### ISSUE TITLE
Tutorial on creating standalone modules which can be imported

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#100]
All tutorials teach users how to create a module as a part of the Substrate Node Template.

We should also write documentation on how to create a standalone module which can be imported into another existing Substrate Node, as there are some nuances.

**Comment by JoshOrndorff** [comment]
@shawntabrizi 's guide about [adding the contract module](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/119) to node template will probably be helpful when writing this.

**Comment by JoshOrndorff** [comment]
Drafted this in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/141

**Comment by shawntabrizi** [comment]
#141 is merged
