### ISSUE TITLE
Need Clarification - Configure Nicks Pallet Code and Comment

### ISSUE THREAD

**Issue by narulasrinivas** [substrate-developer-hub/substrate-developer-hub.github.io#1009]
In [Configure Nicks Pallet](https://substrate.dev/docs/en/tutorials/add-a-pallet/configure-a-pallet) documentation page, code in `runtime/src/lib.rs` file is different from documentation and substrate-node-template v3.0.0. Please refer below screenshots.

Below code is given in documentation
```
 // No weight information is supplied to the Balances pallet by the Node Template's runtime.
    type WeightInfo = ();
```
But in node template code v3.0.0, it has
`type WeightInfo = pallet_balances::weights::SubstrateWeight<Runtime>;`

Can someone explain whether both the codes means samething or do we need to update the documentation with the latest node template code?

![image](https://user-images.githubusercontent.com/2491903/118415816-7b08d400-b6a4-11eb-8330-c3129ee28b71.png)

![image](https://user-images.githubusercontent.com/2491903/118415682-beaf0e00-b6a3-11eb-887e-7849898eb0cd.png)

**Comment by al3mart** [comment]
Hey @narulasrinivas 

Indeed there is a version mismatch between the information shown in the tutorial and the current version of node-template runtime.

As you can read for the tutorial version of the code no information is given about the weights, but the following line 

` type WeightInfo = pallet_balances::weights::SubstrateWeight<Runtime>;` 

means that it will use the weight information defined in SubstrateWeight. Nothing further than that.

As all the links point to current versions, the way to proceed will be creating a PR to update the code shown in that tutorial' section so it matches the latest version

**Comment by narulasrinivas** [comment]
@al3mart - Thanks for clarifying this. 

I'm happy to do that change. 

But do we've any process or steps documented somewhere to raise an PR.

**Comment by al3mart** [comment]
Sure there is :) https://github.com/substrate-developer-hub/substrate-developer-hub.github.io#contributing

**Comment by al3mart** [comment]
Feel free to tag me for review on those changes if you have time

**Comment by narulasrinivas** [comment]
I'll do that change and tag you for review. (y)

**Comment by narulasrinivas** [comment]
@al3mart - I followed below steps to complete this change

1. Created a new local branch (`update-tutorial-addpallet`) from `source` branch.
2. Update code in local repo
3. Committed to local branch
4. Tried to Push new local branch to remote location. But getting access denied since I'm not part of collaborator group.

`remote: Permission to substrate-developer-hub/substrate-developer-hub.github.io.git denied to narulasrinivas.`

Once branch get created, I raise a PR for review for other git repos.

Can you please help me on this?

**Comment by NukeManDan** [comment]
@narulasrinivas you need to fork the repo and push to that. Then create a PR 😁 
1. fork this repo
2. make a new branch on the fork
3. add remote for your new git: `git add remote narulasrinivas git:github.com/narulasrinivas/substrate-developer-hub.github.io.git` (or something close to this)
4. push to this remote: `git push narulasrinivas/<your branch>
5. open a PR 
http://www.dasblinkenlichten.com/how-to-create-a-github-pull-request-pr/

**Comment by narulasrinivas** [comment]
@NukeManDan - Sorry my bad. I got so used to branching and merging missed a point, Thanks for helping out. I did changes by forking the project.

@al3mart - Here is the [PR Link](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/1011) Please check from your end.

**Comment by NukeManDan** [comment]
Now I see the relation, and that #977 is actually a duplicate that we had not previously included. Opting for that PR, and will like to close this issue. Thanks for the extra context and work on this @narulasrinivas ! 😁
