### ISSUE TITLE
Gather info about teams building on substrate

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#101]
The landing page of the new developer hub will have a section featuring teams building on substrate. For each team we will need.
[ ] Project Name
[ ] Logo
[ ] Link
[ ] Permission

According to riot chat @joepetrowski can help out with that this week, so I'm assigning this to him (to get the info) and @shawntabrizi (to enter the info).

I am happy to help out however I can, so ping me or assign me if necessary.

**Comment by joepetrowski** [comment]
Good place to start (public site): https://forum.web3.foundation/t/teams-building-on-polkadot/67

**Comment by shawntabrizi** [comment]
Initial backfill: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/commit/6fa098f99a76ad685092d673673909b6be4e09b2

Follow up to this should be some sort of tweet from the Parity Tech/Polkadot twitters asking users to add/edit themselves using PRs to the config file

**Comment by fabiangmpf** [comment]
Here is an initial list of teams that are building publicly: https://github.com/fabiangmpf/substrate-adoption. Should be a good start for content.

**Comment by fabiangmpf** [comment]
> Good place to start (public site): https://forum.web3.foundation/t/teams-building-on-polkadot/67

I'd be a little bit careful with this list. Let's focus on teams with public repos / testnets first before we jump to conclusions on the basis of old tweets and blog posts (which is what this list is doing sometimes).

**Comment by shawntabrizi** [comment]
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/commit/2a7f008983e09b14468d2557c11378577824657d

This is an update to:
* Alphabetize the list
* Choose some names to be featured on the home page

@fabiangmpf I can also include whoever is on your list, but I would need specific feedback to remove some names.

**Comment by fabiangmpf** [comment]
Yep, I will go over it and give some feedback on what to add / remove.

**Comment by JoshOrndorff** [comment]
FWIW Joystream team has agreed to be included via Riot chat.

I'm going to close this issue. Please re-open or open new issues when changes are necessary.
