### ISSUE TITLE
404 It seems we couldn't come to consensus... Error

### ISSUE THREAD

**Issue by alexkeston** [substrate-developer-hub/substrate-developer-hub.github.io#1024]
Hi when I clicked a link given "Polkadot UI" on the UI Demo Section, in the following content: https://github.com/substrate-developer-hub/utxo-workshop#Installation

It showed me the following error. "404 It seems we couldn't come to consensus..." Is there any new alternative to following link?

**Comment by NukeManDan** [comment]
That workshop is not maintained unfortunately. updated to what I think was intended: https://github.com/substrate-developer-hub/utxo-workshop/commit/c77be105605a9e6429f0128a96a71f6c46bbcf88
