### ISSUE TITLE
Create Translation Recruitment Page

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#103]
Docusaurus supports a "Help Translate" button which takes a user to a defined link:

https://docusaurus.io/docs/en/site-config#translationrecruitinglink-string

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1860335/59270692-6e76d800-8c52-11e9-8ead-df2cd29b116a.png">

We should set up instruction page with possibly even a bounty for users who spend enormous efforts to help us keep docs up to date in different languages.

**Comment by JoshOrndorff** [comment]
I couldn't find any more docs than what's linked above

> translationRecruitingLink [string]
>
>URL for the Help Translate tab of language selection when languages besides English are enabled. This can be included you are using translations but does not have to be.

Adding `translationRecruitingLink: 'Help Translate',` to the siteConfig does create the link as shown in the screenshot, but does not point to a reliable URL.

Consider these two examples.
| page I'm on | Link points to |
| --- | --- |
| docs/en/overview/introduction | http://localhost:3000/docs/en/overview/Help%20Translate |
| http://localhost:3000/docs/en/runtime/macros/construct_runtime | http://localhost:3000/docs/en/runtime/macros/Help%20Translate |

**Comment by shawntabrizi** [comment]
You put a fixed link like "https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/contribute.md"

And then they can read instructions on how to help contribute. The link wouldnt be specific per page (but we may be able to hack something together to do that).

Docusaurus links to: https://crowdin.com/project/docusaurus

**Comment by kaichaosun** [comment]
The Crowdin provides a clear workflow for the translation work. An instruction document for translation work could be helpful. Instead of putting the doc link under `Help Translate`, another option is to put the doc under `Docs`, and leave `Help Translate` links to the Crowdin project.

**Comment by JoshOrndorff** [comment]
> You put a fixed link like "https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/contribute.md"

@shawntabrizi You mean that I should/must do that, not that I _did_ do that correct? I definitely know how to create such a page, but I don't know how to get the "Help Translate" link to point to it.

> leave Help Translate links to the Crowdin project.

@kaichaosun Yeah, I think it would be wise to point the help translate link directly to crowdin. But I'm saying I don't see any way to control where that link points. It seems to automatically point to the places I've shown in the [table above](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/103#issuecomment-501004418).

**Comment by shawntabrizi** [comment]
@JoshOrndorff the confusion is that the setting in the config should look like:

```
translationRecruitingLink: 'myurl.com/mylink',
```

In this case, it can be a fixed URL with instructions or a direct link to crowdin

**Comment by JoshOrndorff** [comment]
> @JoshOrndorff the confusion is that the setting in the config should look like...

That makes perfect sense, and I now see that @kaichaosun did it in 4aca42b950de13b0666c807e4725150ccf601e1e
