### ISSUE TITLE
Fix "EVM pallet" duplicate content 

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-developer-hub.github.io#1039]
Improve the [EVM pallet article](https://substrate.dev/docs/en/knowledgebase/smart-contracts/evm-pallet) to avoid duplicating the [Rust docs](https://substrate.dev/docs/en/knowledgebase/smart-contracts/evm-pallet).

**Comment by NukeManDan** [comment]
Will this include closing or finishing #967?
