### ISSUE TITLE
High-level (TOC-level) restructuring of devhub docs

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#104]
Opening this issue to track a discussion starting in riot. We have consensus that the devhub table of contents needs an overhaul.

@nczhu has a draft doc that she will share here.

@gautamdhameja has a list to share also.

**Comment by gautamdhameja** [comment]
I have a list of items that can be included in the Architect path in the docs site. This is a follow-up to my discussion with @shawntabrizi about what can be included in this learning path.

Here's the proposed list:

1. Substrate high-level overview - https://substrate-developer-hub.github.io/docs/en/overview/introduction

2. Architecture of runtime

3. Transaction life-cycle - https://substrate-developer-hub.github.io/docs/en/overview/transaction-lifecycle

4. Integration tools overview: Codec, JSON RPC Proxy (any others?)

5. Off-chain workers and integration with external data sources.

6. Building decentralized solutions with Substrate - TODO (with the app-dev diagram)

7. Get in touch. (solutions@parity.io) (should we add it here???)

**Comment by nczhu** [comment]
ToC suggestion

*we have most of this content already, with the exception of items marked [todo]*

- Overview
	- Introduction
	- Overall Architecture: Libp2p, consensus, runtime, wasm (Node, SRML, Core) [content available in blogs]
	- Polkadot Network [link out to web3 wiki]

- Quickstart
	- Installing & updating
	- Starting with the node (deploy a chain in 6 minutes)
	- Starting with SRML

- Node [todo]

- Runtime
	- Runtime Architecture: we should combine [this](https://docs.substrate.dev/docs/architecture-of-a-runtime) and [this](https://docs.substrate.dev/docs/srml-overview). 

	- Explaining each SRML: i.e. explain srml reference docs in greater detail, more approachable. For now, it would be great if we can just over the introduction sections for each module and link to its page in http://crates.parity.io. Another thing we can add to these pages are Amar’s recipes.
		- How to use Timestamp & Traits
		- How to use Balances & Traits
		- How to use Staking & Traits
		- etc.
	- SRML Macros
	- SRML Types
	- Testing SRML [in progress?]

- Core [todo later]

- Substrate in Depth
	- Extrinsics
	- The transaction lifecycle
	- The account lifecycle
	- The off chain execution lifecycle [todo]

- Substrate Extended Ecosystem
	- Smart contracts on Substrate [link out]
	- Substrate UI [link out]
	- Subkey
	- JSON RPC

- Best Practices & Security

- Glossary

- Feedback / contact page

**Comment by shawntabrizi** [comment]
@nczhu You think we should have a seperate docs page for smart contract development and Substrate UI?

Where would those be?

**Comment by JoshOrndorff** [comment]
@nczhu I really like the structure of the runtime section!

Is "deploy a chain in 6 minutes" something like this?
1. download a binary package
2. substrate --dev

**Comment by nczhu** [comment]
> @nczhu You think we should have a seperate docs page for smart contract development and Substrate UI?
> 
> Where would those be?

I am suggesting we link out of the developer hub for that content, with an optional short writeup on what it is before linking people out.
 
1. For UI things: we can link out to [this wiki](https://polkadot.js.org/api/) and [this other repo](https://github.com/paritytech/substrate-light-ui). 

2. For smart contracts, up to you. At our last group chat, I remember you saying Substrate Smart Contracts will have its own wiki. The content is certainly complex/important enough to warrant that.

**Comment by nczhu** [comment]
> @nczhu I really like the structure of the runtime section!
> 
> Is "deploy a chain in 6 minutes" something like this?
> 
> 1. download a binary package
> 2. substrate --dev

Yeah - something like that! We want to drive home the value proposition that "you can now deploy a blockchain in 6 minutes and interact with it". So exactly as you mentioned, just have the user download/build binary, deploy with defaults, && briefly interact with it in [Substrate UI](https://polkadot.js.org/apps/#/) 

Feel free to assign this to me if you think having a section like this makes sense 😁

**Comment by kaichaosun** [comment]
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/166#issuecomment-512408811
