### ISSUE TITLE
Reviving video page

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#1042]
Will be great to revive our video page: https://substrate.dev/videos, highlighting event series such as:

- Polkadot Decode series
- Sub 0.1 2020 series
- Sub 0.1 2019 series

**Comment by NukeManDan** [comment]
The only issue I know of though, is that these are very quickly out dated, when it comes to specifics on code, sub0 for instance many workshops are now very state. But concepts are good. I wonder how we could make this apparent, and cater content to be long-lived, without introducing a reason for many to ask for support on outdated and unsupported demos and such.

**Comment by jimmychu0807** [comment]
I am thinking mostly(or only) putting our previous major event videos in. So ppl know how outdated they are and decide if they still want to watch them.

**Comment by NukeManDan** [comment]
Maybe just a little disclaimer for that point on the site would be good then 😁

**Comment by stiiifff** [comment]
@NukeManDan Yes ! I can see how useful it would be to surface content related to a project / pallet on the marketplace. How we do it is a question for @imadarai I think (sounds like content aggregation done during static site generation ?)

**Comment by imadarai** [comment]
@stiiifff @NukeManDan 
Does this need to house in DevHub or should this be part of Ecosystem?  I'll bring it up in the conversation with team, so we can try to have this in next iteration.

**Comment by NukeManDan** [comment]
IMHO it doesn't _need_ to live in devhub. But a curated list of videos that someone actively maintains would be great (if it is **maintained** 😉  ) we can point to it from anywhere. I think the marketplace makes most sense in that it's highly searchable (perhaps the best thing that the devhub lacks somewhat), so videos in context would appear and give a user options on paths forward to learn / tools to use.

**Comment by jimmychu0807** [comment]
closing this issue, and relying on substrate.io to showcase video content.
