### ISSUE TITLE
Bad command line in "Create Your First Substrate Chain"

### ISSUE THREAD

**Issue by h4x3rotab** [substrate-developer-hub/substrate-developer-hub.github.io#1049]
<https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup>

It says:

```bash
git clone -b v3.0.0+monthly-2021-05 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
```

But if you run `cargo build --release`, it complains:

```
error: failed to download `parity-db v0.2.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/h4x/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-db-0.2.3/Cargo.toml`

Caused by:
  failed to parse the version requirement `0.11 ` for dependency `parking_lot`

Caused by:
  expected comma after minor version number, found '\t'
```

The latest commit have this issue fixed. We may need to change the tutorial as well.

**Comment by NukeManDan** [comment]
I think we will wait to update once the next monthly arrives, and we will use this tag to update at least that tutorial. @jimmychu0807 , would you be willing to do that once the release lands?

We don't want to point to a _specific commit_ that is known working, or even worse, float on master that likely will not be working from time to time. Trying to get the devhub here as reliable to build as possible with minimal upkeep (the time we to maintain & improve the dehub is constrained at the moment)

**Comment by jimmychu0807** [comment]
@h4x3rotab if you remove the `Cargo.lock` and recompile again, this should make the node-template compilable again. `parity-db` has been updated to `v0.2.4`.

**Comment by NukeManDan** [comment]
Also a cargo update of this package would work then

```
cargo update -p v0.2.4
```

As deleting the cargo.lock file may actually case other things to break. It's better practice to just update instead from what I have experienced. But if it works to  delete, then you might get some updates you didn't expect to without the breaks 🤷🏼
