### ISSUE TITLE
Migrate to docusaurus 2

### ISSUE THREAD

**Issue by gilescope** [substrate-developer-hub/substrate-developer-hub.github.io#1050]
I know it's not quite cooked yet but thought I'd put it on the horizon. Personally I would like to use (synced) tabs to only show the frame v2 documentation and hide the v1 documentation in another tab. But seems that tabs is really a docusaurus 2 thing.

I did an initial trial migration
`npx @docusaurus/migrate migrate --mdx --page ./website ./website2`
those --mdx and --page flags do mess some stuff up compared to not setting them so there's some work to be done there.

Seems like search and replace require("../../../../react-bootstrap/Button") ->  require("react-bootstrap/Button") is required, but also a few other things...(how long this piece of string is yet I don't know)

**Comment by NukeManDan** [comment]
Totally think you are on the right page with respect to needing some polish on these docs - the team here is working on it!

I know @imadarai is testing a Gatsby version of this site that is starting to look really good (not ready for prime time yet). This will include versioning, better mobile support, and a few minimal custom `.mdx` extensions to make the docs look and feel much more modern and have better UX 🤞🏼 

Are you interested in contributing to this effort once we have it more polished @gilescope ?

**Comment by gilescope** [comment]
Good docs are important and I'm only going to be new to substrate once so that's the time to try and improve the docs. (I'm rust rather than JS so I'm probably limited help on the web side of things unless you're doing the new version in seed-rs)

**Comment by NukeManDan** [comment]
The content is going to be mostly ported, so anything you would like to contribute in that end is more than welcome! I will be sure to make it transition into the new look and feel. Happy to review any PRs you have, just @ me 😁
