### ISSUE TITLE
Integrate search into dev hub

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#106]
Docusaurus supports search capability https://docusaurus.io/docs/en/search It should be set up here.

**Comment by JoshOrndorff** [comment]
> Once your website is online, you can submit it to DocSearch.
```javascript
const siteConfig = {
  ...
  algolia: {
    apiKey: 'my-api-key',
    indexName: 'my-index-name',
    algoliaOptions: {} // Optional, if provided by Algolia
  },
  ...
};
```

I wonder if it needs to be at the right domain first.

**Comment by JoshOrndorff** [comment]
According to https://community.algolia.com/docsearch/who-can-apply.html#the-checklist, we need to go live first.

- [x] You must be the owner of the website, or at least have the power to update its content. You'll have to include a JavaScript snippet to enable DocSearch.

- [ ] Your website must be publicly available. We do not host index for websites that are available behind an authentication or a private network.

- [x] Your website must be a documentation website. We do not index blogs or commercial content.

- [x] Your website must have some final content. We won't index empty websites nor those filled with lorem ipsum placeholder content. Please, wait until you have written some documentation before applying. We would be happy to help you as soon as you have a steady design.

Sounds liek this will be pretty easy once the site launches.

**Comment by JoshOrndorff** [comment]
Now that all the checklist items are complete, I've applied for search.

> Thank you!
>
> Your request will be processed by our team.
>
> We'll get back to you on joshy@parity.io with the snippet of JavaScript you'll need to integrate into https://substrate.dev.
>
> Please be patient, it can take a few days.

They [also said](https://community.algolia.com/docsearch/who-can-apply.html#priority) open source projects, and projects using supported plugins (like docusaurus) get priority

**Comment by shawntabrizi** [comment]
@JoshOrndorff I read that through the process they might contact you about which pages to index or ignore or whatever. If you get the chance to speak to them, can you ask them if their search will work across multiple platforms. For example, when I use the search bar at `substrate.dev` will I get results from `substrate.dev/recipes`? (which is a seperate rust docs project, but under the same domain)

Can we get search results for `crates.parity.io` which is a seperate project AND a seperate domain?

If not, we should also do work to make a repo under this project for the Substrate reference docs so we get a url like: `substrate.dev/rustdocs/` or something

**Comment by JoshOrndorff** [comment]
@shawntabrizi Awaiting direct answer to those questions. In the meantime, this is the actual code of the scraper they use to crawl our website. https://github.com/algolia/docsearch-scraper

**Comment by JoshOrndorff** [comment]
Notes on styling the search bar: https://community.algolia.com/docsearch/styling.html

**Comment by JoshOrndorff** [comment]
Done in 52de5e120d85ac58d4fa31b8b7e9f3bedce1cebc
