### ISSUE TITLE
404 getting started page

### ISSUE THREAD

**Issue by DiazRock** [substrate-developer-hub/substrate-developer-hub.github.io#1062]
On the repo, clicking on this [link](https://substrate.dev/docs/en/overview/getting-started/) its giving me 404 not found. I don't know where to start

**Comment by NukeManDan** [comment]
Where did you find the link you posted above?

use: https://substrate.dev/docs/en/knowledgebase/getting-started/

And in case you are unsure, use https://substrate.dev/ 😀
