### ISSUE TITLE
decl_storage decl_... not valid anymore

### ISSUE THREAD

**Issue by gww-parity** [substrate-developer-hub/substrate-developer-hub.github.io#1064]
decl_storage decl_... not valid anymore, please update:

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/tutorials/add-a-pallet/configure-a-pallet.md

We can find e.g. :
"Because it uses the decl_storage! macro." or "Because it uses the decl_event! macro"

But when we look at "Nicks pallet"
https://github.com/paritytech/substrate/blob/master/frame/nicks/src/lib.rs

it uses:

`#[pallet::storage]` etc.

**Comment by NukeManDan** [comment]
These are actually backwards compatible. If you look at master on substrate, there are many using FRAME V1 macros like this. I agree, everything _should_ move to V2 ASAP. #1075 fixes the mismatched style 😁
