### ISSUE TITLE
install all windows dependencies by chocolatey

### ISSUE THREAD

**Issue by saintfeng** [substrate-developer-hub/substrate-developer-hub.github.io#1073]
[https://substrate.dev/docs/en/knowledgebase/getting-started/windows-users](https://substrate.dev/docs/en/knowledgebase/getting-started/windows-users)

I happened to see this page and I'm already a chocolatey user. 
So I tried to install all the dependencies by choco. 
finally, I got substrate-node-template compiled and run on the windows.
I think I can help the substrate doc a bit by sorting this procedure out.

how do you think of this?

**Comment by NukeManDan** [comment]
I have not heard of chocolatey, if you think it greatly improves usability over WSL2, then it could be useful. But the devhub and substrate are really centric on *nix type systems and assume a `sh` interface for almost every demo. Does choco provide this?

**Comment by saintfeng** [comment]
chocolatey is a package manager on windows, like apt on ubuntu. the doc has already guided users to install **make** by choco.
that's why I think it makes sense to make full use of choco to get a more fluent experience for windows users.

**Comment by NukeManDan** [comment]
Awesome :) I would be open to review a PR to windows instructions, and can get a windows user maintainer to try it out too

**Comment by saintfeng** [comment]
OK. It's my honor to contribute to substrate doc. will PR soon.

**Comment by saintfeng** [comment]
PR https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/1082
