### ISSUE TITLE
Forkless Upgrade a Chain tutorial is out of date

### ISSUE THREAD

**Issue by NarkomDe** [substrate-developer-hub/substrate-developer-hub.github.io#1074]
I've been following [tutorials](https://substrate.dev/en/tutorials) and had problems compiling code in a [Forkless Upgrade a Chain Sudo Upgrade step](https://substrate.dev/docs/en/tutorials/forkless-upgrade/sudo-upgrade). 
I'm trying to do this on top of a node created by the current tuturial for [Create Your First Substrate Chain](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/).
After investigating deeper, I've changed pallete import in Cargo.toml from
`pallet-scheduler = { default-features = false, version = '3.0.0' }`
to
`pallet-scheduler = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }`
And I've changed construct_runtime import from
`Scheduler: pallet_scheduler::{Module, Call, Storage, Event<T>},`
to
`Scheduler: pallet_scheduler::{Pallet, Call, Storage, Event<T>},`
to make it more consistent with what I found in a current node code. That solved compilation issues for me.
I think it would be great to solve this issue to avoid any further confusion for people following tutorials.

**Comment by NukeManDan** [comment]
Agreed. Having uniform versioning throughout the devhub is happening in a soon to be released overhaul of this site. Where you can select for a specific version. 🔜
