### ISSUE TITLE
Some translations are out of date

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#111]
The CI output for #82 contains

```
Warning: Downloaded translations do not match current project configuration. The following files will be omitted:
 - '/website/translated_docs/ja-JP/ecosystem/keys-seeds-and-the-subkey-tool.md'
 - '/website/translated_docs/ja-JP/tutorials/substrate-runtime-recipes.md'
```

The subkey page was recently renamed, and the recipes page was recently removed.

Are there things that we need to be aware of when adding, moving, or deleting English content?

**Comment by kaichaosun** [comment]
I check the Crowdin CLI command options, also chat the admin of Crowdin. Currently, there is no option to delete old files that are not in the source files locally anymore. Once they are uploaded to the Crowdin, they can not be deleted with CLI, but they can be deleted through UI.
This means we should regularly check the warnings and delete them manually. 
That's not much effort after the docs become stable.

**Comment by kaichaosun** [comment]
BTW, I fixed the warnings for now.

**Comment by kaichaosun** [comment]
The warning was removed in the latest build, will close this issue.
