### ISSUE TITLE
Create your first substrate chaine - Troubleshooting - new paragraph suggestion

### ISSUE THREAD

**Issue by claudiociardelli** [substrate-developer-hub/substrate-developer-hub.github.io#1115]
The troubleshooting section in https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact only explains how to resolve the issues found if the node template is on a different server as the front end template.

I have experienced other issues when the node and front end are run on a linux machinte without GUI and the URL to the front end template is called from a remote machine (a windows 10 browser in my case). 

The browser then starts loading the front end (you see a connecting to substrate message) but then reports "Error Connecting to Substrate { "isTrusted": true }"

There is a very clear explanation of the changes to be done in this blog https://www.howtosolutions.net/2021/01/fixing-error-connecting-to-substrate-front-end-template-remote-clients/
1) use the  --ws-external option when running the node
2) replace 127.0.0.1 by the IP of your server in /src/config/development.json

**Comment by NukeManDan** [comment]
Thanks for the :grin: 
To be included here https://github.com/substrate-developer-hub/substrate-docs/issues/173
