### ISSUE TITLE
Forkless Upgrade tutorial. Error in code snippets

### ISSUE THREAD

**Issue by claudiociardelli** [substrate-developer-hub/substrate-developer-hub.github.io#1117]
The code to be added to construct_runtime! in the "Forkless Upgrade" tutorial is incorrect. Causes an error inthe cargo build.
page https://substrate.dev/docs/en/tutorials/forkless-upgrade/sudo-upgrade

Line 
    Scheduler: pallet_scheduler::{Module, Call, Storage, Event<T>},
should be
    Scheduler: pallet_scheduler::{Call, Storage, Event<T>},

removing "Module" compiles correctly.

**Comment by claudiociardelli** [comment]
In fact Line
Scheduler: pallet_scheduler::{Module, Call, Storage, Event},
should be
Scheduler: pallet_scheduler::{Pallet, Call, Storage, Event},

"Module" should be replaced with "Pallet"

**Comment by NukeManDan** [comment]
This depends on your substrate version. v3.0.0 is used here, where Module is correct. 
What version are you using?

**Comment by claudiociardelli** [comment]
You are right. Looking at cargo tree most of the dependencies are 4.0.0.

**Comment by tifrel** [comment]
Made a PR which also clarifies that the browser UI needs (at least for me) a refresh, before I can access the Scheduler pallet extrinsics, and another one to see the updated existentialDeposit.
