### ISSUE TITLE
Tracking the localization & translation

### ISSUE THREAD

**Issue by kaichaosun** [substrate-developer-hub/substrate-developer-hub.github.io#136]
Hub is planned to support multi-language besides English, initially:
* Chinese
* Japanese
* Korean
* Russian

Add comments if you want to be the owner of one.

**Comment by kaichaosun** [comment]
Stable (High Priority)


Unstable (Low Priority)

**Comment by kaichaosun** [comment]
@shawntabrizi @JoshOrndorff 
## Below is the draft priority comment:
💚 high 
🔻 low 
- getting-started (:green_heart:)
- substrate-fundamentals / overview
  - introduction (:green_heart:)
  - extrinsics (:green_heart:)
  - transaction-lifecycle (:green_heart:)
  - low-level data format (:green_heart:)
  - substrate off-chain workers (:green_heart:)
  - session keys (:green_heart:)
  - SS58 address foramt (:green_heart:)
  - glossary (:green_heart:)
  - substrate bonds (:small_red_triangle_down:)
  - telemetry (:small_red_triangle_down:)
  - versioning (:small_red_triangle_down:)

- runtime (mostly :green_heart:)
  - runtime and api (:small_red_triangle_down:)
- substrate contracts
  - introduction (:small_red_triangle_down:)
  - install ink! (:green_heart:)
  - cargo contract: the ink! cli (:green_heart:)
  - test your contract (:small_red_triangle_down:)
  - deploy a contract (:green_heart:)
  - faq (normal)
- ecosystem
  - subkey tool (:green_heart:)
- Contraibute
  - help translate (normal)
- tutorials
  - tcr (:green_heart:)
  - adding a module to your runtime (:green_heart:)
  - creating your first contract (:green_heart:)
  - creating your first substrate chain (:green_heart:)
  - start a private network with substrate (:green_heart:)
  - governance "public" mechanism with a substrate node chain (:small_red_triangle_down:)
  - validator nodes and nominators on substrate chains (:small_red_triangle_down:)

- en.json contains all the strings in pages (:green_heart:)

**Comment by JoshOrndorff** [comment]
I'd mark the session keys as low priority. I'm thinking that isn't even implemented anywhere yet. ([source](https://wiki.polkadot.network/en/latest/polkadot/learn/keys/#session-key))
