### ISSUE TITLE
Display search results from entire site

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#145]
My first attempt was https://github.com/algolia/docsearch-configs/pull/894 but search still hasn't indexed the rustdocs or /recipes.

Now considering whether [selectors](https://community.algolia.com/docsearch/config-file.html#selectors) or [sitemap](https://community.algolia.com/docsearch/config-file.html#sitemaps) are the issue. Here's a good [example of multiple selector sets](https://github.com/algolia/docsearch-configs/blob/master/configs/accengage.json).

Also trying to find a better way to debug / fix this, than submitting a PR to docsearch-configs, waiting for it go get merged, waiting 24 hours for a crawl. [Instructions for self-hosting](https://community.algolia.com/docsearch/run-your-own.html).

**Comment by JoshOrndorff** [comment]
Trying to [run the crawler](https://community.algolia.com/docsearch/run-your-own.html) myself I installed the dependencies and ran
```
docker run -it --env-file=.env -e "CONFIG=$(cat substrate.json | jq -r tostring)" algolia/docsearch-scraper
```
but it failed with a long python traceback ending with
```
algoliasearch.helpers.AlgoliaException: Unreachable hosts: {'substrate-3.algolianet.com': "ConnectionError: HTTPSConnectionPool(host='substrate-3.algolianet.com', port=443): Max retries exceeded with url: /1/indexes/substrate_tmp
```

I'm not sure where it got `substrate-3.algolianet.com`

**Comment by JoshOrndorff** [comment]
Asked for help on the Algolia forum https://discourse.algolia.com/t/how-to-index-entire-site-not-just-docusaurus/7988

**Comment by JoshOrndorff** [comment]
FWIW, The `crawler` branch contains my attempts at manually running the crawler https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/tree/crawler/crawler

**Comment by JoshOrndorff** [comment]
The Algolia community, and in particular @s-pace have been tremendously helpful here. He seems to be [confirming that the issue is with our selectors](https://github.com/algolia/docsearch-configs/pull/894#issuecomment-505736916).

I've gotten further toward running the crawler manually but still not successful. I've created an algolia account and learned our application ID. I've also learned that the API key in our siteConfig.js is for _reading_ the index only and we'll need another one to write to the index. Free accounts cannot create additional api keys, so there are two options for how to proceed.

**Option 1** Try new selectors directly as PRs against the [config repo](https://github.com/algolia/docsearch-configs/)
Con: Wait time for each PR to be merged
Con: Changes (including incorrect ones) will affect live site
Pro: Pretty straightforward workflow
Pro: Free of cost

**Option 2** Pay for an algolia account
Con: Costs Money
Con: Still have to learn how to run crawler manually
Pro: Support Algolia who supports open source
Pro: Less hasle to make future refinements to the config

**Comment by JoshOrndorff** [comment]
Also noticing that their PR template suggests a sitemap is very important https://github.com/algolia/docsearch-configs/blob/master/.github/PULL_REQUEST_TEMPLATE#L7

I wonder where ours came from.

**Comment by JoshOrndorff** [comment]
Proceeding briefly via option 1 to see just how feasible it is. This PR attempts to start indexing on just the rustdocs portion of the site while leaving the docusaurus portion in tact. https://github.com/algolia/docsearch-configs/pull/907

**Comment by JoshOrndorff** [comment]
algolia/docsearch-configs#907 got merged 18 hours ago, and even had some contributions from an algolia team member, but still no rustdocs in the index. I'm feeling pretty stuck on this one.

**Comment by s-pace** [comment]
rustdocs is indexed. Please give it a try, may be an old crawl was made.

Cheers

**Comment by JoshOrndorff** [comment]
Okay, so @s-pace is correct. The rustdocs contents _are_ indeed in the index.

Here's a pretty [simple page](https://substrate.dev/rustdocs/v1.0/substrate_service/type.CodeExecutor.html) from our rustdocs. When I go to substrate.dev and type "CodeExecutor" into the search bar, I get **no results**.

Removing [this language filter](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/website/siteConfig.js#L139) from our docusaurus siteConfig. That line first went in in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/commit/f07250879d6917887df24dd5aeda6ea6f0a9e030 to prevent search results from other languages showing.

Interestingly, removing that line now does _not_ seem to bring back the Chinese language search results.

So the current status is
* Everything seems to be working the way we want
* I'm not clear on _why_ it is working the way we want.

**Comment by shawntabrizi** [comment]
@JoshOrndorff All this testing you are doing is locally? I am not able to repo RustDoc search results on the live page

**Comment by JoshOrndorff** [comment]
@shawntabrizi Yes, I had not pushed that change because I didn't want to make changes to the live site yet.

Here is a branch that removes the language filter and therefore shows the rustdoc results https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/tree/no-language-filter

Exploring again now it seems that removing that filter includes the rustdoc results _and_ includes the chinese results which actually makes more sense to me.

**Comment by shawntabrizi** [comment]
I think this was the fundamental issue:
https://community.algolia.com/docsearch/config-file.html#sitemap_urls-optional

> You can pass an array of URLs pointing to your sitemap(s) files. If this value is set, DocSearch will try to read URLs from your sitemap(s) instead of following every link of your starts_urls.

We had this configuration set, and the `sitemap` being generated via Docusaurus build. However this does not include our other projects and files.

My guess is that if we remove the `sitemap` configuration option, and instead let the crawler do a brute search by following every link, we will get all the results we want.

I will open a PR

**Comment by JoshOrndorff** [comment]
This issue is specific to the docusaurus site and algolia search. Closing as a new search will be built for the new site.
