### ISSUE TITLE
Log type seems to be removed

### ISSUE THREAD

**Issue by kigawas** [substrate-developer-hub/substrate-developer-hub.github.io#149]
The log type describe [here](https://substrate.dev/docs/en/runtime/macros/construct_runtime#log) is already removed after this [pr](https://github.com/paritytech/substrate/pull/2802/files#diff-9ccf13e5a11a7f6c4a3a49d89ef37d8dL97).

Now it seems that a `DigestItem` should be used like [this](https://github.com/paritytech/substrate/pull/2802/files#diff-9ccf13e5a11a7f6c4a3a49d89ef37d8dR177).

**Comment by kigawas** [comment]
https://github.com/paritytech/substrate/pull/2802

**Comment by JoshOrndorff** [comment]
@kigawas The PR you mentioned is against master, and we've been focusing our efforts here on documenting v1.0. So I don't think we should remove the information you linked from the devhub.

That being said, we will, at some point, need to document newer versions, and we probably shouldn't wait until there is a huge backlog of changes built up. We're using docusaurus to host our docs and it supports versions. We haven't explored the versions feature yet, but I would welcome a PR that add's a version like "next" that documents the latest stuff in master.

Default version should definitely stay as v1.0 for the next while.

**Comment by kigawas** [comment]
@JoshOrndorff 
Reasonable, but not exactly the case. AFAIK all the links in the doc referring to substrate repo are against master, thus discrepancy will occur especially when a curious user clicks the link.

Also, the developer hub's installation guide is also [based on master](https://substrate.dev/docs/en/getting-started/installing-substrate#manual-build). 

From my point of view, the develop hub doc should have a dev/stable switch at least, otherwise it'll be a disaster to follow updates when substrate 2.0 released.

**Comment by JoshOrndorff** [comment]
Good catch on the install instructions. Our _intention_ has been to document v1.0, but you're right that we haven't always made that clear or totally consistent.

> From my point of view, the develop hub doc should have a dev/stable switch at least, otherwise it'll be a disaster to follow updates when substrate 2.0 released.

Agreed. Versioning is one of the reasons we chose docusaurus. Here are there docs about getting [set up with versioning](https://docusaurus.io/docs/en/versioning and here), and our [own issue](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/118) tracking it.

My suggestions is to solve that issue by setting up versioning, then make this update about `Log` in the 2.0.0 branch.

**Comment by shawntabrizi** [comment]
It would also be cool to create a page with generally tracks breaking changes that have happened between major releases. Nothing crazy to manage, but maybe some long bullet point index with a short summary of the breaking change and the PR where it happened.

We should be able to sort of generate this by looking at the history of the `spec_version` number in the Substrate codebase.

**Comment by bkchr** [comment]
I think we should at least introduce some label `changelog` or similar in Substrate, to highlight prs that needs to go into a changelog.
