### ISSUE TITLE
Add Substrate installation instruction for Windows

### ISSUE THREAD

**Issue by kaichaosun** [substrate-developer-hub/substrate-developer-hub.github.io#153]

**Comment by JoshOrndorff** [comment]
@laboon You worked through installing on windows before the Pittsburgh meetup, right? Do you have anything written we can start from?

**Comment by laboon** [comment]
I don't have anything written down, unfortunately.  I used the basic instructions found here: https://github.com/paritytech/substrate.  If memory serves, I think I also had to add cmake to the PATH manually.

**Comment by shawntabrizi** [comment]
I wrote those instructions and know a few ways to improve them further. I will make a PR soon to add windows specific install instructions in the dev hub
