### ISSUE TITLE
Add Instructions for Polkadot JS <> Subkey

### ISSUE THREAD

**Issue by joepetrowski** [substrate-developer-hub/substrate-developer-hub.github.io#159]
I moved some Alexander .json files to a different computer and tried to restore the secret key using subkey. Polkadot JS obviously finds it because I imported the json to the UI and was able to sign transactions.

Right now our docs basically say "figure it out for yourself."
https://substrate.dev/docs/en/ecosystem/subkey#more-subkey-to-explore

If someone shows me the subkey command I will write the docs for going back and forth.

**Comment by JoshOrndorff** [comment]
AFAIK, subkey cannot read those json files. The exercise that I intended the user to figure out on their own was copying a mnemonic from the apps UI and then running `subkey inspect "<copied phrase">`.

I agree that that exercise could be more clearly stated

**Comment by joepetrowski** [comment]
If not in `subkey`, we should have instructions on how to decode that JSON. Will be useful for anyone who wants to port addresses to a new wallet.

**Comment by shawntabrizi** [comment]
Related: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/171
