### ISSUE TITLE
Fix Search for Uncommon Substrate Words

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#160]
If you search for `inherent`, the search will try to "fix" it to `interest`:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/1860335/60669017-95998180-9e6d-11e9-9dda-fdb3c836526b.png">

We should have common glossary/blockchain terms protected so search does the right thing here.

**Comment by JoshOrndorff** [comment]
This looks like the option we want. https://www.algolia.com/doc/api-reference/api-parameters/disableTypoToleranceOnWords/

It might go in algolia options in siteConfig.js.
