### ISSUE TITLE
Dead Link to "deploying-a-contract" tutorial

### ISSUE THREAD

**Issue by drdgvhbh** [substrate-developer-hub/substrate-developer-hub.github.io#164]
https://substrate.dev/docs/en/tutorials/creating-your-first-contract

Scroll down to the bottom and click on "deploy a smart contract".

Link is dead because it refers to https://substrate.dev/docs/en/tutorials/contracts/deploying-a-contract but it looks like it should actually refer to https://substrate.dev/docs/en/contracts/deploying-a-contract. 

Interestingly the "creating your first contract" page has the `tutorials` prefix while the  "deploying contract" page does not.

**Comment by shawntabrizi** [comment]
@drdgvhbh thanks, I just patched it here: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/commit/8855c2c0a9e9d9deef73cab8f986fcaaf712e85c

In terms of things being in `tutorial` versus `docs`.... I think we still need to internally make things more clear what goes where. That being said, I think the process of deploying a contract is less of a tutorial, more of a "you need to know how to do this", where as the writing your first contract is very much a step by step guide.
