### ISSUE TITLE
RPC endpoint

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#172]
Should we document the RPC endpoints? There are decent docs from the polkadot-js api https://polkadot.js.org/api/METHODS_RPC.html

But really these endpoints are part of substrate so it makes some sense to document them here.

**Comment by shawntabrizi** [comment]
Ideally the polkadot js docs will find a home in `substrate.dev` similar to rustdocs.

Maybe a page on the main dev hub which redirects users and adds any complementary content, but let's certainly not duplicate information.

**Comment by shawntabrizi** [comment]
Will crate a new issue for this linking to the new page we have for RPC
