### ISSUE TITLE
Document Instantiable Modules

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#182]
Modules that support it can be instantiated multiple times in a single runtime. I've dug fairly deep into this topic the last two days and I'm quite close to having it mastered, but a few small issues and questions remain.

My approach is to start with the node template, upgrade it's template.rs module to support instancing, and install two instances in the runtime. Finally, give each instance a genesis config.

I've made two attempts:
in Substrate v1.0.0: https://github.com/JoshOrndorff/instantiableModules
in Substrate master: https://github.com/JoshOrndorff/substrate/tree/instantiable/node-template
partial video walkthrough: https://youtu.be/XEl59hVcyI8
slides/notes from the video: https://docs.google.com/presentation/d/12jgKTseg2G2P6jTSghEWGrdinpMKf9YjQ-SbP7ziTwY/edit?usp=sharing

Remaining issue:
* In both versions of Substrate, I can't get polkadot js Apps to understand the multiple instances correctly.
* In master Substrate, genesis configuration doesn't seem to be working (It worked when I used DefaultInstance).
* In master Substrate, events are not always emitted correctly.

Feedback and input welcome

**Comment by shawntabrizi** [comment]
It may make sense to spend your efforts documenting this using Substrate v2.0.

Else we will just need to migrate later. I think the API has not changed, so other than sample code and projects, a user should be able to learn from this and apply to 1.0 if needed.

**Comment by thiolliere** [comment]
> * In both versions of Substrate, I can't get polkadot js Apps to understand the multiple instances correctly.

hmm yes there might be issues because I didn't test the js app with many instances but I though it would work because the generated stuff by construct_runtime shouldn't be different between a regular module and one of a specific instance.

> * In master Substrate, genesis configuration doesn't seem to be working (It worked when I used DefaultInstance).

oh ok then it should be fixed, if you can come up with a reproducible error open an issue on substrate.
Code has changed a bit between 1.0 and master and instantiable is affected a bit.

> * In master Substrate, events are not always emitted correctly.

oh this is surprising actually, same this should be fixed, if you have a branch send it to me I can also try and open the issue on substrate if needed

**Comment by thiolliere** [comment]
note that now collective module is used with two instance in node/runtime on master

**Comment by thiolliere** [comment]
first point should have been solved by https://github.com/paritytech/substrate/pull/3188

**Comment by JoshOrndorff** [comment]
@thiolliere I'm back to working on this and I've merged in the change you mentioned, but I still can't get Apps UI to show me that two instances of my module (just the template module modified to support instancing) are installed in the runtime. I've decided to focus entirely on substrate 2.0 and my code is at https://github.com/JoshOrndorff/substrate/tree/instantiable/node-template (Don't merge latest master though or else you won't get block production https://github.com/paritytech/substrate/issues/3330)

I've found that Apps shows whichever instance appears first in `consruct_runtime!` as confirmed by [this commit](https://github.com/JoshOrndorff/substrate/commit/dcc2126e55db730314cb2235fc2b240f3b811148).
![Shows SecondCopy, but not TemplateModule](https://user-images.githubusercontent.com/2915325/62718485-e43dbc80-b9d3-11e9-83ef-1a6c048b5ce1.png)

Using the polkadotjs/api directly `api.rpc.state.getMetadata()` confirms that I'm using metadataV7, and indeed only shows one copy of the module installed. I'd be happy to pair on this if that's helpful.

**Comment by JoshOrndorff** [comment]
Trying to debug further, I see that the full node _does_ work as advertized and Apps handles the Council and TechnicalCommittee just fine. One difference I noticed is that the full node uses `Config<T>` instead of just `Config` like I did. But mine won't compile with `Config<T>`

```
error[E0107]: wrong number of type arguments: expected 0, found 2
   --> node-template/runtime/src/lib.rs:206:1
    |
206 |   construct_runtime!(
    |  _^
    | |_|
    | |
207 | |     pub enum Runtime where
208 | |         Block = Block,
209 | |         NodeBlock = opaque::Block,
...   |
221 | |     }
222 | | );
    | |  ^
    | |__|
    | |__unexpected type argument
    |    unexpected type argument
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

I've tried a few things unsuccessfully to get past that compile error. This seems like a good time to ask some dumb questions.

**Comment by shawntabrizi** [comment]
@JoshOrndorff `Config<T>` versus `Config` is more about if you use generics or not. It is not the problem here.

The error you could be running into could be a problem with the UI. You should confirm by looking at your Runtime metadata and seeing if both modules appear there, or only one.

**Comment by JoshOrndorff** [comment]
This was written in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/208 and finished up in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/217
