### ISSUE TITLE
Reupload and replace Readme.io images

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#184]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1860335/61468891-90b0f380-a97e-11e9-8225-fe942d92746d.png">

Related to #78 

Basically we need to save all the images which are currently hosted on ReadMe.io, and save/upload them to our GitHub repository.

Whoever does this may also want to re-evaluate how our images currently live, since there is not a structure to them. Ideally, I think the images would live very close to the document it is meant for, rather than in a single folder where all images live.

**Comment by JoshOrndorff** [comment]
stale
