### ISSUE TITLE
Dos and Do Nots of Runtime Module Development

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#20]
This might need to be more than one page, and would need someone to come up with a larger plan on what content will be here, and how we will present it

**Comment by JoshOrndorff** [comment]
Much of this content exists already. It should be unified to a single location, and then linked to from relevant places

https://substrate.dev/docs/en/runtime/substrate-runtime-module-library#support-macros
https://substrate.dev/docs/en/tutorials/tcr/tcr-best-practices

I thought there was something in recipes as well, but can't find it now.

At this point my recommendation would be to move the last section of the TCR tutorial to a more general location in substrate.dev, and then add in the content from the first link (if it doens't already exist).

**Comment by shawntabrizi** [comment]
Agreed. Maybe something that feels like this:
https://solidity.readthedocs.io/en/v0.5.10/common-patterns.html

**Comment by gautamdhameja** [comment]
@JoshOrndorff, I'm okay with that. We can remove the last part of the TCR tutorial in favor of this new doc and then we can add a paragraph at the end of part 4 with a link to the new best practices doc. Also, the table of contents in the intro page of the tutorial will need some updates accordingly.

**Comment by shawntabrizi** [comment]
Possibly all of the dos and do nots and common patterns should live in Recipes section instead right?

Could have good recipes and bad ones too

**Comment by shawntabrizi** [comment]
This will be recipes @4meta5
