### ISSUE TITLE
Add Branch Protections and Checks

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#222]
* Check Source Branch builds before new commits are merged
* Make source branch only allow pull requests, no direct changes to master
* Make so that `master` branch can only be updated by our deployment bot

* other?

**Comment by JoshOrndorff** [comment]
The second item means that nobody can push directly to `source` but instead we have to make PRs right?

If so, I think these are all a good ideas.

But I don't have permissions to set that up.

**Comment by shawntabrizi** [comment]
@JoshOrndorff try again now?

**Comment by JoshOrndorff** [comment]
@shawntabrizi Yep, I have access now, Thanks.



[ ] Check Source Branch builds before new commits are merged

[x] Make source branch only allow pull requests, no direct changes to master

[x] Make so that master branch can only be updated by our deployment bot

**Comment by shawntabrizi** [comment]
The build checks are not actually completing

**Comment by JoshOrndorff** [comment]
The issue was that branches in forks were not triggering the build. @shawntabrizi has confirmed it's resolved now.
