### ISSUE TITLE
Add Google Analytics with Klaro Consent

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#227]
We want to add google analytics to Substrate Developer Hub, but we also want to ensure that we are GDPR compliant.

Fortunately, we can use Klaro to do these all without a server.

Here is how it is done for the Kusama Network site:
https://github.com/kusamanetwork/kusama.network/commit/e6e3a7f3d9772a222bf968d8e201fe695c217ff6

We need to use our own fork of the repo to use local storage rather than cookies:
https://github.com/KIProtect/klaro/pull/84

Should also look to add this across all our resources, maybe we can make a generalized plugin for this purpose so we just add one line or something.

---
TODOs
- [x] Substrate developer hub
- [x] Substrate collectables workshop
- [x] Substrate contracts workshop
- [x] Recipes
- [x] Rust docs
- [ ] Support chinese translation, [upstream issue](https://github.com/KIProtect/klaro/issues/1)

**Comment by shawntabrizi** [comment]
We can probably create a centralized plugin that can be reused everywhere, and thus only a single consent is needed across all the substrate.dev sub-sites.

**Comment by JoshOrndorff** [comment]
I'm fine with this implementation if we choose to use analytics. I just want to at least consider not using analytics for all the reasons that Stallman talked about at web3Summit.

**Comment by kaichaosun** [comment]
It seems we have more options:
* Use consolidated GA account
* [Matomo](https://matomo.org/)
* [Snowplow](https://github.com/snowplow/snowplow)

I will use a standalone google analytics account for initial implementation.

**Comment by shawntabrizi** [comment]
@kaichaosun We already have a GA account.

Please use these settings:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-145158313-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-145158313-2');
</script>
```

**Comment by shawntabrizi** [comment]
You can also see how they integrated Klaro into Parity.io:

https://github.com/paritytech/paritytech.github.io/commits/master

**Comment by shawntabrizi** [comment]
@kaichaosun We still want to add these same components to other projects in the Substrate Develop Hub, for example the Kitties tutorial.

Is there some code we can generally copy and paste to make that happen?

**Comment by kaichaosun** [comment]
Yep, I will make sure other resources also add the GA track. The issue seems auto closed, I will reopen it.

**Comment by shawntabrizi** [comment]
It would be good to have some general guide or copy paste code that we could add to other and new sites more easily.

Shouldn't be your responsibility to necessarily add it to every site, but the project owners to follow your guide or copy and paste your code.

**Comment by kaichaosun** [comment]
Cool, I will summarise it in a post.

**Comment by JoshOrndorff** [comment]
It would be really nice if we could actually use the same cookies and settings so users don't have to accept cookies when they go to substrate.dev and then accept them again when they go to kitties, and a third time when they go to rustdocs etc.

If that's more complex, nbd, but if it can be done easily it would be nice.

**Comment by shawntabrizi** [comment]
@JoshOrndorff this too is the implementation I am looking for, and I believe what will be the case with this setup.

**Comment by kaichaosun** [comment]
The steps to integrate GA and klaro:
https://hackmd.io/@2dHpJQYgQrCqfxqXMtJTFQ/Bk6-VMc8B

**Comment by JoshOrndorff** [comment]
@kaichaosun I think this is done right? Re-open if it's not done.
