### ISSUE TITLE
OnChange function not explained sufficiently in front-end tutorial

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#233]
I'm not clearly understanding the `onChange` function described in [part 3.1](https://substrate.dev/docs/en/tutorials/substrate-front-end/part-3-transfer-funds#31-transfer-funds) of the front end tutorial. I so understand that updates the necessary parts of the components state, but I'm really struggling to understand the signature and how it is called.

The [complete function](https://github.com/substrate-developer-hub/substrate-front-end/blob/master/part-3-1/src/Transfer.js#L22-L29) is
```javascript
  const onChange = (_, data) => {
    setFormState(formState => {
      return {
        ...formState,
        [data.state]: data.value
      };
    });
  };
```

It appears to be taking two parameters, but only using the second. What are those two parameters? I found [some docs](https://semantic-ui.com/modules/dropdown.html#additional-settings) for the semantic-ui dropdown module which specifies the signature of `onChange` as `onChange(value, text, $choice)` but I can't see how those match up for these reasons:

1. The function written above takes two args not three.
2. `text` seems like a poor description for what the tutorial called `data`. `data` isn't even a string.
3. What is `$choice` about? Specifically what is the `$` about?
4. The tutorial also uses `onChange` with an [input element](https://semantic-ui.com/elements/input.html) but I don't see any docs at all for `onChange` in the context of an input element.

**Comment by Tbaut** [comment]
You're looking at the wrong documentation: https://react.semantic-ui.com/modules/dropdown/
 and https://react.semantic-ui.com/elements/input/

This should answer most of your questions. Although it doesn't fully apply here, some background:
In JS, if a function has 2 params in its signature, but you only want to use the second, you still need to mention a variable that will get the first unneeded param. The underscore is used here to mention that we actually don't take the first param into account. 

Just to answer your question about the other documentation `$choice` Semantic UI seems to call all the params that are DOM element with a `$`. Not sure it's a generally adopted convention, but that's how they do it.

**Comment by JoshOrndorff** [comment]
Thanks @Tbaut! That helps a ton
