### ISSUE TITLE
Final Touches: Proof Of Existence Tutorial

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#258]
- [ ] Gather Feedback from Users

- [ ] Add links to the tutorial from other docs

- [x] Possibly update the "test" section to a different name

- [x] Fix `...` with `--snip--`

- [ ] ~~Fix comments from `//` to `///` where possible~~ (breaks macros)

- [x] Add code comments to front-end

- [x] Update use of "forked" when referring to Git

- [x] Make code snippets copy-able.

**Comment by shawntabrizi** [comment]
Copyable code blocks: https://gist.github.com/yangshun/55db997ed0f8f4e6527571fc3bee4675

**Comment by shawntabrizi** [comment]
How can I turn `...` into `--snip--` while producing valid rust syntax which only takes one line?

**Comment by JoshOrndorff** [comment]
`/* --snip-- */`?

**Comment by shawntabrizi** [comment]
#263 solves the last item on the list

**Comment by shawntabrizi** [comment]
Updated last chapter to "Building a Custom Front End"
