### ISSUE TITLE
width > 100%

### ISSUE THREAD

**Issue by gnunicorn** [substrate-developer-hub/substrate-developer-hub.github.io#260]
For some reason some of our elements float out of the page width (even on very wide screens) on firefox. See the scroll-bar on the bottom. It is not visible what exactly is causing this, but it is present on all pages.

![image](https://user-images.githubusercontent.com/40496/65865925-47b0ee80-e374-11e9-9780-2a3f1442da98.png)

**Comment by shawntabrizi** [comment]
This has to be new. I have not seen this until now.

**Comment by JoshOrndorff** [comment]
I've also never seen it before and confirm it is on the live site now. I just went back through the history of the repo as far as e1043bebf2422 from almost two weeks ago and have the same error. It couldnt have been on the site that long without us noticing right?

**Comment by shawntabrizi** [comment]
It seems to be introduced with @kaichaosun's PR which introduced items to the footer:

```
<section class="row"><div class="copyright">Copyright © 2019 Parity Technologies</div><a class="item" href="https://www.parity.io/privacy/">Privacy Policy</a><a class="item" href="#" id="cookie-settings">Cookie Settings</a><script>
              var cookieSettings = document.getElementById('cookie-settings');
              cookieSettings.onclick = function() {
                return klaro.show();
              };
              </script></section>
```

This "row" item is the problem.

**Comment by kaichaosun** [comment]
Klaro consent pop up is out of the screen.

**Comment by kaichaosun** [comment]
It's caused with [this commit](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/commit/0562afdfd621f4c2ea047aef0f80f2be1788812e).

**Comment by shawntabrizi** [comment]
Also the original prompt is stuck at the bottom of the page:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/1860335/65972421-187ca900-e46a-11e9-8b82-339d6e27879b.png">

We should revert this commit if it is causing this many issues

**Comment by gnunicorn** [comment]
arguably, this is a different issue ...
