### ISSUE TITLE
Unable to load substrate.dev caused by clipboard.min.js in China

### ISSUE THREAD

**Issue by kaichaosun** [substrate-developer-hub/substrate-developer-hub.github.io#268]
![image](https://user-images.githubusercontent.com/10568673/65977494-9a89c380-e4a4-11e9-9713-a6a03a7fb2c4.png)

**Comment by shawntabrizi** [comment]
the whole site fails to load?

I can download the file and upload it directly, but I would want to understand better what you see on your screen.

**Comment by kaichaosun** [comment]
@shawntabrizi The site is loaded after fetching script is failed.
