### ISSUE TITLE
Resizing Window Hides Content

### ISSUE THREAD

**Issue by HCastano** [substrate-developer-hub/substrate-developer-hub.github.io#273]
I was resizing my browser from full screen to half screen and noticed that some pages don't handle the resizing correctly. I tried resizing [this page](https://substrate.dev/docs/en/getting-started/) on Firefox (v69.0.1) and Chrome (v77.0.3865.90), and all the content disappeared.

Full-size page:

![image](https://user-images.githubusercontent.com/12344623/66044301-833ceb80-e521-11e9-9425-f1c5658ee32d.png)

Smaller, resized page:
![image](https://user-images.githubusercontent.com/12344623/66044326-9059da80-e521-11e9-87dc-3bd1a0def182.png)

**Comment by shawntabrizi** [comment]
@gnunicorn lol

**Comment by shawntabrizi** [comment]
Semi fixed with https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/274

**Comment by gnunicorn** [comment]
`git bisect` told me this was introduced in `1ae4e4b9c09ba229edec82b9725a9eecc7044964` "temp fix for small screen (#274)"
