### ISSUE TITLE
Document transaction fees

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#284]
Details here:

https://github.com/paritytech/substrate/pull/3796

Need to figure out the right place to document this, probably transaction weight.

**Comment by JoshOrndorff** [comment]
But do allow free transactions from accounts with zero balance.

**Comment by JoshOrndorff** [comment]
Another relevant PR: https://github.com/paritytech/substrate/pull/3816 Where transaction fees are separated into another module.

Let's make this issue about documenting transaction fees in general and filling in https://substrate.dev/docs/en/next/development/module/weight which should be renamed from weight to fees.

**Comment by shawntabrizi** [comment]
Just make sure we don't miss addressing this specific point Gav wanted pointed out :)

**Comment by JoshOrndorff** [comment]
The specific point being:

> Runtime practitioners will need to conscious not to allow free transactions from arbitrary accounts that do not aware at least the ED, since each such transaction will result in storage leakage.

**Comment by JoshOrndorff** [comment]
@kianenigma We still need to capture this tip about free transactions from accounts that don't have existential deposit. I'm not totally clear what domain this applies to. Only when we're using the balances module to collect transaction fees?

**Comment by kianenigma** [comment]
done
