### ISSUE TITLE
Create logos/ logo theme for tutorials

### ISSUE THREAD

**Issue by Stefie** [substrate-developer-hub/substrate-developer-hub.github.io#304]
Taken from retreat pop-up meeting:

Create a theme / CI for the tutorial logos and create logos for the existing ones.
https://substrate.dev/en/tutorials

// cc Zsofia

**Comment by JoshOrndorff** [comment]
cc @meheszsofi

**Comment by JoshOrndorff** [comment]
Closing this because comms has done a lot with branding since the retreat. cc @thisisvilla for context.
