### ISSUE TITLE
node version in "Your First Substrate chain" tutorial

### ISSUE THREAD

**Issue by weichweich** [substrate-developer-hub/substrate-developer-hub.github.io#306]
I followed the [Creating Your First Substrate chain](https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain) and encountered some minor issues.

First it might help to mention that `yarn install` should be run before `yarn run dev`.

The second issue I had was that I got some errors when using the latest node version (v13.1.0).
In the README of the substrate-ui project it says that Node v11 and Python 2.7 are required. But the tutorial instructs to install the latest node version.

**Comment by JoshOrndorff** [comment]
@weichweich Thanks for reporting and using the tutorial. I've made a PR to fix the issues you reported.

I also wanted you to know that the doc you're referencing is about Substrate v1.0 which will be deprecated soon. You may enjoy trying this new tutorial for Substrate master. https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/
