### ISSUE TITLE
Rename to Palette and Pallet terms

### ISSUE THREAD

**Issue by kianenigma** [substrate-developer-hub/substrate-developer-hub.github.io#324]
- [x] Update Github Substrate Master Links

- [x] Update Reference Docs Links

- [ ] Update known direct replacements (SRML -> Frame, SRML Contracts module -> Contracts pallet, runtime module -> pallet)

- [ ] A final hand rename of in sentence terms

**Comment by shawntabrizi** [comment]
Step 1 addressed with: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/338

**Comment by shawntabrizi** [comment]
Step 2 addressed with: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/340

**Comment by JoshOrndorff** [comment]
Some thoughts about docs/conceptual/runtime/srml.md for step 4, copied from https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/344#discussion_r356963924

* Rename the entire file
* Rename all the headers eg System Module -> System Pallet
* rename srml -> ?? (brought this up on riot chat)

And @joepetrowski's suggestion for the former SRML article intro
```
---
title: FRAME (whatever the acronym is)
---
FRAME is a set of modules (called _pallets_) and support libraries that simplify runtime development. Pallets are individual modules within FRAME that host domain-specific logic.

FRAME provides some helper modules to interact with Substrate Primitives, namely Executive, Metadata, Support, System, and Utility. Any module that uses these `frame-*` helper modules is a pallet. Parity develops and maintains
a set of these, but they can come from the community as well.

If you don't want to use the FRAME helpers, you can still write your own interfaces to interact with the Substrate client and implement your custom runtime.
```
