### ISSUE TITLE
Metadata in SRML

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#34]
Metadata in the SRML is the final layer between the blockchain node and the underlying JavaScript APIs allowing you to call into the Runtime.

Users who want to learn more about the SRML will probably want answers to the following:

* How is the metadata generated?
* What is the general structure of the metadata, and what information can I find in it?
* How can I fetch the metadata via a raw RPC call (metadata endpoint)? (or something low level)
* How is the result of the metadata endpoint encoded, and how do I decode it?
* Can I add additional information to the metadata using Substrate?
* (Edit to add other questions we should answer)

These questions should be indirectly answered via two forms of documentation:

* Reference documentation for the `srml-metadata` crate in the `srml` folder of Substrate.
    * These are low level docs for the crate. First check if they exist already. If they do not, you should try your best to write the docs **if** you understand the code, otherwise, leave it to the developers who wrote the code and ping them that we need to update the docs.

* Substrate Developer Hub Docs
    * This doc should wrap together the various docs around Substrate types, which all point to generating some information for the metadata.
    * This doc should also update the architecture of a runtime doc to add a layer between `construct_runtime` and the JavaScript APIs.

**Comment by nczhu** [comment]
Draft in progress: https://hackmd.io/3c-y_oAGTDOwMvm7fFZciA
