### ISSUE TITLE
Substrate Deployment URL not available (404)

### ISSUE THREAD

**Issue by SelvarajDhaamodaran** [substrate-developer-hub/substrate-developer-hub.github.io#364]
https://substrate.dev/docs/en/overview/tutorials/start-a-private-network-with-substrate.md not available

**Comment by JoshOrndorff** [comment]
This is probably the link you're looking for https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/

I'll close this issue, but please do let us know where you found these broken links in #365 so we can fix them.

**Comment by SelvarajDhaamodaran** [comment]
the link is available in the following URL
https://substrate.dev/docs/en/overview/

Under the USAGE section

**Comment by JoshOrndorff** [comment]
Forgot to close earlier. Thanks for following up. Will report back in #365

**Comment by SelvarajDhaamodaran** [comment]
Hi,
                I can see a good documentation on the substrate explanation. Similarly, could you please provide a documentation for setting up the relaychain and parachain setup with examples?


Thanks,
Selvaraj Dhaamodaran

**Comment by JoshOrndorff** [comment]
@SelvarajDhaamodaran Starting your own relay chain is nearly identical to the [Start a private network tutorial](https://substrate.dev/docs/en/next/tutorials/start-a-private-network/) that you originally asked about. The main difference is that you'll use the [Polkadot repository](https://substrate.dev/docs/en/next/tutorials/start-a-private-network/) rather than the node template as that tutorial instructs.

Launching parachains is not yet well-trodden enough to have the same level of docs, but it is possible with some work. Right now your best source is the [Cumulus Workshop](https://joshorndorff.github.io/cumulus-workshop/#/). There is also a [recording of walking through](https://www.youtube.com/watch?v=cL6UFeoiMVw&list=PLsBc7YjizKUwc3AcNb9oNZvtsN0QmAJPP&index=3&t=32m38s) some of that material while I was preparing it.

If you do dig in on launching parachains, feel free to ask for more help. Rather than continuing this issue, though, please open issues against my cumulus workshop or other relevant repos or reach out on riot. Good luck!

**Comment by SelvarajDhaamodaran** [comment]
Hi Joshy,
                Thanks for the information.
We are primarily focusing on the exploring on the polkadot interoperability and how to bridge with the external blockchain network like ethereum. If you have any documentation on the setting up the bridge network that will also help us.
I will work on the Cumulus Workshop url you have  given and let you know if I have any questions.

Thanks,
Selvaraj Dhaamodaran

**Comment by SelvarajDhaamodaran** [comment]
Hi,
                I am trying to setup the polkadot environment using the Cumulus Workshop<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjoshorndorff.github.io%2Fcumulus-workshop%2F%23%2F&data=02%7C01%7Cselvaraj.dhaamodaran%40cognizant.com%7C3865ec26c2034938e98f08d78fb3558a%7Cde08c40719b9427d9fe8edf254300ca7%7C0%7C0%7C637135872718818748&sdata=TWvzkof07ZvQPdJ73ViXOJGYqtsDVFE0UTvQrzemn3A%3D&reserved=0> url you have sent.
I downloaded the polkadot code from the git clone -b bkchr-cumulus-branch https://github.com/paritytech/polkadot.git

When I start the polkadot using the following command

./target/release/polkadot –dev

I am getting the following message, it is not creating block, always the block count is 0. Need your help in understand where I am going wrong.


2020-01-09 07:58:47 Idle (0 peers), best: #0 (0x8681…d81f), finalized #0 (0x8681…d81f), ⬇ 0 ⬆ 0
2020-01-09 07:58:48 Unable to author block in slot 263092788,. `can_author_with` returned: `spec_name` does not match `kusama` vs `polkadot` Probably a node update is required!
2020-01-09 07:58:52 Idle (0 peers), best: #0 (0x8681…d81f), finalized #0 (0x8681…d81f), ⬇ 0 ⬆ 0
2020-01-09 07:58:54 Unable to author block in slot 263092789,. `can_author_with` returned: `spec_name` does not match `kusama` vs `polkadot` Probably a node update is required!
2020-01-09 07:58:57 Idle (0 peers), best: #0 (0x8681…d81f), finalized #0 (0x8681…d81f), ⬇ 0 ⬆ 0
2020-01-09 07:59:00 Unable to author block in slot 263092790,. `can_author_with` returned: `spec_name` does not match `kusama` vs `polkadot` Probably a node update is required!



Thanks,
Selvaraj Dhaamodaran

From: Dhaamodaran, Selvaraj (Cognizant)
Sent: Wednesday, January 8, 2020 11:35 AM
To: substrate-developer-hub/substrate-developer-hub.github.io <reply@reply.github.com>; substrate-developer-hub/substrate-developer-hub.github.io <substrate-developer-hub.github.io@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [substrate-developer-hub/substrate-developer-hub.github.io] Substrate Deployment URL not available (404) (#364)

Hi Joshy,
                Thanks for the information.
We are primarily focusing on the exploring on the polkadot interoperability and how to bridge with the external blockchain network like ethereum. If you have any documentation on the setting up the bridge network that will also help us.
I will work on the Cumulus Workshop url you have  given and let you know if I have any questions.

Thanks,
Selvaraj Dhaamodaran

**Comment by SelvarajDhaamodaran** [comment]
Hi Joshy,

                I am getting the error message when I tried to start the parachain. Not sure where I am going,  could you please help me in resolving the error message?

Error: Input("Input(\"Client(Backend(\\\"IO error: lock : cumulus_collator_path/chains/parachain_local_testnet/db/LOCK: No locks available\\\"))\")")

I have used the following url to start the parachain.
https://github.com/paritytech/cumulus/tree/bkchr-test-parachain


Step1: As per the documentation first started the alice node using the following command:
cargo run --release -- --chain=local --base-path=cumulus_relay_chain_node_0 --alice --ws-port 8081



Step 2: started the bob node using the following command:
cargo run --release -- --chain=local --base-path=cumulus_relay_chain_node_1 --bob --port 50666



                The first 2 step ran successfully, (i.e.) the relay chain started successfully and got clustered

                Step 3: When I tried to start the collator node, I am getting error message.
Node Identity of the Alice node = QmP7vcGgjprVCBnA14LXLMA5fjz7nUYGzGpU6EVSwLr13C
cargo run --release -p cumulus-test-parachain-collator -- -d cumulus_collator_path --chain polkadot_chainspec.json --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmP7vcGgjprVCBnA14LXLMA5fjz7nUYGzGpU6EVSwLr13C --ws-port 8085


ERROR LOG:
cargo run --release -p cumulus-test-parachain-collator -- -d cumulus_collator_path --chain polkadot_chainspec.json --bootnodes /ip4/13.59.135.174/tcp/30333/p2p/QmP7vcGgjprVCBnA14LXLMA5fjz7nUYGzGpU6EVSwLr13C
    Finished release [optimized] target(s) in 0.42s
     Running `target/release/cumulus-test-parachain-collator -d cumulus_collator_path --chain polkadot_chainspec.json --bootnodes /ip4/13.59.135.174/tcp/30333/p2p/QmP7vcGgjprVCBnA14LXLMA5fjz7nUYGzGpU6EVSwLr13C`
2020-01-20 10:14:46 Cumulus Test Parachain Collator
2020-01-20 10:14:46   version 0.1.0-74cb796-x86_64-linux-gnu
2020-01-20 10:14:46   by Parity Technologies <admin@parity.io>, 2019
2020-01-20 10:14:46 Chain specification: Local Testnet
2020-01-20 10:14:46 Node name: vagabond-pets-8271
2020-01-20 10:14:46 Roles: FULL
2020-01-20 10:14:46 Parachain id: Id(100)
2020-01-20 10:14:46 Highest known block at #0
2020-01-20 10:14:46 Using default protocol ID "sup" because none is configured in the chain specs
2020-01-20 10:14:46 Local node identity is: QmZ6GAdsVbxfS5fgj5AuAKWjHBhAegL4u99emCWBdbzKMU
2020-01-20 10:14:46 Not registering Substrate logger, as there is already a global logger registered!
2020-01-20 10:14:47 Cumulus Test Parachain Collator
2020-01-20 10:14:47   version 0.1.0-74cb796-x86_64-linux-gnu
2020-01-20 10:14:47   by Parity Technologies <admin@parity.io>, 2017-2019
2020-01-20 10:14:47 Chain specification: Local Testnet
2020-01-20 10:14:47 Node name: cowardly-celery-5746
2020-01-20 10:14:47 Roles: FULL
Error: Input("Input(\"Client(Backend(\\\"IO error: lock : cumulus_collator_path/chains/parachain_local_testnet/db/LOCK: No locks available\\\"))\")")


Thanks,
Selvaraj Dhaamodaran


From: Dhaamodaran, Selvaraj (Cognizant)
Sent: Thursday, January 9, 2020 1:34 PM
To: substrate-developer-hub/substrate-developer-hub.github.io <reply@reply.github.com>; substrate-developer-hub/substrate-developer-hub.github.io <substrate-developer-hub.github.io@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [substrate-developer-hub/substrate-developer-hub.github.io] Substrate Deployment URL not available (404) (#364)

Hi,
                I am trying to setup the polkadot environment using the Cumulus Workshop<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjoshorndorff.github.io%2Fcumulus-workshop%2F%23%2F&data=02%7C01%7Cselvaraj.dhaamodaran%40cognizant.com%7C3865ec26c2034938e98f08d78fb3558a%7Cde08c40719b9427d9fe8edf254300ca7%7C0%7C0%7C637135872718818748&sdata=TWvzkof07ZvQPdJ73ViXOJGYqtsDVFE0UTvQrzemn3A%3D&reserved=0> url you have sent.
I downloaded the polkadot code from the git clone -b bkchr-cumulus-branch https://github.com/paritytech/polkadot.git

When I start the polkadot using the following command

./target/release/polkadot –dev

I am getting the following message, it is not creating block, always the block count is 0. Need your help in understand where I am going wrong.


2020-01-09 07:58:47 Idle (0 peers), best: #0 (0x8681…d81f), finalized #0 (0x8681…d81f), ⬇ 0 ⬆ 0
2020-01-09 07:58:48 Unable to author block in slot 263092788,. `can_author_with` returned: `spec_name` does not match `kusama` vs `polkadot` Probably a node update is required!
2020-01-09 07:58:52 Idle (0 peers), best: #0 (0x8681…d81f), finalized #0 (0x8681…d81f), ⬇ 0 ⬆ 0
2020-01-09 07:58:54 Unable to author block in slot 263092789,. `can_author_with` returned: `spec_name` does not match `kusama` vs `polkadot` Probably a node update is required!
2020-01-09 07:58:57 Idle (0 peers), best: #0 (0x8681…d81f), finalized #0 (0x8681…d81f), ⬇ 0 ⬆ 0
2020-01-09 07:59:00 Unable to author block in slot 263092790,. `can_author_with` returned: `spec_name` does not match `kusama` vs `polkadot` Probably a node update is required!



Thanks,
Selvaraj Dhaamodaran

From: Dhaamodaran, Selvaraj (Cognizant)
Sent: Wednesday, January 8, 2020 11:35 AM
To: substrate-developer-hub/substrate-developer-hub.github.io <reply@reply.github.com<mailto:reply@reply.github.com>>; substrate-developer-hub/substrate-developer-hub.github.io <substrate-developer-hub.github.io@noreply.github.com<mailto:substrate-developer-hub.github.io@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [substrate-developer-hub/substrate-developer-hub.github.io] Substrate Deployment URL not available (404) (#364)

Hi Joshy,
                Thanks for the information.
We are primarily focusing on the exploring on the polkadot interoperability and how to bridge with the external blockchain network like ethereum. If you have any documentation on the setting up the bridge network that will also help us.
I will work on the Cumulus Workshop url you have  given and let you know if I have any questions.

Thanks,
Selvaraj Dhaamodaran

**Comment by SelvarajDhaamodaran** [comment]
+ Chayan

**Comment by JoshOrndorff** [comment]
This is not the right place to post for help with cumulus. Please open an issue on the [cumulus workshop](https://github.com/joshorndorff/cumulus-workshop) if you're following that, or on the [cumulus repo](https://github.com/paritytech/cumulus/) itself if you suspect a bug in the cumulus code.
