### ISSUE TITLE
Creating Your First Substrate URL not found (404)

### ISSUE THREAD

**Issue by SelvarajDhaamodaran** [substrate-developer-hub/substrate-developer-hub.github.io#365]
https://substrate.dev/docs/en/overview/tutorials/creating-your-first-substrate-chain.md

**Comment by kaichaosun** [comment]
Hi @SelvarajDhaamodaran where do you find this broken link? I believe this tutorial already linked to the next branch and it's accessible from the tutorial page. https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/

**Comment by SelvarajDhaamodaran** [comment]
> Hi @SelvarajDhaamodaran where do you find this broken link? I believe this tutorial already linked to the next branch and it's accessible from the tutorial page. https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/

the link is available in the following URL 
https://substrate.dev/docs/en/overview/

Under the USAGE section

**Comment by SelvarajDhaamodaran** [comment]
the link is available in the following URL
https://substrate.dev/docs/en/overview/

Under the USAGE section
