### ISSUE TITLE
Broken link on Overview page

### ISSUE THREAD

**Issue by bertstachios** [substrate-developer-hub/substrate-developer-hub.github.io#372]
Broken link to tutorial *Start a Private Network with Substrate* at https://substrate.dev/docs/en/next/ 

![image](https://user-images.githubusercontent.com/43627527/71044229-3adab480-2185-11ea-9283-71af873b0cc0.png)

**Comment by riusricardo** [comment]
It should be: https://substrate.dev/docs/en/next/tutorials/start-a-private-network/
Instead of: https://substrate.dev/docs/en/next/tutorials/start-a-private-network-with-substrate.md
The same page needs fixes to replace SRML to FRAME.

**Comment by kaichaosun** [comment]
I notice there are a lot of places still using SRML under docs. will open another issue for all the renaming.

**Comment by riusricardo** [comment]
We need to do a  review of all the Docs to replace SRML to FRAME and any related reference. This is a logged [task](https://github.com/paritytech/devex-planning/issues/22) to update DevHub but we need someone else to take it.

**Comment by kaichaosun** [comment]
I'm working on it.

**Comment by kaichaosun** [comment]
Thanks @bertstachios
