### ISSUE TITLE
Consensus diagrams are ugly

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#401]
The [consensus article](https://substrate.dev/docs/en/next/conceptual/core/consensus) contains diagrams that are helpful in terms of content, but ugly in terms of design. They should be replaced by an actual designer.

**Comment by goldsteinsveta** [comment]
Something like this?
![longest chain](https://i.imgur.com/kGXpdrW.png)
![GHOST](https://i.imgur.com/y5Mk5TF.png)

**Comment by JoshOrndorff** [comment]
Yes! Those are awesome! We can remove the title from the image since it is already in the surrounding page. I can do that myself unless you'd rather do it. May I go ahead and include these images?

**Comment by JoshOrndorff** [comment]
Well I guess you put them here so I could use them, so I will. Thanks again :)
