### ISSUE TITLE
Check links to crates.parity.io

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#411]
Some links to crates.parity.io are pointing to 404.  

Btw, what is the context of having https://crates.parity.io and https://substrate.dev/rustdocs/master ? Are we migrating one over to another? @shawntabrizi  @folsen

**Comment by shawntabrizi** [comment]
You should use `https://substrate.dev/rustdocs/...` for all Rust docs in the Substrate Developer Hub.

We provide versioning:

* https://substrate.dev/rustdocs/master
* https://substrate.dev/rustdocs/v1.0
* https://substrate.dev/rustdocs/v2.0 (soon)

And it provides telemetry + analytics that we have set up.
