### ISSUE TITLE
"Creating an external pallet" tutorial is broken

### ISSUE THREAD

**Issue by domob1812** [substrate-developer-hub/substrate-developer-hub.github.io#416]
The [tutorial for creating a pallet as external crate](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/tutorials/creating-a-runtime-module.md) is broken for me.  (I just tried to walk through it, without having too much prior exposure to Substrate.)  "Broken" here means that I followed all instructions closely, but building the node runtime fails after including my external pallet.

I *think* the first issue is that the tutorial instructs me to clone [substrate-module-template](https://github.com/substrate-developer-hub/substrate-module-template), which seems outdated (and in fact the commit ids of core substrate dependencies mismatch between this repository and the node-template).  I then tried to use [substrate-pallet-template](https://github.com/substrate-developer-hub/substrate-pallet-template) instead, which fixed most issues.

However, I still get the following error when I try to implement my pallet's trait from `Runtime` (before even adding it to the runtime construction):

       Compiling node-template-runtime v2.0.0 (/home/daniel/ExternalPallet/node/runtime)
    error: failed to run custom build command for `node-template-runtime v2.0.0 (/home/daniel/ExternalPallet/node/runtime)`
    
    Caused by:
      process didn't exit successfully: `/home/daniel/ExternalPallet/node/target/release/build/node-template-runtime-8751aec9b8ea6d01/build-script-build` (exit code: 1)
    --- stdout
    Executing build command: "rustup" "run" "nightly" "cargo" "build" "--target=wasm32-unknown-unknown" "--manifest-path=/home/daniel/ExternalPallet/node/target/release/wbuild/node-template-runtime/Cargo.toml" "--release"
    
    --- stderr
       Compiling wasm-build-runner-impl v1.0.0 (/home/daniel/ExternalPallet/node/target/release/wbuild-runner/node-template-runtime)
        Finished release [optimized] target(s) in 0.29s
         Running `/home/daniel/ExternalPallet/node/target/release/wbuild-runner/node-template-runtime/target/release/wasm-build-runner-impl`
       Compiling node-template-runtime v2.0.0 (/home/daniel/ExternalPallet/node/runtime)
    error[E0277]: the trait bound `Event: core::convert::From<test_pallet2::RawEvent<sp_api_hidden_includes_construct_runtime::hidden_include::sp_runtime::AccountId32>>` is not satisfied
       --> /home/daniel/ExternalPallet/node/runtime/src/lib.rs:244:3
        |
    243 | impl test_pallet2::Trait for Runtime {
        | ------------------------------------ in this `impl` item
    244 |   type Event = Event;
        |   ^^^^^^^^^^^^^^^^^^^ the trait `core::convert::From<test_pallet2::RawEvent<sp_api_hidden_includes_construct_runtime::hidden_include::sp_runtime::AccountId32>>` is not implemented for `Event`
        |
        = help: the following implementations were found:
                  <Event as core::convert::From<frame_system::Event>>
                  <Event as core::convert::From<pallet_balances::RawEvent<sp_api_hidden_includes_construct_runtime::hidden_include::sp_runtime::AccountId32, u128, pallet_balances::DefaultInstance>>>
                  <Event as core::convert::From<pallet_grandpa::Event>>
                  <Event as core::convert::From<pallet_indices::RawEvent<sp_api_hidden_includes_construct_runtime::hidden_include::sp_runtime::AccountId32, u32>>>
                and 2 others
    
    error: aborting due to previous error
    
    For more information about this error, try `rustc --explain E0277`.
    error: could not compile `node-template-runtime`.
    
    To learn more, run the command again with --verbose.

Likely it is me doing something stupid, but the tutorial should be fixed to lead me onto the right path (and I guess at least link to the correct repository).

I'm happy to provide a PR, but for that I'd need some more guidance on whether my understanding is actually correct and what I need to do to fix the compiler error.

**Comment by riusricardo** [comment]
Thanks for the catch. This tutorial is going to be fixed in the next days.
You can take a look at https://github.com/riusricardo/substrate-pallet-template/tree/ricardo-node-pallet to get a better idea of where it is headed.
It is correct to use the pallet-template.

**Comment by JoshOrndorff** [comment]
Indeed, it should be that pallet template. PR #417 that fixes that in the tutorial. Thanks for catching it.

The error you posted probably is a mistake on your part, but I can't figure out what it would be from the message alone. If the code @riusricardo posted doesn't help you find your error, please post a link to your complete code, and I'll try to compile it myself. Most likely I can find the mistake.

**Comment by domob1812** [comment]
Thanks for the feedback!  I'll try out @riusricardo's code and let you know if it helps.

**Comment by domob1812** [comment]
I've now looked at my code again in detail, and got it to work.  I still had some "bad" changes in it from trying to work around the outdated module repository previously.  It now all works.

I'll leave this issue open so you can decide when to close it (e.g. after #417 is in).  Thanks for the fast response and help!

**Comment by JoshOrndorff** [comment]
You're welcome. Let us know if you need more help with Substrate :)
