### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by goldsteinsveta** [substrate-developer-hub/substrate-developer-hub.github.io#424]
I wish there were directions to docker compose file and image on the Devhub i.g. for quick checks or for those who build on the top of a node: smart contracts or front ends

**Comment by JoshOrndorff** [comment]
I learned this in devops riot channel the other day

David:
> FYI every merge to master and every tagged release will create a binary that's put in s3 and a docker image ... 
e.g. see pipeline: https://gitlab.parity.io/parity/substrate/pipelines/74606

Me:
> That sounds useful, but I'm not sure what I'm looking at (on the linked page). Can I download the binary to run locally?

David:
> So under the publish section there's publish-s3-release and publish-docker-substrate
They link to the file: https://releases.parity.io/substrate/x86_64-debian:stretch/2.0.0-8cb71bd/substrate/substrate and the docker image parity/substrate:2.0.0-8cb71bd

**Comment by goldsteinsveta** [comment]
Ok, that's super nice to know actually...but what I'd like to find when typing "docker" in the search field is ~this one here: https://github.com/paritytech/srml-contracts-waterfall/blob/master/docker-compose.yml

I think it would be super cool to have it in the Getting Started or in Ecosystem Tools. I guess I can write a small paragraph myself though?

**Comment by JoshOrndorff** [comment]
Closing because this is not totally actionable. Would the docker image be just for running a node or for developing on it. If just running, then which node would it run. Feel free to re-open in the new [cms repo](https://github.com/substrate-developer-hub/substrate-cms).
