### ISSUE TITLE
Integrate Substrate playground into our tutorials

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#425]
- I (Jimmy) will try to integrate playground in off-chain worker tutorial and see how hard this process is

**Comment by JoshOrndorff** [comment]
cc @jeluard

**Comment by jeluard** [comment]
Can you (Jimmy) detail what you have in mind?

**Comment by JoshOrndorff** [comment]
Dupe of 426, now moved to https://github.com/paritytech/substrate.io/issues/1
