### ISSUE TITLE
Integrate coding-heavy tutorials with Substrate Playground

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#426]
# Current Situation

Currently devhub's tutorials are hosted in two different ways.

### With the Main Devhub
For example, the [Private Network Tutorial](https://substrate.dev/docs/en/next/tutorials/start-a-private-network)
Pros:
* Theme matches the rest of devhub
* Fewer repos to track issues on

Cons:
* Harder to show code in complete context.
* Learners need their own dev environment to actually _run_ the code.

### In their own docsify-based repository
For example, the [ink! tutorial](https://substrate-developer-hub.github.io/substrate-contracts-workshop/)
Pros:
* Code with context is always visible

Cons:
* Theme does not match the rest of devhub
* Learners need their own dev environment to actually _run_ the code.

# Proposal

It would be strictly better to have code-heavy tutorials (such as ink tutorial, and any runtime-writing tutorial) integrate with the existing [Substrate Playground](https://playground.substrate.dev/). This retains all the Pros of the docsify-based approach, and it also adds these advantages:
* Learners can actually use and run the code right away.
* Devhub team doesn't need to worry about theming the tutorial, only writing the content.

cc @jeluard

**Comment by JoshOrndorff** [comment]
@jimmychu0807 has proposed to try this first with hi upcoming offchain workers tutorial https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/425

**Comment by jeluard** [comment]
@JoshOrndorff Definitely! Do you have some specific ideas how it would be integrated? 
What would it look like in your mind?

**Comment by JoshOrndorff** [comment]
What it would physically _look_ :eyes: like is very open to interpretation.

We like the fact that learners can read the tutorial text and work on code side by side in the ink! tutorial https://substrate.dev/substrate-contracts-workshop/#/

One off-the-cuff idea would be to have a markdown viewer integrated into the editor so learners could read through the tutorial as rendered markdown while using playground. It would be nice if the tutorial file were read-only or at least gave a warning on changes, so learners didn't accidentally change/delete the tutorial writeup itself.

**Comment by jeluard** [comment]
That could be easily done via a VSCode/theia plugin that would allow navigation alongside the code editor.

The main thing we should define is some standard way of defining:
- how to move from what step to another
- how each step is documented
- how to access before/after code skeleton

An easy way to implement that could be to rely on well known git tags (e.g. `step/1`, `step/1-finished`) and rely on the `README.md` for instructions.

**Comment by JoshOrndorff** [comment]
moved to https://github.com/paritytech/substrate.io/issues/1
