### ISSUE TITLE
broken link in private network tutorial

### ISSUE THREAD

**Issue by coriolinus** [substrate-developer-hub/substrate-developer-hub.github.io#440]
At the end of https://substrate.dev/docs/en/tutorials/start-a-private-network/customchain, the word "executor" is a link to https://substrate.dev/docs/en/tutorials/start-a-private-network/docs/conceptual/core/executor. That latter link is a 404.

**Comment by riusricardo** [comment]
Fixed in #438

**Comment by coriolinus** [comment]
@riusricardo @JoshOrndorff looks like you two added conflicting commits within minutes of each other fixing this issue. Thank you both! I have no idea which should take precedence.

**Comment by riusricardo** [comment]
Fixed on #438
