### ISSUE TITLE
Improve "Getting Started" Structure

### ISSUE THREAD

**Issue by apopiak** [substrate-developer-hub/substrate-developer-hub.github.io#442]
The [getting started page](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/overview/getting-started.md) was somewhat confusing while I was starting out. It was not quite clear which steps I need to take to set up substrate.

My idea would be to split the process into different paths and make each of those straight forward (as in, you just follow it step by step without having to jump or branch except for OS selection):
+ fastest way to get started (with the install script and `--fast`)
+ manual installation
+ substrate development installation

Fast Structure:
1. run script
2. use polkadot.js frontend

Manual Structure:
1. prequisites
2. set up Rust
3. set up substrate node template
4. set up frontend

Substrate Development Structure:
1. prerequisites
2. set up Rust
3. install substrate
4. install subkey

**Comment by JoshOrndorff** [comment]
I'm closing it because it has been discussed in many places and partially addressed in the [new cms repo](https://github.com/substrate-developer-hub/substrate-cms).

If further refinements are desired the best course of action is to open a new issue against that repo.
