### ISSUE TITLE
Improve UX when navigating between docusaurus, rustdocs, recipes, kitties, etc

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#45]
* What will it feel like to have a user jump to a different page to see documentation that we are keeping with the source code
* Are there things we can do to minimize confusion and maximize discoverability
* Is there some format we need to follow with our direct links so that redirects do not break and do not become stale with updates

**Comment by shawntabrizi** [comment]
As long as the rustdoc project generates the static html within a repo in this organization, we can access the rustdoc at: `substrate.dev/<project_name>`

I think the next hack may be some JS injected nav bar or some pop up on the right corner which takes the user back to the Dev Hub, hopefully making it feel more like a single experience

**Comment by shawntabrizi** [comment]
The first major step of this is done with the [`rustdocs`](https://github.com/substrate-developer-hub/rustdocs) repository.

Next to figure out custom HTML/CSS/JS to inject a common navbar or similar to the site

**Comment by JoshOrndorff** [comment]
> Next to figure out custom HTML/CSS/JS to inject a common navbar or similar to the site

@shawntabrizi You're talking about injecting a navbar  that looks like 
![image](https://user-images.githubusercontent.com/2915325/60189998-e7079800-97ff-11e9-9e0a-100f749475ff.png)
into https://substrate.dev/rustdocs/v1.0 right?

**Comment by JoshOrndorff** [comment]
This might be relevant:
https://doc.rust-lang.org/1.30.0/book/first-edition/documentation.html#generation-options

> `--html-before-content FILE`: includes the contents of FILE directly after <body>, before the rendered content (including the search bar).

That has to be done when the docs are generated. I see https://github.com/paritytech/substrate/commit/047e887d1191aa0b85f46570a432c5665bfc1b02 but can't seem to figure out where the `cargo doc` actually gets run. I'll play with this locally and see whether it seems promising.

**Comment by JoshOrndorff** [comment]
I played with that flag a bit, and it's only okay. I'm not sure how to use that flag with `cargo doc` only with `rustdoc`.

![image](https://user-images.githubusercontent.com/2915325/60193583-eeca3b00-9805-11e9-8c0e-3e3fa01918d4.png)

Here's a playground repo if you want to quickly reproduce my results https://github.com/JoshOrndorff/rustdoc-playground

**Comment by shawntabrizi** [comment]
I spent a little time looking at this a week ago or so.

Made a repo here: https://github.com/substrate-developer-hub/substrate-developer-hub-navbar

And did a little investigating here: https://stackoverflow.com/questions/56658987/create-a-navbar-which-can-be-added-embedded-to-any-site/56659006#56659006

Happy for you to pick up or I will take another stab maybe this weekend.

**Comment by JoshOrndorff** [comment]
I'm pretty happy with what you have started there @shawntabrizi We could add the algolia search bar to it like https://community.algolia.com/docsearch/dropdown.html

There is also a `--html-in header` that we could use to get your script tag into the rustdocs.

**Comment by kaichaosun** [comment]
IMO the principle should be making the Docs, rustdoc, tutorial, receipts **as isolated as possible**.
Proposals that could potentially improve UX:
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/166#issuecomment-512408811

**Comment by shawntabrizi** [comment]
@kaichaosun Let's keep this item scoped to adding a shared navbar across all the sites.

We want the user to navigate to all parts of the developer hub from every other part.

Take a look at my project for injecting a navbar and see if you can make it work consistently across the different resources.

**Comment by kaichaosun** [comment]
The different resources serve for different purposes, there is no need to share the navbar of substrate developer hub with other resources IMO.
Substrate developer hub is meant to be at the central place of different resources. Have a link to the homepage of dev hub within other resources makes sense to me. What do you think? @shawntabrizi

**Comment by kaichaosun** [comment]
Like @JoshOrndorff said, link dev hub in rustdoc is a bit tricky, we need to modify the scripts that generates docs and include another html, which is not clean in Substrate codebase. Leave this piece of work until we have other requirements.
