### ISSUE TITLE
Broken Link on Cryptography Overview

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#457]
The link to the Polkadot claims module that is used to verify Ethereum signatures is broken on the cryptography overview page. Despite the fact that the link in the raw markdown seems correct (https://github.com/paritytech/polkadot/blob/master/runtime/common/src/claims.rs) it does not resolve to the correct location (https://github.com/paritytech/polkadot/blob/master/runtime/src/claims.rs).

```
Expected: https://github.com/paritytech/polkadot/blob/master/runtime/common/src/claims.rs
Actual:   https://github.com/paritytech/polkadot/blob/master/runtime/src/claims.rs
```

**Comment by JoshOrndorff** [comment]
It seems you've already observed that the link with the `/common` is the correct one.

I wonder if the confusing part is that our docs are versioned. It seems the `next` version ([published](https://substrate.dev/docs/en/next/conceptual/cryptography/), [source](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/conceptual/cryptography/index.md)) was updated in [this PR](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/434). But the `pre-v2.0-3e65111` version ([published](https://substrate.dev/docs/en/conceptual/cryptography/), [source](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/website/versioned_docs/version-pre-v2.0-3e65111/conceptual/cryptography/index.md)) was never updated.

@danforbes  If you would like to tackle this in your already-started PR on fixing links please assign yourself. If no, that's totally fine too, and please assign me.

**Comment by danforbes** [comment]
Ah...now I get it! will certainly handle this in #456 :+1:
