### ISSUE TITLE
Update tutorial on visualizing node metrics

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#458]
The grafana endpoint is being removed from Substrate in https://github.com/paritytech/substrate/pull/4511 which means the [tutorial for using grafana](https://substrate.dev/docs/en/next/tutorials/visualizing-node-metrics/) will need to be updated.

This update should _not_ be made on `pre-v2.0-3e65111` version

**Comment by dlguddus** [comment]
We are B-Harvest working on this : https://github.com/paritytech/substrate/pull/4511 which allows substrate built in prometheus. Our second milestone is to provide easy setup grafana connected to this prometheus exporter. I expect the linked tutorial can be updated based on our tutorial which will be provided in less than 4 weeks we expect.

We will drop additional comment here when our tutorial is ready. Thank you for raising the issue.

**Comment by JoshOrndorff** [comment]
The update has begun in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/461 You're welcome to conribute there if you like @dlguddus

**Comment by nodebreaker0-0** [comment]
https://github.com/nodebreaker0-0/substrate/blob/prometheus_v0.4.0/utils/prometheus/README.md

It was written earlier, but it might be helpful for this tutorial.
In the future, we will support the entire dashboard (Mileston 2).
Setting up Prometheus is very easy, but the above address will help.

I think there should be a grafana tutorial and a prometheus tutorial at the same time.

**Comment by JoshOrndorff** [comment]
Done in #461 and #488
