### ISSUE TITLE
Substrate VSCode/Sublime snippets plugin

### ISSUE THREAD

**Issue by kianenigma** [substrate-developer-hub/substrate-developer-hub.github.io#47]
With the current rush on docs this is no priority but something that has been on my mind for a while: 

- Assuming that VSCode is the editor of choice for most rust devs: 
- VSCode + RLS has relatively good support for rust projects with auto-imports, Intellisense, and inline error report. If the project is huge it takes a while to compile under the hood and get the errors but no complaints here.
- All of this breaks the minute you start working on any sort of SRML/macro-generated code. All that you get is the fuzzy auto-completion that just comes from inspecting the file and _guessing_. 
- The least we can do here is to create a snippet plugin for edits to make some of the SRML syntax which is eccentric auto-generated. 
- Ideally, the rest of the features (intellisense, auto-import, peek definition, peek function signature etc.) might also be fixable. 
- I assume since the scope here is SRML-specific syntax (macro magic as @shawntabrizi calls it), RLS or any rust related tool will *never* help.

**Comment by shawntabrizi** [comment]
Related to https://github.com/substrate-developer-hub/hacktoberfest/issues/9

Closing because not docs
