### ISSUE TITLE
v2 tutorials?

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-developer-hub.github.io#473]
Hello!  
Thanks for your great material and tutorials.

Now that v1 seems [EOL](https://github.com/polkadot-js/apps/issues/2205#issuecomment-579227198), and I heard about the "feature freeze" of the v2 version ... where can I find a list of all those **tutorials & manuals that target v2** ? 

E.g. this excellent workshop is still based on `-b v1.0` https://substrate.dev/docs/en/tutorials/start-a-private-network-with-substrate#your-first-time 

Secondly, for very basic experiments, would you recommend to I use this "[Current Stable Version](https://substrate.dev/en/versions)" Jan 6 [pre-v2.0-3e65111](https://github.com/paritytech/substrate/tree/3e651110aa06aa835790df63410a29676243fc54)  ?

Thank you very much!

**Comment by drandreaskrueger** [comment]
P.S.: How about a flag on the top of every page of every manual - which signals for which version that page is suitable? Perhaps even until which future version it might be useful, i.e. "expiration date".

**Comment by JoshOrndorff** [comment]
The private network tutorial you linked above has been updated. Here is the new version which works with `pre-v2.0-3e65111` https://substrate.dev/docs/en/tutorials/start-a-private-network/

And yes, currently we are recommending building on 3e65111 for experimentation. That is the version that is currently best documented.

I'm sorry you've struggled with the versioning. It has been tough for us writing the docs too. The good news is that that will change soon as we are just starting to publish Substrate on crates.io and soon v2.0 proper will be out.

Please continue to reach out with questions and we will do our best to help.

**Comment by drandreaskrueger** [comment]
Perfect. This time, I just asked before, to minimized the trouble. So ... all good.

Thanks a lot.  Have a great weekend.
