### ISSUE TITLE
v2 installing-substrate#manual-build

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-developer-hub.github.io#474]
https://github.com/paritytech/substrate/blob/3e651110aa06aa835790df63410a29676243fc54/README.md points to: getting started instructions.

https://substrate.dev/  
https://substrate.dev/en/who/  
https://substrate.dev/en/who/runtime-developer

Install Substrate #manual-build
https://substrate.dev/docs/en/getting-started/installing-substrate#manual-build

```# Update your rust toolchain
./scripts/init.sh
```
> bash: ./scripts/init.sh: No such file or directory

I think it's this file https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/getting-started/installing-substrate.md here in this repo, right?

**Comment by drandreaskrueger** [comment]
```
source ~/.cargo/env
rustup update
rustup default stable
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
cargo clean
```
right?

**Comment by shawntabrizi** [comment]
Somehow you are falling into our v1.0 docs. See the issue here:

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/463

That PR may close some of this issue for you.

All the latest install instructions for Substrate can be found here:

https://substrate.dev/docs/en/overview/getting-started#manual-installation

**Comment by drandreaskrueger** [comment]
wow, fast answer. Thanks a million.

> Somehow you are falling into our v1.0 docs. 

Try the above sequence of URLs --> that is how I ended up on the outdated page.

**Comment by shawntabrizi** [comment]
Opened an issue for the old links. Thanks for pointing that out. Feel free to ask any further questions about installing substrate here, or close the issue if you think your issue is resolved.

**Comment by JoshOrndorff** [comment]
Seems @drandreaskrueger has been helped and #475 has a specific call to action, so I'm closing this for now.
