### ISSUE TITLE
cargo test --release --all ?

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-developer-hub.github.io#476]
just an idea, can't the tests be run with `--release` ?

because [this page](https://substrate.dev/docs/en/overview/getting-started#substrate) says

> Build the project with:  
> cargo build --release
> Test the project with:  
> cargo test --all

but when I do the second part, then everything gets compiled AGAIN ... in the `target/debug` folder.

So, here's the simple idea:

    cargo test --release --all

wrong idea?

PS: I have just tried it out and _most_ tests are passing. The two that are not are `test tests/ui/impl_incorrect_method_signature.rs ... mismatch` and `test tests/ui/type_reference_in_impl_runtime_apis_call.rs ... mismatch` (HEAD on commit 3e651110aa06aa835790df63410a29676243fc54 tag: test-tag-pre-2.0, tag: pre-v2.0-3e65111).

**Comment by JoshOrndorff** [comment]
Yes, it's fine to run tests in `--release` mode and you should get the same results either way. :+1:

I'm not familiar enough with those tests to know what they are testing exactly, but I too would expect them to pass. If those failing tests are interfering with your work, please open an issue against the main Substrate repository.

**Comment by drandreaskrueger** [comment]
Great. Thanks.

I suggest you change your manual to `--release`, that saves compiling `target/debug`.

**Comment by JoshOrndorff** [comment]
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/481
