### ISSUE TITLE
Issue with api.query while building PoE dApp

### ISSUE THREAD

**Issue by mnlsbn** [substrate-developer-hub/substrate-developer-hub.github.io#487]
while adding the custom react component, i had the following issue in my front-end 
![image](https://user-images.githubusercontent.com/26409790/76165522-f7765d80-6157-11ea-9a33-31f2b354a8a6.png)
Any idea to solve this issue ?
Thanks

**Comment by riusricardo** [comment]
Hey @mnlsbn thanks for getting in touch. Can you give more details on what step you get the issue?

One option is that you're running the front-end-template using the unmodified code from the node-template. It is unable to find the storage value proofs because it doesn't exists in the template code. This storage value is created on the tutorial.

**Comment by mnlsbn** [comment]
Hey @riusricardo thanks for your reply. I have the issue when i try to add the react component in the front-end template. After replacing the code in the TemplateModule.js, i get an error for this line of code "api.query.templateModule".

**Comment by riusricardo** [comment]
What is really happening is that your Substrate node-template doesn't contains the final code. 
Does your rust code contains this section: https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet#callable-pallet-functions?

It should be working if your local node has the correct Substrate code.

**Comment by JoshOrndorff** [comment]
Remember that you'll need to purge your chain as described in the final section before the UI stuff https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet#compile-your-new-pallet

```bash
./target/release/node-template purge-chain --dev
```

**Comment by mnlsbn** [comment]
Many thanks @riusricardo @JoshOrndorff , I start again from the "building a custom pallet" step and it works fine
