### ISSUE TITLE
Bonded Token Tutorial

### ISSUE THREAD

**Issue by lsaether** [substrate-developer-hub/substrate-developer-hub.github.io#49]
As per the call earlier today I'm opening an issue to track the tutorial I wrote about bonding curve tokens as a Substrate runtime module. All the code compiles and is complete through a minimal token which is minted / burned from a bonding curve. The implementation could be expanded and the tutorial leaves off before describing the UI portion (the UI code is available in the repo and should be able to be started by following the quickstart). Right now, I don't have any definite plans to finish the UI part but if it turns out to be a priority, can definitely do that.

Another idea was to possibly include the code into the `party-samples` organization, which is something we could do too. 

[Link to code repository](https://github.com/lsaether/sr-bonded-token)

[Link to tutorial](https://github.com/lsaether/sr-bonded-token/blob/master/Tutorial.md)

**Comment by shawntabrizi** [comment]
@lsaether I noticed, in a quick review, you have some `init()` logic in your code. Are you familiar with the genesis config? Is there a reason not to use it here instead?

**Comment by shawntabrizi** [comment]
Welcome @lsaether. I gave your code a review earlier today and opened a number of issues which should help make your code a bit better :)

The tutorial, in my opinion is cool, but not a priority in the short term. See if you feel comfortable to grab some of the existing open issues around documenting Substrate in the context of the v1 release.

Feel free to reach out to me or others directly to help you get from 0 to 60
