### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v6.2.4`

### ISSUE THREAD

**Issue by Icatream** [substrate-developer-hub/substrate-developer-hub.github.io#502]
I have follow the [installation](https://substrate.dev/docs/en/overview/getting-started#getting-started-on-windows), but got this error.

#### Here are the buildtools version.

platform: win10 1809
os-version: 17763.1098

rust toolchain version:
nightly-x86_64-pc-windows-msvc (default)
rustc 1.43.0-nightly (c20d7eecb 2020-03-11)

clang version:
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

cmake version:
cmake version 3.17.0-rc3

#### Full error messages:
Compiling sc-finality-grandpa v2.0.0 (https://github.com/paritytech/substrate.git?rev=3e651110aa06aa835790df63410a29676243fc54#3e651110)
     Running `rustc --crate-name sc_finality_grandpa --edition=2018 C:\Users\28359\.cargo\git\checkouts\substrate-7e08433d4c370a21\3e65111\client\finality-grandpa\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=cd1f14bda1b8a1c8 -C extra-filename=-cd1f14bda1b8a1c8 --out-dir C:\Workspace\Github\substrate-node-template\target\release\deps -L dependency=C:\Workspace\Github\substrate-node-template\target\release\deps --extern finality_grandpa=C:\Workspace\Github\substrate-node-template\target\release\deps\libfinality_grandpa-8fcc1081f2a47539.rmeta --extern fork_tree=C:\Workspace\Github\substrate-node-template\target\release\deps\libfork_tree-14b4b868a9fc9aaa.rmeta --extern futures=C:\Workspace\Github\substrate-node-template\target\release\deps\libfutures-5574d475975657e4.rmeta --extern futures03=C:\Workspace\Github\substrate-node-template\target\release\deps\libfutures-da2393047174bec2.rmeta --extern futures_timer=C:\Workspace\Github\substrate-node-template\target\release\deps\libfutures_timer-429878baf30a5015.rmeta --extern log=C:\Workspace\Github\substrate-node-template\target\release\deps\liblog-a27d2e7b96d2aab0.rmeta --extern parity_scale_codec=C:\Workspace\Github\substrate-node-template\target\release\deps\libparity_scale_codec-581928b3e9169e87.rmeta --extern parking_lot=C:\Workspace\Github\substrate-node-template\target\release\deps\libparking_lot-d003309a4ca0c7f8.rmeta --extern rand=C:\Workspace\Github\substrate-node-template\target\release\deps\librand-b50f0c03dfa1fd9f.rmeta --extern sc_client=C:\Workspace\Github\substrate-node-template\target\release\deps\libsc_client-3d0c9c7135f7f3db.rmeta --extern sc_client_api=C:\Workspace\Github\substrate-node-template\target\release\deps\libsc_client_api-9bbd8dcf0e1af5b1.rmeta --extern sc_keystore=C:\Workspace\Github\substrate-node-template\target\release\deps\libsc_keystore-2c5dc67785955b98.rmeta --extern sc_network=C:\Workspace\Github\substrate-node-template\target\release\deps\libsc_network-cfba8a45885b5ff1.rmeta --extern sc_network_gossip=C:\Workspace\Github\substrate-node-template\target\release\deps\libsc_network_gossip-9a1cf75389f00e86.rmeta --extern sc_telemetry=C:\Workspace\Github\substrate-node-template\target\release\deps\libsc_telemetry-8ddd188fa79cad86.rmeta --extern serde_json=C:\Workspace\Github\substrate-node-template\target\release\deps\libserde_json-7ce9207d9f72b8f4.rmeta --extern sp_blockchain=C:\Workspace\Github\substrate-node-template\target\release\deps\libsp_blockchain-c20a911ed277487f.rmeta --extern sp_consensus=C:\Workspace\Github\substrate-node-template\target\release\deps\libsp_consensus-9b02ec1da700c594.rmeta --extern sp_core=C:\Workspace\Github\substrate-node-template\target\release\deps\libsp_core-98a76312fd73bb49.rmeta --extern sp_finality_grandpa=C:\Workspace\Github\substrate-node-template\target\release\deps\libsp_finality_grandpa-0b343494f723464d.rmeta --extern sp_finality_tracker=C:\Workspace\Github\substrate-node-template\target\release\deps\libsp_finality_tracker-8d13465f2889ac67.rmeta --extern sp_inherents=C:\Workspace\Github\substrate-node-template\target\release\deps\libsp_inherents-0040b826610d4c03.rmeta --extern sp_runtime=C:\Workspace\Github\substrate-node-template\target\release\deps\libsp_runtime-c5aeef4e072b5d48.rmeta --cap-lints allow -L native=C:\Workspace\Github\substrate-node-template\target\release\build\clear_on_drop-7af9bf4097e232f2\out -L native=C:\Workspace\Github\substrate-node-template\target\release\build\ring-80b42ab20314a96c\out -L native=C:\Workspace\Github\substrate-node-template\target\release\build\libz-sys-cfc9894b0e60e47f\out\build`
error: failed to run custom build command for `librocksdb-sys v6.2.4`

Caused by:
  process didn't exit successfully: `C:\Workspace\Github\substrate-node-template\target\release\build\librocksdb-sys-bdf78f6029eb9098\build-script-build` (exit code: 1)
--- stderr

error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "." "-W4" "-EHsc" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_PCLMUL=1" "-DHAVE_SSE42=1" "-DOS_WIN=1" "-DROCKSDB_WINDOWS_UTF8_FILENAMES=1" "-FoC:\\Workspace\\Github\\substrate-node-template\\target\\release\\build\\librocksdb-sys-f34557b0cde0f1ca\\out\\rocksdb/db/db_impl.o" "-c" "rocksdb/db/db_impl.cc" with args "cl.exe" did not execute successfully (status code exit code: 2).

I had updated the vs-buildtools, but i don't know how to check it's version.

**Comment by Icatream** [comment]
Some people has problem with compiling `librocksdb-sys v6.2.4`, at 2018 year.  They changed clang version and solved this problem.
I don't know if my problem came from version conflicts of clang or others.
I had run this in wsl, that works fine.

**Comment by JoshOrndorff** [comment]
I'm happy to hear that you've completed the tutorial. You will probably have a better time working in WSL.

I searched for someone who could help with your Windows issues but couldn't find anyone. I'll keep this issue open since we didn't really solve it so much as worked around it.
