### ISSUE TITLE
Start a private network tutorial not found.

### ISSUE THREAD

**Issue by noslav** [substrate-developer-hub/substrate-developer-hub.github.io#536]
https://substrate.dev/docs/en/next/tutorials/start-a-private-network/ 
https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/
https://substrate.dev/docs/en/next/tutorials/build-a-dapp

**Comment by JoshOrndorff** [comment]
Here are the correct links.

https://substrate.dev/docs/en/tutorials/start-a-private-network/
https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/
https://substrate.dev/docs/en/tutorials/build-a-dapp/

You can find them all in the index at https://substrate.dev/en/tutorials. Our Substrate.dev site has been updated recently, so sorry if that was confusing for you.

Would you mind telling us where you found those outdated links so we can update them?

**Comment by noslav** [comment]
https://substrate.dev/ -> [Getting Started](https://substrate.dev/docs/en/getting-started/)
