### ISSUE TITLE
Evaluate Search Options

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#546]
Search on substrate.dev is not working. The results that are returned do not seem high-quality and there appear to be duplicate entries. Search results lead to 404s.

**Comment by riusricardo** [comment]
This is why we need to reset the Algolia search engine.

**Comment by danforbes** [comment]
Since search was broken, it was disabled with #548. In the short-term, the default Algolia search capabilities may be re-enabled. This decision needs to be re-evaluated by 2020-06-12; ideally, we will have switched to a locally-host search solution by that time, however [it's not clear if the version of Docusaurus we are using supports this](https://github.com/facebook/docusaurus/issues/776#issuecomment-639451782).

cc: @kirushik

**Comment by danforbes** [comment]
Ref: https://github.com/the-darc/Docusaurus#express-middleware-example

**Comment by kirushik** [comment]
Re express-middleware-example — I would actually be against us having any special _search server_ for the search. We would be better off integrating a third-party solution in such case, at least for security and DevOps-related reasons.

But aren't you overthinking it? Adding custom client-side search would only require:
1) tweaking our page template to include the search form and associated search script tags (similar to what we do in say [Footer.js](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/website/core/Footer.js))
2) adding an additional step into our [CI config](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/.circleci/config.yml) to index required files and put the resulting index files into the `static/` folder of the Github pages.

I understand that I am most likely missing some important subtleties — but so far it seems to me that it can be done in a day or two, reliably, without investing too much effort into reviewing other solutions or finding a ready-made one.

**Comment by kirushik** [comment]
And, as I've already mentioned in Riot, we can still have version and locale scopes for our search with this setup — by generating a separate index for each individual locale/version, and loading only it into the search bar configuration when you're browsing this particular facet of the site.

**Comment by danforbes** [comment]
Adding some additional references to support the idea that @kirushik has. Essentially, we will disable Algolia search and include a custom JS component in our header that will search a client-side index we include as part of the website's source. We need to see if this can reasonably be implemented in 1-3 weeks time.

https://stork-search.net/
https://lunrjs.com/
https://lucaongaro.eu/blog/2019/01/30/minisearch-client-side-fulltext-search-engine.html

**Comment by danforbes** [comment]
Ref https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/tree/df/fix/search

**Comment by NukeManDan** [comment]
Closing as we have a new site with better searching features: https://github.com/substrate-developer-hub/substrate-docs/
