### ISSUE TITLE
Tutorial Start private chain shouldn't depend on polkadot.js/apps

### ISSUE THREAD

**Issue by brenzi** [substrate-developer-hub/substrate-developer-hub.github.io#552]
In the tutorial you suggest inserting keys with polkadot.js/apps

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/tutorials/start-a-private-network/customchain.md

This is very inconvenient when setting up a cloud vps because you'd need to expose the RPC port, provide `wss://` by setting up let's encrypt first or build polkadot.js/apps on the vps itself. All this is so much easier with `curl` (like the tutorial was previously). Please at least mention that option.

**Comment by danforbes** [comment]
Closing in favor of https://github.com/substrate-developer-hub/tutorials/issues/21. I will prioritize this.
