### ISSUE TITLE
Update 404 page

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#556]
I see a lot of comments like:

```
I can't find it on the website where it used to be https://substrate.dev/docs/en/next/tutorials/visualizing-node-metrics#step-3-configure-prometheus-to-scrape-your-substrate-node
```

based on the latest updates to the developer hub. I suggest you do a simple update to your 404 page so that people who land on these old links are automatically redirected to the right place.

**Comment by wheresaddie** [comment]
updating now. thanks
