### ISSUE TITLE
Consider whether to support manual install on more Linux distributions

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#560]
In https://github.com/paritytech/substrate/issues/6299 the user was unable to install Substrate on Fedora. That makes sense because our instructions are for Debian. The user found that this command works for Fedora

```
sudo dnf install -y cmake pkg-config openssl-devel git gcc @development-tools clang clang-devel
```

This issue is to decide which distros we want to support and document it somewhere.

**Comment by danforbes** [comment]
Related: https://github.com/paritytech/substrate/issues/5681

We should determine a set of supported environments and then create CI processes, VMs, etc to ensure that a set of minimal commands (e.g. installation) works across all those environments.

**Comment by NukeManDan** [comment]
Fedora, Arch, Debian, Nix(OS), MacOS, Windows all now mentioned. No CI to check, but reports are that the minimal set of deps works on all platforms.
