### ISSUE TITLE
CI (incorrectly) reports several links as broken

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#561]
This run reports several links as broken although they seem to be fine to me. https://circleci.com/gh/substrate-developer-hub/substrate-developer-hub.github.io/1950

The "broken" links include:
* https://github.com/centrifuge/go-substrate-rpc-client
* https://github.com/scs/substrate-api-client
* https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

**Comment by JoshOrndorff** [comment]
Looking loser at the failed job it seems related to rate limiting. The response is [HTTP 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)

**Comment by NukeManDan** [comment]
I have see something like this, but infrequently, and only on many pushes triggering back to back link checking that sometimes fails.
Think this is worth a bump to devops @danforbes, as your linked PR is rather stale? I can bump there as well...
 IMHO it's not annoying enough (a rerun usually works fine) to merit it.

**Comment by NukeManDan** [comment]
#979
