### ISSUE TITLE
Quick TODO Fixes

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#575]
There are 10 instances of TODO in the current docs:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1860335/84691233-1ac55b80-af44-11ea-9f3f-e06beb1480d1.png">

Seems like a quick sprint could help resolve these issues and remove the TODOs

**Comment by NukeManDan** [comment]
Porting to https://github.com/substrate-developer-hub/substrate-docs/issues/158
