### ISSUE TITLE
Better Runtime Upgrade Documentation

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#580]
We can create more [documentation around runtime upgrades](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/knowledgebase/advanced/executor.md#runtime-upgrades), which is one of Substrate's most important and distinguishing characteristics. In particular, a community member recently asked for an enumeration of the changes that _can_ be included in a  forkless runtime upgrade and those that _cannot_.

**Comment by wheresaddie** [comment]
yes.. great suggestion.. ! will put this on the list for next week's DevHub to-dos. thanks for the suggestion @danforbes

**Comment by JoshOrndorff** [comment]
Some existing (but possibly slightly outdated) resources you may find helpful:
https://substrate.dev/substrate-beginner-workshop/#/
https://www.youtube.com/watch?v=0eNGZpNkJk4&list=PLp0_ueXY_enXRfoaW7sTudeQH10yDvFOS (also features storage migrations)
https://www.youtube.com/watch?v=yHodYke7nms&list=PLp0_ueXY_enXRfoaW7sTudeQH10yDvFOS

**Comment by danforbes** [comment]
Comments from @HCastano on how Knowledge Base docs can complement #670 

    How does the node know to use the version on chain instead of the native version?
    Why does the runtime + client split allow for this? (Might be helpful to go into the responsibilities of each)
    Under what circumstances would I need to restart my node?
    Potential "gotcha's", like not updating the spec_version

**Comment by danforbes** [comment]
The enhanced documentation should include the materials created by @apopiak https://hackmd.io/BQt-gvEdT66Kbw0j5ySlWw

**Comment by wheresaddie** [comment]
thanks for tackling this @danforbes I made some minor PRs on #750 and appreciate the additional context and documentation <3

**Comment by apopiak** [comment]
@danforbes Do you want to use a new issue to track things like a runtime migration tutorial or the above mentioned "things that can and cannot be changed via runtime upgrade" or do we want to reopen this one?

**Comment by wheresaddie** [comment]
Id start new ones @apopiak @danforbes otherwise its just a link to a link to a link until we all die
