### ISSUE TITLE
Link to GRANDPA PDF Broken

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#582]
Can we link to https://github.com/w3f/consensus/blob/master/pdf/grandpa-old.pdf? Is there some better replacement?

**Comment by wheresaddie** [comment]
maybe find grandpa-new? otherwise link to wikipedia ...?

**Comment by danforbes** [comment]
I checked, there is no "new" one, and the one that doesn't say "new" doesn't have a PDF version (only available in `.tex`). I have reached out to Bill from W3F to ask him the right thing to do.

**Comment by wheresaddie** [comment]
thanks @danforbes .. let me know what Bill suggest

**Comment by danforbes** [comment]
cc @AlistairStewart, @laboon

**Comment by JoshOrndorff** [comment]
So I didn't see this issue, and went ahead and "fixed" it by linking to https://w3f-research.readthedocs.io/en/latest/polkadot/GRANDPA.html ... I did it as an afterthought in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/577

Would be happy to revert if necessary.

**Comment by danforbes** [comment]
From @AlistairStewart
> ...keep linking to grandpa-old, maybe even after there is a grandpa.pdf. I'm aiming to post that one online today or tomorrow, but grandpa-old will still be more complete.

**Comment by danforbes** [comment]
@JoshOrndorff - I requested your review on the PR to fix this. Let's go with the specific link that @AlistairStewart mentioned. Thanks for being proactive about fixing the link!
