### ISSUE TITLE
Anchor Links in the Knowledge Base are Broken

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#597]
Anchor links within the storage documentation are broken https://substrate.dev/docs/en/knowledgebase/runtime/storage It looks like this is a capitalization problem.

**Comment by wheresaddie** [comment]
fixed bugs

**Comment by JoshOrndorff** [comment]
Was there a PR to address this?

**Comment by danforbes** [comment]
I do not believe so; here is the commit https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/commit/bc2bd3b8b99018a640e32a2e27a6c0f8b53081e1#diff-e9947298703a618ed717a990ee96c70a
