### ISSUE TITLE
rustdoc docs generator for master & all Substrate versions released on crates.io

### ISSUE THREAD

**Issue by bjornwgnr** [substrate-developer-hub/substrate-developer-hub.github.io#6]
docs.rs (https://github.com/rust-lang/docs.rs) has a nice UI and supports versioning, unfortunately they don't host docs for master (only for versions released on crates.io).

**Comment by nczhu** [comment]
The question is what version we want to show as a default, long term: 
- Latest stable release version
- Pre-release version, with possible breaking changes and misleading documentation, i.e. the master branch

I think after 1.0.0 release (next few days?), we should default to showing the stable release. Which is also doc.rs' default.

However, we should make sure we can give users access to something like **1.0.1-pre.1**. 

Next steps: Looking into setting this up & how we'll handle pre/stable

**Comment by bkchr** [comment]
I don't think that 1.0 will be on docs.rs. We still have some git dependencies and that prevents us from uploading stuff to crates.io.

We have crates.parity.io that already hosts the master docs.

**Comment by shawntabrizi** [comment]
All of our rustdocs, can be placed in the `rustdocs` repo now, where we can have separate folders for each "branch/version" of Substrate.

Gonna close this.
