### ISSUE TITLE
Document How Chain State Exports Can Help with Storage Migrations

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#611]
Have these capabilities been documented anywhere? https://hackmd.io/mGgNZX0VT4S0UTaq89-_SQ Consider documenting more use cases around these capabilities, such as updating validator sets:
1. Delete all session and staking keys from the exported spec
2. Create a spec for a vanilla chain with desired validators
3. Copy all items at same keys into the exported spec

**Comment by JoshOrndorff** [comment]
Kian also presented on this technique at seminar https://www.crowdcast.io/e/substrate-seminar/5

**Comment by jimmychu0807** [comment]
@apopiak  Alex we have an issue here on storage migration.

**Comment by apopiak** [comment]
[This tool](https://github.com/maxsam4/fork-off-substrate) is also aimed at making this easier.

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-docs/issues/163
moving here
