### ISSUE TITLE
"Well Known Keys" should mention Dev Seed

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#613]
The section in the dev hub mentions well known accounts like `//Alice`, but does not mention that there is some underlying magic happening to generate the final private key for these accounts.

https://substrate.dev/docs/en/knowledgebase/integrate/subkey#well-known-keys

Specifically there is a dev phrase used whenever a mnemonic phrase is omitted:

https://github.com/paritytech/substrate/blob/293bcd6059f1e4e3dd95aa64989dadef4234222d/primitives/core/src/crypto.rs#L52

so `//Alice` is really:

```
bottom drive obey lake curtain smoke basket hold race lonely fit walk//Alice
```

And anyone not using Polkadot JS or Subkey would need to know this information to properly generate the account.

This information should be added to this section.

**Comment by wheresaddie** [comment]
Super appreciate this, adding now.
