### ISSUE TITLE
Developer Hub Resources Should Not Open in New Tab

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#623]
Opening in a new tab (`target='blank'`) is an anti-pattern ([reference](https://css-tricks.com/use-target_blank/)). The tutorials open in a new tab, which should be fixed, as should other unnecessary uses of `target='blank'` in the Developer Hub code base.

**Comment by JoshOrndorff** [comment]
I agree this is weird and should be fixed.

Tangent: I read the whole article you referenced. Beforehand I was in the [external-links-should-open-in-a-new-tab camp](https://css-tricks.com/use-target_blank/#a-bad-reason-internal-links-and-external-links-are-different). But the article convinced me to be more open minded about that.

**Comment by danforbes** [comment]
I'm glad you got something out of that article...I did as well and think it's a great reference.
