### ISSUE TITLE
Pinned Repositories

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#626]
I'm just using this GitHub repository as a vehicle for this Issue...it doesn't really "belong" here. I suggest that we pin the following repos (in this order) to the Developer Hub organization in GitHub:

1. Node template
2. Pallet template
3. Front-end template
4. Parachain template
5. Cumulus workshop
6. Enterprise sample

**Comment by JoshOrndorff** [comment]
I think those are all worthy repos to be pinned, and I understand we only have 6 slots to pin. Two others we might consider pinning though:

* This devhub repo
* Whichever repo has the most stars

**Comment by danforbes** [comment]
The reason I didn't include this repo in the list of pinned repos is because I really don't think anyone from the community would ever really care about this repo. I suppose they may fork it at some point and make some documentation enhancements, but I think that is secondary to encouraging people to work with our template/tutorial projects. I definitely like the suggestion to check out what has the most stars.

**Comment by danforbes** [comment]
I have updated the pins and will leave this Issue open for people to consider the choices I made. I chose to highlight resources that I felt have GitHub as an entrypoint, as opposed to resources like substrate.dev or Recipes, which have their own dedicated entrypoints. I also used GitHub stars to help me determine the repos to choose and the order in which to pin them. Please let me know what you think.

**Comment by riusricardo** [comment]
> I have updated the pins and will leave this Issue open for people to consider the choices I made. I chose to highlight resources that I felt have GitHub as an entrypoint, as opposed to resources like substrate.dev or Recipes, which have their own dedicated entrypoints. I also used GitHub stars to help me determine the repos to choose and the order in which to pin them. Please let me know what you think.

@danforbes I see recipes as the first pinned repository. Also the utxo-workshop is there.

**Comment by danforbes** [comment]
Yes, I modified the list I provided above based on stars. Anything in particular you think we should swap out?

**Comment by riusricardo** [comment]
> Yes, I modified the list I provided above based on stars. Anything in particular you think we should swap out?

Ok, makes sense. I like the UTXO but it is outdated an may not work. I always wondered if we should find a way to do it more friendly.

**Comment by danforbes** [comment]
Yeah that's a good point that UTXO is probably out-of-date. Probably makes sense to replace it with the parachain template. I will do that now.
