### ISSUE TITLE
New tutorial: Interacting with a Pallet using Apps

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#639]
Polkadot JS Apps is the defacto standard way to interact with a running Substrate node. When developing new pallets, Apps is a great tool to test them quickly before building a custom UI. We should have a tutorial that covers the basic process of:

1. Connecting to your local node
2. Entering custom types
3. Submitting extrinsics on the extrinsics tab
4. Querying chain state

optional: maybe we should use the front end template instead now that I think about it, but adding custom types is still significantly harder there than it is in apps.

**Comment by NukeManDan** [comment]
Joshy, would you say that https://substrate.dev/docs/en/tutorials/build-a-dapp/ covers this? If not, let's reopen this issue.
