### ISSUE TITLE
Subkey Tutorial is outdated as of v2.0.0-rc6

### ISSUE THREAD

**Issue by mswezey23** [substrate-developer-hub/substrate-developer-hub.github.io#640]
`subkey --ed25519 inspect "infant salmon buzz patrol maple subject turtle cute legend song vital leisure"`

No longer works!

`subkey inspect-key --scheme Ed25519` 
Prompts the user with: `URI:`  user enter's URI; enter.
Spits out generated output as expected. 

Docs: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/tutorials/start-a-private-network/keygen.md

![image](https://user-images.githubusercontent.com/1747669/90970655-57c24700-e4cd-11ea-9991-78f8a5322be2.png)

**Comment by bkchr** [comment]
This should work again on master.

**Comment by wheresaddie** [comment]
successfully ran for me
