### ISSUE TITLE
Subkey Commands out of date with latest Substrate

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#645]
Latest Substrate seems to have updated Subkey commands.

https://substrate.dev/docs/en/tutorials/start-a-private-network/keygen

This page says to do:

```
subkey --sr25519 generate
```

where the command is now:

```
subkey generate --scheme sr25519
```

Would be good to double check all other subkey commands too.

**Comment by wheresaddie** [comment]
squash and merge please @shawntabrizi
