### ISSUE TITLE
https://substrate.dev/en/docs/en 404

### ISSUE THREAD

**Issue by tengpeng** [substrate-developer-hub/substrate-developer-hub.github.io#673]
I opened https://substrate.dev/en/docs/en and it returns 404

1. Open https://substrate.dev/en/
2. Click "Get started" => https://substrate.dev/en/docs/en
3. Returned 404

**Comment by danforbes** [comment]
Hi, @tengpeng - sorry for the confusion. I think this may be an artifact of the fact that we are not really linking in Docusaurus correctly. If you start by going to just www.substrate.dev, the "Get Started" button should work just fine :+1:

**Comment by s3krit** [comment]
I just ran into this bug

### Steps to reproduce:
1. Go to https://substrate.dev
2. Click 'Get started', which directs you to https://substrate.dev/docs/en/
3. Click the 'Substrate Developer Hub' logo in the top-left to return to the homepage, which directs you to https://substrate.dev/en/
4. Click 'Get started' again

### Expected result

On step 4, you get directs to the same page as step 2 (https://substrate.dev/docs/en/)

### Observed result

On step 4, you get directed to https://substrate.dev/en/docs/en - which returns a 404

**Comment by wheresaddie** [comment]
@Stefie might need to know about this and @imadarai who is reworking the site atm. thanks for the follow up

**Comment by Stefie** [comment]
Hey! I never worked on the developer hub so I can‘t really help with any issues here. Maybe @shawntabrizi knows more about it?!
