### ISSUE TITLE
Sample/one-pager: on_initialize, on_finalize

### ISSUE THREAD

**Issue by nczhu** [substrate-developer-hub/substrate-developer-hub.github.io#68]
from @shawntabrizi : 
On_finalize and on_initialize would be a perfect one-pager, especially talking about what they are good for with examples:

on finalize for storage clean up, fees, some sort of state verification, ...?
on initialize for storage migration, updates, long processes where you need as much computation time as possible (rather than at the end, where it may not complete past the recommended block time)

**Comment by JoshOrndorff** [comment]
I've opened this issue https://github.com/paritytech/substrate/issues/2818

I hope there will be a best practice for forwarding the blockchain during testing.
`System::set_block_number(System::block_number() + 1);` is not sufficient if any of your runtime uses `on_initialize` or `on_finalize`.

**Comment by shawntabrizi** [comment]
Take a look at something like `run_to_block` in Polkadot crowdfund:
https://github.com/paritytech/polkadot/blob/master/runtime/src/crowdfund.rs#L671

In general, if we wanted to follow exactly how executor does it, we would need to create an array of modules:

I agree this can be done generally. Speaking about this issue though, @4meta5 should consider a recipe for this one
