### ISSUE TITLE
Sample/one-pager: genesis config

### ISSUE THREAD

**Issue by nczhu** [substrate-developer-hub/substrate-developer-hub.github.io#70]
Explaining the Genesis Config in greater detail:

How to set up things like (and what they mean): 
- total issuance
- existential deposit
- transfer fee
- vesting 
- creation fee
etc.

How to create new storage variables for genesis, how to set up genesis in testing, when to use add_extra_genesis, etc.

**Comment by gautamdhameja** [comment]
We have a small part of the last point (How to create new storage variables for genesis) in the GenesisConfig Type doc - https://docs.substrate.dev/docs/genesisconfig-struct
Should be considered when writing this doc.

**Comment by JoshOrndorff** [comment]
Some of this content is covered in https://www.shawntabrizi.com/substrate-collectables-workshop/#/5/testing-genesis

**Comment by JoshOrndorff** [comment]
And a helpful example from nicole https://github.com/substrate-developer-hub/substrate-collectables-workshop/pull/100#discussion_r287309170

**Comment by JoshOrndorff** [comment]
This tidbit came across substrate technical chat.

```
Guillaume
I would expect to show in the doc, it is added here
https://github.com/paritytech/substrate/blob/master/srml/support/procedural/src/storage/transformation.rs#L437

and defined here
https://github.com/paritytech/substrate/blob/master/srml/support/procedural/src/storage/transformation.rs#L416
if you do cargo doc don't you have this PhantomData field (I'm actually not sure it is, but I thought so)
bedeho / Joystream
Now it says

"
193 |         _generisi_phantom_data: Default::default() 
    |         ^^^^^^^^^^^^^^^^^^^^^^ help: a field with a similar name exists: `_genesis_phantom_data`
"
Guillaume
it is just a phantom data to deal with the generic argument T. If you are sure that you genesis config don't need this extra field you can bypass our best effort assumption using another definition in decl_storage which is used here for example:
https://github.com/paritytech/substrate/blob/master/srml/balances/src/lib.rs#L334
yes _genesis_phantom_data not _genesisi_phantom_data
bedeho / Joystream
oh, I didnt see the typo. Ok, that actually worked.
Guillaume
cool :-)
bedeho / Joystream
but I don't understand why this was needed here in particular?
I have another genesisconfig type where I dont need to do this
what is the distinction?
This is the only configurable field for this gensisconfig where your fix had an effect

pub ForumUserById get(forum_user_by_id) config(): map T::AccountId => Member<T::AccountId>;
Guillaume
we might lack doc here indeed but I would expect this field to be shown in doc.

decl_storage generate struct GenesisConfig<T: Trait> {..} this genericity is used later for some stuff.
But if the field of your genesis config doesn't make use of T like

struct GenesisConfig<T: Trait> {
forum_by_id: u64,
}
Then rust can't compiles because T is not used in the struct.

In our macro we try to distinguish with a best effort method when it used and when it is not. if it seems not to be used we add a phantomdata field to capture it

I'm a bit surprise by this definiton as our macro should have seen T::AccountId and thus see that T was used by genesis config.

Also if you are sure T is used (if it compiles) then you can add an extra field in decl_storage which is extra_genesis_skip_phantom_data_field; look at srml/balances/src/lib.rs
this bypass our assumption
```

**Comment by JoshOrndorff** [comment]
https://crates.parity.io/srml_support_procedural/macro.decl_storage.html#genesisconfig

**Comment by JoshOrndorff** [comment]
Started a draft at https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/154 but got stuck earlier than expected on a compile issue related to the `_genesis_phantom_data` issue discussed above.

**Comment by bkchr** [comment]
You just need to give it this value and initialize it to `Default::default()`.
On master this is fixed, but we can not backport as this breaks some code.

**Comment by JoshOrndorff** [comment]
Thanks for that tip @bkchr !

#154 is merged now, so I'm closing this.

**Comment by lerajk** [comment]
not very clear in this tutorial on how to set up the genesis configuration. it will be useful to add some references.

https://substrate.dev/substrate-verifiable-credentials/#/docs/securing-issuing

**Comment by JoshOrndorff** [comment]
@lerajk Are you currently stuck on this? If you share your code I can help you get unstuck. If you can say what wasn't clear or have some specific tips to fix that tutorial, you could open an issue over here https://github.com/substrate-developer-hub/substrate-verifiable-credentials/issues
