### ISSUE TITLE
Check Runtime Metadata page for accuracy of Substrate v2 and metadata v12

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#701]
The Runtime Metadata page was recently updated https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/691 but the sample metadata we use still states `V11`. We should check to make sure that this page is correct and update it if needed.

**Comment by wheresaddie** [comment]
closing in lieu of #707
