### ISSUE TITLE
Proof of Existence is not showing while building a PoE Decentralized Application 

### ISSUE THREAD

**Issue by ayushmishra2005** [substrate-developer-hub/substrate-developer-hub.github.io#725]
I have followed all the steps, mentioned here https://substrate.dev/docs/en/tutorials/build-a-dapp/front-end. But still, I am not able to see Proof of Existence on the frontend.

It looks like some steps or code is missing at this step https://substrate.dev/docs/en/tutorials/build-a-dapp/front-end#add-your-custom-react-component

**Comment by wheresaddie** [comment]
can you post a screen shot of the error in your console/log please @ayushmishra2005

**Comment by jimmychu0807** [comment]
@ayushmishra2005 Did you run `yarn install` and then `yarn start` after pasting the React code? What did you see on your screen?

**Comment by wheresaddie** [comment]
:popcorn:

**Comment by ayushmishra2005** [comment]
@jimmychu0807 As per the documentation, restarting `yarn` is not required. Please see below screenshot

![image](https://user-images.githubusercontent.com/1575561/96252679-f8198100-0fcf-11eb-8d4c-fedb866addb1.png)

However I also tried `yarn install` and `yarn start`, but I am still facing the same issue.

**Comment by wheresaddie** [comment]
can you post a screen shot of the error you are getting @ayushmishra2005 ?

**Comment by ayushmishra2005** [comment]
@wheresaddie I am not getting any error. After `yarn start`, I am getting below screen


![image](https://user-images.githubusercontent.com/1575561/96260235-649a7d00-0fdc-11eb-931d-06995e8b085c.png)

**Comment by danforbes** [comment]
@ayushmishra2005 the front-end will not show the PoE component if the chain that it is connected to does not support those capabilities. Are you sure that you updated the node and restarted it after it doing so https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet#compile-your-new-pallet?

**Comment by ayushmishra2005** [comment]
Thanks @danforbes . It works.
