### ISSUE TITLE
Create a Workshop/Tutorial on Setting Up a Test Network with Multiple Peers

### ISSUE THREAD

**Issue by gautamdhameja** [substrate-developer-hub/substrate-developer-hub.github.io#74]
Create a (node-template) test net and play around

- Story: “Put your own test network on the telemetry page”
- Better understand the chainspec, modify it
- Story of the node template
- 2-4 hour workshop where at the end, all users are connected to a single network

**Comment by shawntabrizi** [comment]
@JoshOrndorff

**Comment by JoshOrndorff** [comment]
Here is a rough draft of my writeup https://gist.github.com/JoshOrndorff/bb9f7eb69ca6b51a0112a01bbb9405f8

I'd love feedback especially from @gautamdhameja since he worked on this with me.

cc @jimscarver @jeremybeal11 since we practiced this the other night.

**Comment by gautamdhameja** [comment]
Here's some feedback on the tutorial draft:

1. I don't think we need to ask the users to clone the entire Substrate repo and build from there. We can simply ask them to install Substrate and use the substrate-node-new command to clone and build the node template. This is simpler and less error-prone.

2. Because of point 1, we can get rid of the update and related sections. I am in favour of a short and simple tutorial and not diving deep into things that do not directly relate to the network setup process.

3. The following creates confusion. We should either rephrase it or just remove it. If we want this to be there then let's find out the reason for that line of code and briefly explain this here.

> You'll notice (both in the terminal and the UI) that no blocks are being produced yet. I'm not really clear on the motivation of why, but this line is probably relevant. Blocks will start being produced once another validator joins the network.

4. We should add the screenshots from the Polkadot Apps portal and telemetry UI when the nodes are connected. At the moment it is not clear to the user how they should know that everything is working as expected after connecting the UI.

PS: We have to keep in mind that this tutorial might be read/used by users even before they try other tutorials (custom-chain and substratekitties), so it will not hurt to have some basic things like UI screenshots added.

**Comment by JoshOrndorff** [comment]
Thanks a ton for the feedback @gautamdhameja !

Re 1 and 2.
I disagree with you here. The problem with relying on `substrate-node-new` is that it will always pull the latest version of the repo. That leads to the following practical problem. Imagine Alice and Bob follow the tutorial on Monday and succeed. They are so excited they try to do the same thing with Carol the next day. Carol now has a newer, and possibly incompatible node than Alice and Bob. If https://github.com/paritytech/substrate-up/issues/31 gets solved, then I will agree with 100% here. While shorter instructions are generally desirable, I think in this case the probability of confusion is too high, and the longer form is worthwhile.

3. I think it's important to tell the user that it's normal for no blocks to be produced. If you prefer removing the code reference I'm fine with that. What do you think about phrasing it as, "You'll notice (both in the terminal and the UI) that no blocks are being produced yet. Curious learners can see why here (link to code)"

4. I agree 100% with this. I actually think it would be preferable for users to go through this tutorial before writing their own runtimes.

**Comment by JoshOrndorff** [comment]
Question. After we deem this tutorial good-enough-to-publish, where should it be published to? Ideally it could be under version control.

@shawntabrizi I see you've made some commits in this repo recently. Should I drop it in here?

One strategy for migrating from readme.io is to have more and more of the links be external links to the new home (maybe this repo on github pages?).

**Comment by gautamdhameja** [comment]
> The problem with relying on substrate-node-new is that it will always pull the latest version of the repo. 

I don't think this is true anymore. The substrate-node-new script was recently updated to use the v1.0 tag. Also, I could see this problem arising by cloning the latest codebase all the time if older participants don't update/pull in time.

**Comment by JoshOrndorff** [comment]
It was updated to use the v1.0 _branch_ which doesn't move _as_ fast as master, but his still had 7 commits in the last 3 days https://github.com/paritytech/substrate/commits/v1.0

There is no v1.0 tag https://github.com/paritytech/substrate/tags

**Comment by gautamdhameja** [comment]
Yeah, so v1.0 branch. And it will further stabilize once we move near to the release. In any case, cloning from the master branch of repo every time is still not the best option, imo.

**Comment by laboon** [comment]
Some minor typo cleanup:

* "ecause substrate is a framework," -> "**Because** substrate is a framework,"
* "ultimately the key's " -> "ultimately the **keys**"
* "One the chainspec is ready," -> "**Once** the chainspec is ready,"
* "What if you want to add more validators after starting the blockchain." -> "What if you want to add more validators after starting the blockchain**?**" 
* "The authority set can be change after genesis " -> "The authority set can be **changed** after genesis "
* "a simple module that wrap's " -> "e a simple module that **wraps** "

**Comment by jeremybeal11** [comment]
My feedback():

**Requirement**: 

- i think it would be helpful to add a basic requirement section that tells the users what they will need(like git, etc)

**Compiling the Tools**

1.  i wouldn't mention that it takes a long time(i fear it can potentially deter people because their is no number on how long it takes)

**Your first time**

- i would recommend an actual location to download Substrate(like root or a specific testing location)

**Updating Later:**

- do they need to go back to the directory substrate is downloaded in(i think it would be helpful to specify)

- also should they also update the subkey just in case(as we saw it won't run if everyone has different key versions)

**Comment by laboon** [comment]
The initial git clone command doesn't work:

```
(20204) $ git clone https://paritytech/substrate
Cloning into 'substrate'...
fatal: unable to access 'https://paritytech/substrate/': Could not resolve host: paritytech
```

Do you mean:

```
https://github.com/paritytech/substrate
```

**Comment by laboon** [comment]
```
./target/debug/node-template \
  --base-path /tmp/alice \
  --chain=local \
  --key //Alice \
  --port 30333 \
  --telemetry-url ws://telemetry.polkadot.io:1024 \
  --validator
  --name AlicesNode
```

This needs a `\` after `--validator` as well

**Comment by laboon** [comment]
Before starting `./target/debug/node-template`, we should state that you should be in the root directory ( `cd ..` if we want to be explicit) since users were in the ./node-template subdirectory immediately before this.

**Comment by laboon** [comment]
We also need some `\`'s for Bob's node

```
./target/debug/node-template \
  --base-path /tmp/bob \
  --chain=local \
  --key //Bob \
  --port 30333 \
  --telemetry-url ws://telemetry.polkadot.io:1024 \
  --validator
  --name BobsNode
  --bootnodes /ip4/<Alices IP Address>/tcp/<Alices Port>/p2p/<Alices Node ID>
```

should be

```
./target/debug/node-template \
  --base-path /tmp/bob \
  --chain=local \
  --key //Bob \
  --port 30333 \
  --telemetry-url ws://telemetry.polkadot.io:1024 \
  --validator \
  --name BobsNode \
  --bootnodes /ip4/<Alices IP Address>/tcp/<Alices Port>/p2p/<Alices Node ID>
```

**Comment by laboon** [comment]
If people are going to mostly start both of these on the same machine, perhaps we should also change `--port` value to, say, 30334?

**Comment by laboon** [comment]
"Alice's node ID which she copied from her log " -> It might be usefult o add something like 

"This node ID will look something like this: `QmWnsCra3h5ShZW8ZSosWfX99NUf4GucTr8pGAimgoNqvB`."

**Comment by laboon** [comment]
```
When you have generated a key pair, record the entire output somewhere safe, and share your public address (the last line in the example) with the other validators in the network. When everyone in the network knows everyone else's addresses, you are ready to proceed to launch your own chain.
```

How is sharing done?  Off-chain?  Replace the key in the `node-template` commands above and restart?

**Comment by laboon** [comment]
Another typo: " compile the node-tmeplate" -> " compile the **node-template**"

**Comment by JoshOrndorff** [comment]
Thanks for all the feedback @laboon and @jeremybeal11 . I've incorporated it into the draft. More feedback is always welcome, but I'm inclined to say these instructions work.

@laboon Were you able to successfully spin up the network?

**Comment by JoshOrndorff** [comment]
Relevant code that @gautamdhameja wrote for adding validators after genesis https://github.com/gautamdhameja/substrate-poa

**Comment by JoshOrndorff** [comment]
The draft is now stable enough that I moved it to https://docs.substrate.dev/docs/deploying-a-substrate-node-chain.

@ltfschoen Would you mind pasting your suggestions here as well?

**Comment by JoshOrndorff** [comment]
Still to do
* Use v1.0 branch
* compile subkey (or use the polkadot api)

**Comment by ltfschoen** [comment]
> The draft is now stable enough that I moved it to https://docs.substrate.dev/docs/deploying-a-substrate-node-chain.
> 
> @ltfschoen Would you mind pasting your suggestions here as well?

i can't remember which room you posted https://gist.github.com/JoshOrndorff/bb9f7eb69ca6b51a0112a01bbb9405f8 into, that's where i posted my suggestions

**Comment by JoshOrndorff** [comment]
I've just merged the last updates. Writing the tutorial is done, so I'm closing this. Additional feedback or corrections are welcome as new issues or PRs.

Final Product: https://substrate.dev/docs/en/tutorials/start-a-private-network-with-substrate
