### ISSUE TITLE
Search bar non-funtctional

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#746]
I have tried on firefox and brave browsers now... https://substrate.dev/docs/en/ and on https://substrate.dev 

The top right search function doesn't accept a `return` key and the magnifier glass icon is not clickable...  Am I missing something? 

In the dev tools, I see no event listener attached to this element.

**Comment by NukeManDan** [comment]
There _should_ be search in the recipies using `mdbook` but I don't see this feature on the page (and `s` key does nothing). The rust docs search works fine though

**Comment by wheresaddie** [comment]
yes this is a known issue @NukeManDan and something we are actively working to update and change with the next GUI rework (which should happen any time now)
