### ISSUE TITLE
Detailed SRML Dependency Diagram

### ISSUE THREAD

**Issue by joepetrowski** [substrate-developer-hub/substrate-developer-hub.github.io#75]
Make diagram of SRML inter-dependencies.

**Comment by joepetrowski** [comment]
Start here: https://docs.google.com/presentation/d/1aJ1AtAJTogxu1Ek6iUNe2tsCKg_oirI6r7x0kI1Jyys/edit?usp=sharing

![image](https://user-images.githubusercontent.com/25483142/57300157-8351d000-70d6-11e9-82e7-29d1046f7393.png)

**Comment by ltfschoen** [comment]
https://github.com/brenzi/substrate-doc/blob/master/SRMLmodules.svg

**Comment by joepetrowski** [comment]
Closing this - some other people have made scripts for dep graphs.
