### ISSUE TITLE
Node Authorisation Pallet does not connect nodes

### ISSUE THREAD

**Issue by stanly-sovereignnw** [substrate-developer-hub/substrate-developer-hub.github.io#763]
I followed the steps at https://substrate.dev/docs/en/tutorials/build-permission-network/add-node-authorization-pallet to create  two nodes but the two nodes are not connecting/recognising each other.

I was able to make them connect by using the `--bootnodes` flag and manually specifying the other node's `peer-id`

I was wondering if the tutorial missed specifying this flag or is my approach wrong?

**Comment by danforbes** [comment]
@kaichaosun are you able to help with this?

**Comment by stanly-sovereignnw** [comment]
Just an update, I figured that this approach will just connect with the other peer, not the entire network. So if I specify `--bootnodes <A>` and start two other nodes, these two nodes are connected to just peer A. So if peer A goes down, both the other nodes stop syncing. My understanding was that these two nodes should continue to create blocks. 

Can someone suggest where I am going wrong?

**Comment by kaichaosun** [comment]
Hi @stanly-sovereignnw, did you start both nodes in the same machine? If yes, both nodes should be able to find each other with mdns (a discovery mechanism for local network). If not, you need to configure bootnode or reserved node, it's probably not covered in the tutorial.
Also if same machine, discovery is not working, try restarting nodes.
Let me know if this works or not and what I missed in the tutorial.

**Comment by stanly-sovereignnw** [comment]
@kaichaosun I've been trying on the same machine itself with the local chain, but for some reason my nodes are not discovering each other. 

It works with `bootnode` flag only. My understanding is that assigning `bootnode` flag leads to dependency on that node, so if 3 nodes are connected with `--bootnode <node-A>` and `node-A` goes down, it stalls the network since the other 3 nodes are unable to connect to each other. How to get around this? Use multiple bootnodes?

**Comment by kaichaosun** [comment]
Did you try restart your nodes without `bootnode` flag?

**Comment by stanly-sovereignnw** [comment]
Yes, I tried that but didnt help, the nodes dont discover each other.
I've attached a screenshot of the `alice` and `bob` nodes, don't know if it helps.

<img width="1680" alt="Screenshot 2020-11-02 at 2 54 39 PM" src="https://user-images.githubusercontent.com/48114788/97851437-62922700-1d1b-11eb-9d2e-dd3e97e029d0.png">

**Comment by kaichaosun** [comment]
Do you mind share both commands that starts the node?
I will try later today and see if works.

**Comment by stanly-sovereignnw** [comment]
`./target/release/node-template --chain=local --base-path ~/tmp/validator1 --alice --node-key=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a --port 30333 --ws-port 9944`

`./target/release/node-template --chain=local --base-path ~/tmp/validator2 --bob --node-key=6ce3be907dbcabf20a9a5a60a712b4256a54196000a8ed4050d352bc113f8c58 --port 30334 --ws-port 9945`

Thanks

**Comment by kaichaosun** [comment]
I'm using the codebase: https://github.com/kaichaosun/substrate-permission-network
It works at my end with exact command you provided.
![image](https://user-images.githubusercontent.com/10568673/97858253-d511ff80-1d39-11eb-80dd-94ac1cb96f44.png)

**Comment by stanly-sovereignnw** [comment]
I tried it on a Linux VM now and it works as expected. The issue is with my MacOS permissions I guess, let me try to debug.
Thanks for the help.

**Comment by stanly-sovereignnw** [comment]
For anyone who is having the same issue on MacOS, turn off `Security&Privacy -> Firewall`, this will enable peer discovery on MacOS.
