### ISSUE TITLE
[New Tutorial] Advanced Runtime Upgrade + Storage Migration

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#766]
Create a new tutorial or add a new section to the existing tutorial on runtime upgrades. The new material should demonstrate the details of storage migrations as well as strategies for testing them.

Relates to #580 and #750.

**Comment by apopiak** [comment]
Minimum steps:
1. run original node template
2. change `Something get(fn something): Option<u32>;` storage to store `SomeStruct` (and define `SomeStruct`).
3. add storage migration function [like here](https://github.com/JesseAbram/demo_runtime_upgrade/blob/47fa0c321e8169c841d28a7b9fa06f9b91231b66/pallets/template/src/lib.rs#L120-L146) except putting it in a separate `migration` module and `migrate_to_struct` function. (might be missing some logging)
4. compile the new runtime and perform an upgrade

**Comment by apopiak** [comment]
We could also think about introducing tests. Like a unit test for the migration function. Or an integration test via Halva or the substrate-test-runner.

**Comment by NukeManDan** [comment]
Closing in favor of #939 to consolidate issues here. 

With respect to unit tests, we may be able to solve #638 with this one as well...?
