### ISSUE TITLE
Update off-chain workers section in main doc to reflect current Substrate v3

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#776]
https://substrate.dev/docs/en/knowledgebase/runtime/off-chain-workers

**Comment by NukeManDan** [comment]
@jimmychu0807 this is stale? Should it be closed? IIRC #901 also deprecates this for now?
A new tracking issue to have offchain workers may be needed, if you see fit.

**Comment by jimmychu0807** [comment]
Actually this is a task need to be done. I will just continue to keep this issue(task) here.

**Comment by jimmychu0807** [comment]
The doc is removed, and I think ocw examples can be better referenced in Substrate Recipe.
Done in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/995
