### ISSUE TITLE
Have an index page showing all previous Substrate Seminars 

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#788]
- with tagging & filtering

**Comment by NukeManDan** [comment]
I think @sacha-l is doing this manually for now, but it's not searchable with tags and filters... yet anyway 😁
Should we ping the design team on this to have some kind of gallery to peruse previous talks? 
Maybe the substrate marketplace that Steve is working on? https://marketplace-staging.substrate.dev/
