### ISSUE TITLE
Update private network tutorial to use key subcommand

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#791]
Polkadot has a subcommand to insert keys into the keystore without having to start the node first. This eliminates the nastiness around restarting nodes after inserting grandpa keys https://github.com/paritytech/substrate/issues/7268#issuecomment-737491349

The private network tutorial should be updated accordingly.

**Comment by danforbes** [comment]
It doesn't look like this subcommand is in the Node Template yet.

**Comment by JoshOrndorff** [comment]
Seems like a nice one to have. I wonder if it's in the `bin/node`?

**Comment by evgeny-s** [comment]
Is it possible to add keys with some other approach besides CURL and Polkadot UI? I have this issue #794. Maybe you guys take a look at it and give some advice. Thanks!

**Comment by danforbes** [comment]
Yes, you can also use Subkey https://substrate.dev/docs/en/knowledgebase/integrate/subkey#inserting-keys-to-a-nodes-keystore

**Comment by korzewski** [comment]
Hi @danforbes,
It seems that this section "subkey insert" is not valid anymore -> based on this PR https://github.com/paritytech/substrate/pull/7775

Outdated docs: https://substrate.dev/docs/en/knowledgebase/integrate/subkey#inserting-keys-to-a-nodes-keystore

**Comment by evgeny-s** [comment]
This can be closed. Fixed by adding `--rpc-external` parameter to the run script

**Comment by JoshOrndorff** [comment]
This issue was not about @evgeny-s's question. It recommends an improvement to a tutorial, and that improvement has not yet been made. If you want to close it as out-of-scope of something, that's fine, but it is not done

**Comment by evgeny-s** [comment]
Yes, agree! My fault.
