### ISSUE TITLE
Add note about runtime <> metadata correspondence

### ISSUE THREAD

**Issue by joepetrowski** [substrate-developer-hub/substrate-developer-hub.github.io#797]
I've had a few wallet teams ask if they need to fetch the (rather large) metadata every time they make a transaction. Can we add a note to the metadata documentation page that the metadata corresponds to a runtime spec number? It should clarify that:

- Spec version => unique metadata
- Transaction version => unique call mapping

**Comment by jimmychu0807** [comment]
@joepetrowski will work on this coming week

**Comment by jimmychu0807** [comment]
@joepetrowski  So we have this [runtime version structure](https://github.com/substrate-developer-hub/substrate-node-template/blob/master/runtime/src/lib.rs#L94-L102) in our runtime

```rust
pub const VERSION: RuntimeVersion = RuntimeVersion {
	spec_name: create_runtime_str!("node-template"),
	impl_name: create_runtime_str!("node-template"),
	authoring_version: 1,
	spec_version: 1,
	impl_version: 1,
	apis: RUNTIME_API_VERSIONS,
	transaction_version: 1,
};
```

- you are saying users can first check the `spec_version`. If the `spec_version` hasn't changed, then they can assume the pallet function signatures (and thus the chain metadata) hasn't been changed, and they can just submit extrinsics as they know of. If the spec version has incremented, they should query the metadata again to get the latest pallet APIs. Am I understanding you correctly?
- `impl_version` is incremented if runtime code logic, but not the function signature, has changed. So this does not change the metadata as well. Right?
- when is `transaction_version` got incremented?
- How can I query this runtime version structure outside of the chain? The closest I seem to get is submitting an RPC call of `system_version()`. But it is returning the string `2.0.0-unknown-x86_64-linux-gnu` only. Not the whole `RuntimeVersion` structure.

Thanks.

**Comment by joepetrowski** [comment]
1. Correct. Metadata is generated deterministically from the runtime Wasm. So if there is a new runtime, then you should assume that there's new metadata. Likewise, if the runtime `spec_version` hasn't changed then the metadata should not have changed. There is an edge case where a chain really fucks up and pushes a runtime upgrade without incrementing `spec_version`, but there are lots of checks in the upgrade code that make it really hard to make that mistake.
2. Correct, `impl_version` would not actually change the spec or runtime version. It's not something to worry about in the context of this issue, because the chain only checks `spec_version` when it's deciding which code to execute (Wasm or native). Whatever is on-chain is the canonical implementation.
3. `transaction_version` increments whenever there is a breaking change to the transaction format. A lot of signers (like Ledger) can't pass the entire metadata over the wire because of memory limitations, so they hardcode in a mapping of indices to function calls, like `pallet 07, call 04 == balances.transfer` and then the types needed to parse that call. So if you add a new function _before_ call 04 or changed the signature (type change, extra param) then the signer wouldn't be able to parse it properly. Note that new functions can be added to _the ends_ of pallets, or new pallets to the end of `construct_runtime` because those only add new indices, but if anything breaks existing indices then `transaction_version` needs an increase.
4. I'm not sure if you can get the entire struct outside the chain, but you can definitely get `spec` and `transaction` versions. It looks like [this RPC call](https://github.com/paritytech/substrate-api-sidecar/blob/a8387dfbbcc8ce3df68a7768643e1a5e2202148e/src/services/transaction/TransactionMaterialService.ts#L23) gets both (and maybe includes more?). See L35-37 too.

**Comment by jimmychu0807** [comment]
Re 4), indeed there is an RPC call `state.getRuntimeVersion()` and returning the following struct:

```js
{
  specName: node-template,
  implName: node-template,
  authoringVersion: 1,
  specVersion: 1,
  implVersion: 1,
  apis: [
    [
      0xdf6acb689907609b,
      3
    ],
    [
      0x37e397fc7c91f5e4,
      1
    ],
    [
      0x40fe3ad401f8959a,
      4
    ],
    [
      0xd2bc9897eed08f15,
      2
    ],
    [
      0xf78b278be53f454c,
      2
    ],
    [
      0xdd718d5cc53262d4,
      1
    ],
    [
      0xab3c0572291feb8b,
      1
    ],
    [
      0xed99c5acb25eedf5,
      2
    ],
    [
      0xbc9d89904f5b923f,
      1
    ],
    [
      0x37c8bb1350a9a2a8,
      1
    ]
  ],
  transactionVersion: 1
}
```
Thanks.
