### ISSUE TITLE
Developer Hub Landing Page

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#80]
Gotta have the best landing page of all time.

**Comment by JoshOrndorff** [comment]
@shawntabrizi has been making good progress on this for example 61ee78612135f4e58a34d1d8c6df0fd50c570b89

Preview at https://substrate-developer-hub.github.io/docs/ (This URL will likely change because of https://github.com/substrate-developer-hub/docs/issues/96)

**Comment by JoshOrndorff** [comment]
Could use a favicon. This is the old one https://files.readme.io/1b958ee-favicon.ico from readme_io

**Comment by JoshOrndorff** [comment]
Any thoughts on what to do with this currently-empty page? substrate-developer-hub.github.io/docs

One idea is to just delete that page, and have docs start with the quickstart.

**Comment by shawntabrizi** [comment]
Should be the landing page for docs no?
https://reactjs.org/docs/

Maybe I misunderstand what you mean

**Comment by JoshOrndorff** [comment]
I think launching the live docusaurus site means this ready to be closed. Awesome work @shawntabrizi 

Changes or corrections are welcome in new issues or as PRs.
