### ISSUE TITLE
FRAME Pallet Links Point to master Instead of Released Tags

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-developer-hub.github.io#818]
@al3mart pointed out that the "Source" links for the pallets on this page https://substrate.dev/docs/en/knowledgebase/runtime/frame point to master as opposed to v2.0.0 like the Rustdoc links.

**Comment by al3mart** [comment]
I will create a new branch for changing this link, and also any other one pointing to outdated source.

I am going to use v2.0.0, as I am not completely sure if v2.0.1 is going to get some iterations. Even though I don't think they change any existing pallet (who knows ?)

**Comment by danforbes** [comment]
Closing with #821. Thank you so much @al3mart! FYI - the _entire_ substrate.dev website is on v2.0.0, so using that version was the right choice. At some point, we will probably move everything including the Node Template etc to the newly released version.
