### ISSUE TITLE
Document the subkey tool

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#85]
I've written a draft at https://dash.readme.io/project/substrate/v1.0.0/docs/keys-seeds-and-the-subkey-tool

Would love initial feedback about what to add or remove, corrections, or anything. When the content looks good, I'll record a video walk-through.

**Comment by folsen** [comment]
@JoshOrndorff I would suggest looking up through git blame or history who wrote most of the code for subkey and ping them directly here, otherwise you might not get the attention necessary.

**Comment by ltfschoen** [comment]
@JoshOrndorff i've suggested changes to https://dash.readme.io/project/substrate/v1.0.0/docs/keys-seeds-and-the-subkey-tool. just click "View Doc History" then "View Diff" to see the proposed changes. if you don't like the suggested changes then just click the "Revert" button to revert to previous versions (although I haven't played around with the VCS of Readme.io enough to know whether/how we'd still have access to the suggested changes if you revert them and then want to unrevert them again).

**Comment by ltfschoen** [comment]
@JoshOrndorff suggest linking SS58 to https://github.com/substrate-developer-hub/docs/issues/90 once @joepetrowski has completed that task

**Comment by JoshOrndorff** [comment]
Thanks @ltfschoen I appreciate the edits (including digging up the bip39 link!).

Looks like Gav wrote most of the code (https://github.com/paritytech/substrate/blame/master/subkey/src/main.rs). I'll finish this first draft and then ping him.

**Comment by ltfschoen** [comment]
@JoshOrndorff also might be worth getting in touch with Logan at Web3 to make sure it's in sync with the Web3 wiki

**Comment by ltfschoen** [comment]
@JoshOrndorff also might be worth incorporating this script https://github.com/luboremo/Edgeware-seed-generating-script-SSSS, which was shared in https://discordapp.com/channels/537281916567814144/545028376889393152 by @luberemo

**Comment by JoshOrndorff** [comment]
I've decided the doc I wrote and Luke revised was helpful enough to be published at https://docs.substrate.dev/docs/keys-seeds-and-the-subkey-tool

@gavofyork since you wrote most of subkey, could you please take a look for correctness or suggestions? I'd love to write more about sign and transfer too, but could not figure out the formats necessary for input keys/addresses, or where to use the signed output.

**Comment by JoshOrndorff** [comment]
Edgeware write-up that uses some derivation paths https://blog.edgewa.re/edgeware-lockdrop-for-validators/

From Rob on derivation paths:
> My (possibly incorrect) understanding is that we make a distinction between soft/hard derived keypairs. All derived keypairs are made by combining and original key with a derivation path. A hard derivation means that the derived public key will be unpredictable to someone who knows the initial public key but not the initial private key. A soft derivation allows you to predict what the derived public key will be, using the original public key and the derivation path, but without leaking any info about the derived private key.

**Comment by JoshOrndorff** [comment]
@ltfschoen I've moved the info you added about session keys to  a [new article](https://substrate.dev/docs/en/overview/session-keys).

I feel like it needs a little context at the beginning. Where might one have heard of session keys that would have gotten them reading that article?

@rphmeier I've confirmed your assertion about the difference between [hard and soft derivation paths](https://substrate.dev/docs/en/ecosystem/subkey#derivation-paths), and observed that soft paths don't work with Ed25519 keys. Thanks for sharing that tidbit. Very interesting.

I'm satisfied with this article so I'll close the issue. Please open a new issue if you'd like to add info about `subkey`'s transaction signing capabilities.

**Comment by ltfschoen** [comment]
@JoshOrdorff ,suggest adding context at the start of the article that provides a link to the Session SRML module, the W3F wiki (where i got that info in the beginning). i write that concise summary and added it to the Subkey article to provide more context to readers

**Comment by JoshOrndorff** [comment]
@ltfschoen The reason I moved it is because subkey deals with individual key-pairs even in ed25519, `-e`, mode. I hadn't encountered the idea of certificates before.

It looks like https://wiki.polkadot.network/en/latest/polkadot/learn/keys/#session-key might be the original source you mentioned?

That page contains a disclaimer
> Currently as implemented in Polkadot / Substrate, the session key is just a normal ed25519 key and the following information has not been implemented. It is written here for educational purposes as a notice for what's to come.
