### ISSUE TITLE
substrate dev docs dead link

### ISSUE THREAD

**Issue by pkrasam** [substrate-developer-hub/substrate-developer-hub.github.io#854]
For some reason this URL is leading to a 404

Most likely it is a dead link

[substrate dev docs dead link](https://substrate.dev/docs/en/tutorials/start-a-private-network/Specifically)

**Comment by jimmychu0807** [comment]
Could you point to which article containing the dead link?

**Comment by NukeManDan** [comment]
@pkrasam here is what you likely want: https://substrate.dev/docs/en/tutorials/start-a-private-network/
where did you find this dead link? I can't find this in the devhub, and we have CI to check for these, so it must be external to our docs.
