### ISSUE TITLE
Error when installing Subkey

### ISSUE THREAD

**Issue by centrifugenoder** [substrate-developer-hub/substrate-developer-hub.github.io#862]
Hey,
I am new to substrate and programming and I am constantly running into the same error when trying installing subkey to generate some keys for a node. I have tried to install subkey following the step in the Substrate Developer Hub but I am not being able to complete the installation. The error is the following:
error[E0034]: multiple applicable items in scope
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:51:25
    |
51  |     const MASK: u8 = Self::BITS - 1;
    |                            ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:44:2
    |
44  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `IsNumber`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
51  |     const MASK: u8 = BitMemory::BITS - 1;
    |                      ^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
51  |     const MASK: u8 = IsNumber::BITS - 1;
    |                      ^^^^^^^^^^^^^^

error[E0034]: multiple applicable items in scope
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/order.rs:291:15
    |
291 |         if ct == R::BITS {
    |                     ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:44:2
    |
44  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `IsNumber`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
291 |         if ct == BitMemory::BITS {
    |                  ^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
291 |         if ct == IsNumber::BITS {
    |                  ^^^^^^^^^^^^^^

error[E0034]: multiple applicable items in scope
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/order.rs:339:15
    |
339 |         if ct == R::BITS {
    |                     ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:44:2
    |
44  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `IsNumber`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
339 |         if ct == BitMemory::BITS {
    |                  ^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
339 |         if ct == IsNumber::BITS {
    |                  ^^^^^^^^^^^^^^

error[E0034]: multiple applicable items in scope
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/order.rs:450:19
    |
450 |     for n in 0 .. R::BITS {
    |                      ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:44:2
    |
44  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `IsNumber`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
450 |     for n in 0 .. BitMemory::BITS {
    |                   ^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
450 |     for n in 0 .. IsNumber::BITS {
    |                   ^^^^^^^^^^^^^^

error[E0034]: multiple applicable items in scope
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/order.rs:469:21
    |
469 |             pos.value() < R::BITS,
    |                              ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:44:2
    |
44  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `IsNumber`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
469 |             pos.value() < BitMemory::BITS,
    |                           ^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
469 |             pos.value() < IsNumber::BITS,
    |                           ^^^^^^^^^^^^^^

error[E0034]: multiple applicable items in scope
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/order.rs:476:7
    |
476 |             R::BITS,
    |                ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:44:2
    |
44  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `IsNumber`
   --> /home/centifuge/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
476 |             BitMemory::BITS,
    |             ^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
476 |             IsNumber::BITS,
    |             ^^^^^^^^^^^^^^

error: aborting due to 60 previous errors

**Some errors have detailed explanations: E0034, E0308.**
For more information about an error, try `rustc --explain E0034`.
error: failed to compile `subkey v2.0.0 (https://github.com/paritytech/substrate#e03ca38d)`, intermediate artifacts can be found at `/tmp/cargo-installkvO14R`

Caused by:
  could not compile **`bitvec`**

****
Thank you for the help :).

**Comment by NukeManDan** [comment]
This was an issue cause by `funty` issues upstream that should now be resolved. Try again with https://substrate.dev/docs/en/knowledgebase/integrate/subkey instructions
