### ISSUE TITLE
Adding instructions on compiling Substrate on Mac M1 chip

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#867]
A few comments has been seen in our Element technical channel on how to run Substrate on Mac M1 chip. Let's add a section [here](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/knowledgebase/getting-started/index.md) (will be shown [here](https://substrate.dev/docs/en/knowledgebase/getting-started/) finally) on how to make Substrate run on Mac M1 chip.

@hammewang Could you help? Thanks.

**Comment by hammeWang** [comment]
@jimmychu0807 Of course. Since lots of changes in the latest substrate, it will take me some time.

**Comment by NukeManDan** [comment]
This blog seems to outline a solution that works for most people. Although I have been telling people that really it's a pain and if possible, do not use M1 ARM for builds/running substrate until upstream rust deps get stable for use on them. 

https://vikiival.medium.com/run-substrate-on-apple-m1-a2699743fae8

**Comment by NukeManDan** [comment]
updated instructions here: https://github.com/substrate-developer-hub/substrate-node-template/issues/179#issuecomment-843522331
