### ISSUE TITLE
confusion about smart ink contracts

### ISSUE THREAD

**Issue by tansaku** [substrate-developer-hub/substrate-developer-hub.github.io#876]
Thanks for all the great resources.  I completed the adding a smart contract pallet, and then followed the instructions to learn about smart ink at https://substrate.dev/docs/en/knowledgebase/smart-contracts/ and then in https://substrate.dev/substrate-contracts-workshop/#/0/introduction

There I got a bit confused as I was trying to run the canvas front end against the subtrate backend that I had upgraded for contracts in https://substrate.dev/docs/en/tutorials/add-contracts-pallet/

Receiving help from the smart ink folk https://github.com/paritytech/canvas-ui/issues/67 I got the smart ink contract working in canvas, but now I'm back to seeing it I can get a contact running on my upgraded substrate node.  Unlike canvas which accepts a contract json file, the substrate node only has the option to add an encoded chunk of code:

![Screenshot 2021-03-04 at 12 21 25](https://user-images.githubusercontent.com/30216/109963915-df8ed680-7ce4-11eb-83ce-eb1d368a7409.png)

Do I extract the encoded code from the basic flipper contract and put that?  Is there a tutorial on that part or it's just something we need to work out for ourselves?

I think I just successfully uploaded the contract (via a signed operation?), but am now unclear about calling it - not sure what should go in each of the fields offered:

![Screenshot 2021-03-04 at 12 42 05](https://user-images.githubusercontent.com/30216/109965617-1e259080-7ce7-11eb-813f-41222ba9d1c3.png)

Am trying to work out which of the items that are pre-filled in https://substrate.dev/substrate-contracts-workshop/#/0/calling-your-contract?id=get are the ones to put in where ...

**Comment by J-Cook-jr** [comment]
You're asking great questions man! I hope you get an answer because this is no joke confusing. There are so many different versions, docs and repos on all of this and I keep going into rabbit hole after rabbit hole. I'm kind of getting information paralysis over here. I just need a solid, straight forward tutorial to follow to make this a smoother experience. 

I can see that you're kind of where I am as far as following along with the docs. I'm confused about the compatibility of ink with substrate. After running into errors using the "most up to date version of the substrate node", I started over and followed the docs on substrate.dev using node-template v2.0.1. I successfully imported and built the contracts pallet using v2.0.1, even though the tutorial recommended building with v3.0.0. Now I'm working on the ink smart contracts tutorials and I'm not sure if I should be using v0.7.0 or v0.8.0... Also, ink v3.0 is being thrown around but the git repo says the latest version is v2.0.1. If you've found any more solutions since posting this issue, please let me know. Thanks and Good luck!

**Comment by jimmychu0807** [comment]
@tansaku @J-Cook-jr thanks for reporting/sharing your confusion. Let me repeat your step above this week and get back to you.

**Comment by tansaku** [comment]
thanks @jimmychu0807 - much appreciated.

@J-Cook-jr glad it's not just me that gets stuck sometimes :-) The key thing that's helping me at the moment is understanding that substrate and canvas are two different systems.  Similar, but different.  And it seems the ink tutorial is all based around canvas, so I'm going to focus on completing the ink tutorial with canvas, and then come back to substrate when I'm finished there.

**Comment by tansaku** [comment]
So I got a bit further into the smart contract tutorial and now have a slightly more complex "incrementer" smart contract which works fine on canvas, and I have also successfully uploaded to my local substrate node using the signed putCode option and grabbing the wasm from the incrementer.contract file.

So I thought I'd have a go at trying to call it:

![Screenshot 2021-03-19 at 11 43 37](https://user-images.githubusercontent.com/30216/111775256-6c6e8e00-88a8-11eb-9e0a-d3764cd57f3e.png)

in the history here you can see the successful upload.  I'm trying randomly to specify the address of the user I uploaded the contract as as the destination and trying to call a fee not required `get` operation.  This leads to the error shown.  I'm guessing that the `data` field needs to be the wasm encoded version of `incrementer::get` maybe?  or it should be blank and the `dest` field needs to be that?

I've just been back through instantiating and executing the incrementer contract on canvas - here's some suggestive screenshots

![Screenshot 2021-03-19 at 11 47 59](https://user-images.githubusercontent.com/30216/111775966-57462f00-88a9-11eb-9db2-b155888cbe46.png)

![Screenshot 2021-03-19 at 11 48 15](https://user-images.githubusercontent.com/30216/111775990-5f9e6a00-88a9-11eb-8923-fd668b0f485a.png)

![Screenshot 2021-03-19 at 11 51 12](https://user-images.githubusercontent.com/30216/111776029-6cbb5900-88a9-11eb-916e-643c812b2892.png)

which makes me think that perhaps the first call needs to be an instantiation call?  I see a data element there.   I was trying to see if I could see the get request in the canvas node go over the wire in the network tab in the browser so I could see what format the request was sent to the node in, but there was nothing there, and no immediate logging on the server.

I guess I will move on to other substrate tutorials and come back to this when I've learnt more about debugging and analysing these things ...

**Comment by NukeManDan** [comment]
@tansaku - this is a very stale question, I hope that it's OK to close it and that you solved your problems around it. If not, I am happy to bring this back up with the `ink!` experts 😁
