### ISSUE TITLE
Review & update Tutorial: Create Your First Substrate Chain to v3 compatible

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#881]
https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/

**Comment by riusricardo** [comment]
@jimmychu0807 what is the status of this? It is important to prioritize it because all the other tutorials depend on it.

**Comment by NukeManDan** [comment]
Happy to help if needed - tag me in anytime 😁

**Comment by riusricardo** [comment]
@NukeManDan please feel free to take this. There are events coming on different fronts and we need to push this forward.
