### ISSUE TITLE
Review & update Tutorial: Build a PoE Decentralized Application to v3 compatible

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#883]
https://substrate.dev/docs/en/tutorials/build-a-dapp/

**Comment by sacha-l** [comment]
Most updates have been made. The remaining update needed is the screenshot ``/tutorials/build-a-dapp/front-end-template.png`` showing the version of Substrate used. Need to test it out and take new screenshot.

**Comment by NukeManDan** [comment]
notice this:
Resolving this one will close https://github.com/substrate-developer-hub/substrate-front-end-template/issues/161

**Comment by NukeManDan** [comment]
also reporting this to the design team to fix: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/909

**Comment by NukeManDan** [comment]
Hey @sacha-l any updates on progress here? 😁

**Comment by sacha-l** [comment]
> Hey @sacha-l any updates on progress here?

Thanks for the ping Dan, on it!

**Comment by NukeManDan** [comment]
Closed in #954 - thanks for the work @sacha-l !
