### ISSUE TITLE
Remove TODO in Executor

### ISSUE THREAD

**Issue by kianenigma** [substrate-developer-hub/substrate-developer-hub.github.io#903]
This page is pretty old I think, and there's a leftover TODO in it. 

https://substrate.dev/docs/en/knowledgebase/advanced/executor

**Comment by jimmychu0807** [comment]
@kianenigma would you suggest we just remove the word "TODO" (that there is still some values in displaying the page), or removing the whole page altogether?

**Comment by kianenigma** [comment]
Ideally we should add an example, else remove the section, not the whole page. 

I think https://github.com/paritytech/substrate/blob/3adefdcea47a26c4904651e108129fd6b6ce132a/client/api/src/execution_extensions.rs#L42 is a good example: The default execution strategies that are used in substrate-node for different actions.

**Comment by kianenigma** [comment]
also: https://github.com/paritytech/substrate/blob/6ac86d545f6da8e4afc373dc0876c3e7ba79e51b/client/cli/src/arg_enums.rs#L208

**Comment by jimmychu0807** [comment]
@kianenigma please review the PR: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/922. Thanks 🙏
