### ISSUE TITLE
Provide examples throughout for Substrate v3

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#906]
The https://github.com/substrate-developer-hub/substrate-node-template lists branches with solutions for the tutorials, we should clean these and link to the correct branches in all tutorials for those looking (at the end of the tutorial?)  

Why? so we have a know build-able source to confirm that those looking can compare to and troubleshoot against.

**Comment by riusricardo** [comment]
I agree, but lets do review on a case-by case basis. Many of those branches are reference to videos so they could still teach something and may only need a small update to the readme. Many others could be removed.

**Comment by NukeManDan** [comment]
Closing in favor of a newer model to use patch files and CI to try and merge into node template releases for all templates. :soon:
