### ISSUE TITLE
Runtime picture have an error

### ISSUE THREAD

**Issue by yunweb** [substrate-developer-hub/substrate-developer-hub.github.io#909]
https://substrate.dev/docs/en/knowledgebase/runtime/
![image](https://user-images.githubusercontent.com/13432688/111115980-4f804500-85a0-11eb-8357-e3f5cf642f6e.png)

one is elections, other is elections phragmen?

**Comment by NukeManDan** [comment]
This image also appears here: https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet and possible in other places in the devhub. 😬

**Comment by NukeManDan** [comment]
We still need a specific request on how to update this @sacha-l , do you have a vision in mind for how this could be improved and "future proofed"? We can pass that to Dan M.

**Comment by sacha-l** [comment]
Apologies - this slipped. We just need a clean png of it. The latest version is a hack I did with Inkscape, it looks fine but you can tell it's not transparent if you open the standalone file. I'll ask Dan M to have a look.
