### ISSUE TITLE
Create docs for reclaiming an index

### ISSUE THREAD

**Issue by joepetrowski** [substrate-developer-hub/substrate-developer-hub.github.io#91]
Related to deprecation of the wiki
https://github.com/paritytech/wiki/pull/335

Old:

To reclaim an index `I`, you must be sure that `I` is currently mapped to a dead account (i.e. one with zero total balance). You need to craft a transaction that creates a new account by placing some balance `B` in it. `B` must satisfy these conditions:

 `B % 256 == 105`

 `B / 256 % E == I`	

 Where `E` is the quantized account index count:	

 `E := (next_set_index * enum_set_size / 256 + 1) * 256`	

 Given an amount to transfer `A`, you can calculate the lowest amount that is at least `A`, `A'` which will attempt to reclaim `I` as:	

 `(Q(N / 256 + (E - 1 - I), E) + I) * 256 + N % 256`	

 Where	

 `N := Q(A + (256 - 1 - 105), 256) + 105`

**Comment by joepetrowski** [comment]
Could potentially just live with the Indices module reference docs

**Comment by JoshOrndorff** [comment]
I'm in favor of this living with the reference docs. Or if it is to live on its own, it needs a lot more context. For example, what is an index and why should I care?

**Comment by joepetrowski** [comment]
> I'm in favor of this living with the reference docs. Or if it is to live on its own, it needs a lot more context. For example, what is an index and why should I care?

Agree, should just be included in the docs with `srml/indices`.

**Comment by JoshOrndorff** [comment]
The indicies module does not yet include _any_ reference docs. Given that maintenance of reference docs was handed off to core dev team, I've opened https://github.com/paritytech/substrate/issues/2989

**Comment by shawntabrizi** [comment]
@JoshOrndorff I think maintenance is handed off to the core dev team, but we are still on the hook for doing the first draft and getting it reviewed and merged in. But that could be different depending on who you ask so... ¯\\_(ツ)_/¯
