### ISSUE TITLE
Mention the Enterprise Sample? {Needs to be updated for v3}

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#913]
https://github.com/substrate-developer-hub/substrate-enterprise-sample/issues/73 

This issue prompted me to notice that we don't have this on the devhub (not sure how I was able to find this before TBH... maybe https://substrate.dev/awesome-substrate/ ... I think is it the referenced [crowdcast](https://www.crowdcast.io/e/substrate-seminar/6) for this, also on youtube AFAIK)

### Should the enterprise sample be added into a tutorial of it's own? Or at least referenced in devhub? 

If so, it will need to be updated

**Comment by riusricardo** [comment]
Nope, the sample requires a big update to many repos from different users. It isn't designed as a tutorial and should only be used as an example.

Where do you think that we could reference to it? I don't see any section for this. IMO AwesomeSubstrate could be a better fit.

**Comment by NukeManDan** [comment]
Motion to move to archive (for now  at least) : https://github.com/substrate-developer-hub/substrate-enterprise-sample/pull/89
