### ISSUE TITLE
[WIP] New Benchmarking Tutorial

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#914]
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/879

I see that this _should_ have been published, but:

https://substrate.dev/docs/en/tutorials/runtime-benchmarking/

shows a blank page 😬 
@jimmychu0807 can you see what was wrong in the PR deployment that didn't catch this? In #912 I needed to get links working via gihub CI checks (locally was fine) before it actually pushed the live version

**Comment by jimmychu0807** [comment]
I think this is right. I haven't completed the tutorial and just put a placeholder there. I should hide it at first and show it when it is completed. The published [runtime benchmarking page is here](https://substrate.dev/docs/en/knowledgebase/runtime/benchmarking).

**Comment by NukeManDan** [comment]
#917 for now, as you see fit @jimmychu0807 open a draft PR linked to close this issue? 🙏🏼

**Comment by jimmychu0807** [comment]
I think to close this issue, I need to actually write the benchmarking tutorial using the node template.

**Comment by NukeManDan** [comment]
Migrating to https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/914
