### ISSUE TITLE
Javascript fetch metadata instruction outdated

### ISSUE THREAD

**Issue by Slesarew** [substrate-developer-hub/substrate-developer-hub.github.io#916]
This file:

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/knowledgebase/runtime/metadata.md

contains instruction how to fetch metadata through https://polkadot.js.org/apps/#/js that result in error. https://polkadot.js.org/apps/#/js itself has a working metadata fetch example that could be referenced instead unless the idea behind this manual is different.

**Comment by NukeManDan** [comment]
@Slesarew thanks for the report! 😁 
Can you provide a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) of the issue you ran into? Then we can fix it appropriately.

For reference, where do you see instructions on the Apps UI that we should point out? This feature (not documented explicitly on the UI AFAIK)?

![image](https://user-images.githubusercontent.com/35669742/111517448-b0cc2380-871a-11eb-80af-f3a84fcbeff5.png)

**Comment by Slesarew** [comment]
This instruction:

![image](https://user-images.githubusercontent.com/33295157/111588712-96528280-87cc-11eb-8793-194811bc0a35.png)

Copied verbatim into web UI linked from the same place (just copy the code, click on Substrate UI link, select all and paste):

![image](https://user-images.githubusercontent.com/33295157/111588826-baae5f00-87cc-11eb-94a2-20f2a45fc173.png)

Results in error. Instead, always up-to-date test is available at the top of that UI page (and is loaded by default when you click the link above I think, didn't test in fresh profile though):

![image](https://user-images.githubusercontent.com/33295157/111588987-f47f6580-87cc-11eb-9ddc-3473cd148738.png)

It doesn't show magic number, though, which is kind of important for the manual below.

**Comment by jimmychu0807** [comment]
@Slesarew Thanks for reporting. Indeed. The correct code is:

```javascript
const { magicNumber, _metadata } = await api.rpc.state.getMetadata();

console.log("Magic number: " + magicNumber);
console.log("Metadata: " + _metadata);
```
