### ISSUE TITLE
error[E0463]: can't find crate for `std`

### ISSUE THREAD

**Issue by spindriftur** [substrate-developer-hub/substrate-developer-hub.github.io#929]
got an error and the build failed for substrate
<img width="666" alt="Screen Shot 2021-03-22 at 10 04 00 PM" src="https://user-images.githubusercontent.com/49564726/112081773-9fd84380-8b5a-11eb-9d9a-9d8f8c174b60.png">

**Comment by NukeManDan** [comment]
Hey did you _read_ the message? 😉 

You need to install the right toolchain: https://substrate.dev/docs/en/knowledgebase/getting-started/
