### ISSUE TITLE
Improvement to "Installation" instructions

### ISSUE THREAD

**Issue by DavidSSL** [substrate-developer-hub/substrate-developer-hub.github.io#934]
So some background. I have only started with Rust at the beginning of this month and I got interested in blockchains last Sunday. Therefore that might explain why I had difficulty following the instructions on the [installation steps](https://substrate.dev/docs/en/knowledgebase/getting-started/) page.

Now the problems I had are more related to Rustup but regardless of this fact, the documentation might need some reworking in my opinion.

There is a section related to installing Rustup where we are told to run:

```console
source ~/.cargo/env
```
I didn't install Rustup via the shell script but instead used the Arch community package and as result, I didn't have the `env` file. 

However, it didn't seem to matter really as I was eventually able to go through the [creation of Substrate chain tutorial](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/) without any issues. I agree that yes it's my fault for not following the instructions to the letter but maybe this issue can be highlighted for people who installed Rustup the way I did. 

While the previous issue was my fault, the section about the [toolchain](https://substrate.dev/docs/en/knowledgebase/getting-started/#rust-nightly-toolchain) really slowed me down as I wasn't sure what to do because, Polkadot was mentioned while I was interested in Substrate. I simply ploughed ahead and installed the latest nightly toolchain and I had no problem going through the above referenced tutorial. This might well be due to my lack of understanding about the whole Rust ecosystem but I recall reading that knowledge of Rust would not be required for that tutorial.

Now, I would be happy to help rewrite that part of the documentation as long as it is deemed to be necessary/desirable and also if I can get some degree of support either from here or in Matrix. 

Just my 2 cents as they say...

**Comment by NukeManDan** [comment]
Thanks for the feedback @DavidSSL - I would be happy to review a PR on this to improve the docs. 
- IIUC the env file is just to get the $PATH variable updated:
```shell
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac
```
So including a note about that for other distros could be good.

2. RE: Polkadot mentioned, it is built with substrate, and as a best practice for people actually using the template for a production product like it, it is very important to set a known good toolchain. What would you suggest (in your PR) to make that more clear?

**Comment by DavidSSL** [comment]
Hey @NukeManDan, the "env" part is clear for non ArchLinux other environments. I will need to spend some time on another machine in order to be able to update the documentation properly on this one. 

As for Polkadot, I think I have to elaborate on the workflow. 

I wanted to simply run the tutorial mentioned above as a result of which I am redirected to the installation page we're currently discussing. 

Then you go through the process of:

- Installing Rustup
- Installing a given nightly toolchain

At this point I am introduced to 2 things:
1. Rustup's nightly build
2. Polkadot. 

Now from the point of view from someone who doesn't know much about 
- Rust and its ecosystem
- Parity and its products

I get totally puzzled because all I want to do is to be able to run the tutorial which doesn't involve Polkadot.

So what goes through my mind is the fact that ok, I now need to find some date for the nightly version of Rustup when it comes to *Substrate*. I failed to make the connection between *Polkadot* and *Substrate* which you've mentioned above. However, looking at the [latest version of *Polkadot*](https://github.com/paritytech/polkadot/releases/tag/v0.8.29), I see three different dates and I don't really know what to do. 

Now my assumption is that it is possible that from some Polkadot tutorials, we get redirected to this installation page and hence why this information about nightly Rustup is important in this case.

Let me create a PR which I'll send and you can guide me better.
