### ISSUE TITLE
Enhance Transaction Weight and Transaction Fee article

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#946]
- https://substrate.dev/docs/en/knowledgebase/learn-substrate/weight
- https://substrate.dev/docs/en/knowledgebase/runtime/fees

Todo:
- Put these two articles next to each other in the sidebar.
- Move some of the weight stuff from **Fees** article back to **Weight** article.

**Comment by NukeManDan** [comment]
Would it also be important to talk more about benchmarking in this context? and cross link to the page on it https://substrate.dev/docs/en/knowledgebase/runtime/benchmarking

As this is especially critical in the parachain context!
