### ISSUE TITLE
Update Create a Pallet Tutorial FRAME v2

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#947]
https://substrate.dev/docs/en/tutorials/create-a-pallet/

Based on https://github.com/substrate-developer-hub/substrate-node-template/pull/160 landing from @jimmychu0807 - there will be a new tag to use for this tutorial (if not all tutorials?) for the node template to build from.

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-pallet-template was archived (by me) as it wasn't being maintained in the context of the rest of the devhub updates. Should this be amended or removed from the tutorial? @sacha-l @jimmychu0807 what do you think? 

I would suggest instead we just use the template pallet that exists within the substrate node, and mention that it is a sub-crate, so the entire `pallets/template` directory could be moved into it's own repo, much like the https://github.com/open-web3-stack/open-runtime-module-library does (and we get the chance to give that lib a shout out 😁  )

**Comment by jimmychu0807** [comment]
I support that we archive the substrate-pallet-template. 

The content of the tutorial does worth mentioning: on how to publish a pallet as crate in github or crate.io, and how other runtimes can reuse that pallet. I also agree that we can make the template pallet as the target pallet we want to publish.

I wonder where should we put these content in. One place is putting it in Substrate node template readme (or part of the doc somewhere in node template).

**Comment by jimmychu0807** [comment]
People seems to be using this tutorial. [See here](https://stackoverflow.com/questions/68254008/error-when-cargo-build-node-templare-with-pallet-in-its-own-crate/68254658#68254658), we should either update this tut or retire this tut soon.

**Comment by NukeManDan** [comment]
I think its very valuable. It shows best practices to contribute to our ecosystem via a pallet. Do you have bandwidth for this @jimmychu0807 ?

**Comment by sacha-l** [comment]
This sounds like better content for a how-to guide. Should I make one and then we can archive this?

**Comment by jimmychu0807** [comment]
@sacha-l Actually these two tutorials, [Add a Pallet to your Runtime](https://substrate.dev/docs/en/tutorials/add-a-pallet/) and [Write a Pallet in its own Crate](https://substrate.dev/docs/en/tutorials/create-a-pallet/), have a lot of content overlapping each others. The only subject that the second tut added on is about publishing the pallet in github and crate.io. This is what I am trying to add to the first tut via this PR: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/1061, and proposing to removing the 2nd tut altogether.

So I think just keeping one tut is enough.
