### ISSUE TITLE
Move this repo to substrate-developer-hub.github.io

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#96]
We want this docusaurus site to be our org page, so the repo must be [named appropriately](https://help.github.com/en/articles/user-organization-and-project-pages#user-and-organization-pages-sites)

This will also require:
docusaurus will build to master
docs edits will be made on source
source will be default github branch
update CI accordingly

**Comment by shawntabrizi** [comment]
These are the instructions from the docusaurus side: https://github.com/facebook/Docusaurus/blob/master/docs/getting-started-publishing.md#using-github-pages

> Note: When you deploy as user/organization page, the publish script will deploy these sites to the root of the master branch of the username.github.io repo. In this case, note that you will want to have the Docusaurus infra, your docs, etc. either in another branch of the username.github.io repo (e.g., maybe call it source), or in another, separate repo (e.g. in the same as the documented source code).

**Comment by JoshOrndorff** [comment]
This is done and the build is passing again!

Make sure to update your remotes and branches. **Default branch is source**.
