### ISSUE TITLE
Clarify Exectutor CLI and internal API mapping

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#963]
#922 left a few things unclear:
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/922#discussion_r605348803

The present docs don't mention the CLI options and how they map to the actually executed API (that is detailed in the docs now)

**Comment by jimmychu0807** [comment]
I see what you mean. Let me add this in.

cli arg Native maps to sc_client_api NativeWhenPossible
cli arg Wasm maps to sc_client_api AlwaysWasm
cli arg Both maps to sc_client_api Both
cli arg NativeElseWasm maps to sc_client_api NativeElseWasm
