### ISSUE TITLE
Developer Documentation Needed on Proper Usage of Reference Counters

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#965]
After a review of: https://github.com/paritytech/substrate/pull/8221

The auditing team said it would be important to document how to correctly use the different reference counters so that third party teams do not make mistakes and get accounts into locked states.

A technical writer can work with me to get a better understanding of reference counters and then work to write up documentation which covers this within the DevHub or even the inline documentation.

**Comment by jimmychu0807** [comment]
let me work on this next week.

**Comment by jimmychu0807** [comment]
- https://github.com/paritytech/substrate/pull/8221/
- https://github.com/paritytech/substrate/pull/8220
- https://github.com/paritytech/substrate/issues/5255

@shawntabrizi I start to work on this. I went over Substrate PR #8221, see the keys are on having `{ consumers, providers, sufficients }` in `AccountInfo`. I also see the intricate logic when incrementing and decrementing each of them in the `dec_{providers, consumers, sufficients}`, and `inc_{providers, consumers, sufficients}` methods. I check and see the test cases.

But I wonder how should this be documented? Current there is almost no use of `inc_sufficients`, a few uses of `inc_providers` in the src, and moderate uses of `inc_consumers` by frame_balances, pallet_recovery. It seems to me this is some kind of internal state tracking variables. I am thinking what is a good approach of writing the doc for these three variables so runtime developers can start using them in their work?

**Comment by shawntabrizi** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1860335/117219841-144a0780-add4-11eb-91f2-71dab88b9214.png">
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1860335/117219861-1ca24280-add4-11eb-89d1-79f225719995.png">
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1860335/117219878-25931400-add4-11eb-91e6-8c5c247a2ba4.png">
