### ISSUE TITLE
Newsletter page not rendering. Does the newsletter exist?

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#968]
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/59187679bc1b4cd7c4eda38dc8996314ea59cbe4/website/pages/en/newsletter.js#L8

I can't get this to render locally or on the deployed site. All blocking off.... @imadarai this may be a bug, but I also am not aware of a newsletter for Substrate and/or Parity... Am I missing this?

**Comment by jimmychu0807** [comment]
This is what I see when loading the newsletter page. Do you have some ad-blocking plugin in your browser that block this script to load?

We don't really have Substrate Newsletter. The closest we get is the Technical Newsletter written by Stefan 

@stefan-sopic, how are you getting the email list recipients for the technical newsletter? Are you getting them from activehosted.com?

![Screenshot 2021-04-10 at 17 49 36](https://user-images.githubusercontent.com/898091/114265753-2b8c1400-9a25-11eb-886f-c285cc5f212d.png)

**Comment by NukeManDan** [comment]
AFAIK the newsletter is _parity internal only_ that Stefan produces. Who would know where this data is aggregated and used?

**Comment by NukeManDan** [comment]
AFAIK the newsletter is _parity internal only_ that Stefan produces. Parity has a new newsletter in development that will use this list 🔜 ™️ 

The https://ublockorigin.com/ extention (that we are supposed to be using while browsing @jimmychu0807 😉 ) is the likely cause, it has done this before. cc @imadarai for note if/when this gets a facelift

**Comment by jimmychu0807** [comment]
I will close this for now, as the newsletter strategy is out of scope for the substrate.dev website.

**Comment by NukeManDan** [comment]
sure, but the site itself still has this issue. And the newsletter is still listed on it. So I would keep this open until:
- we close this newsletter to new signups and remove the page
- we fix the issues with site blockers and make the signup more visible (design team would decide this)

**Comment by imadarai** [comment]
@NukeManDan @jimmychu0807 
(for some reason I've been not being notified, so just catching up on this) 

I recently solved this for parity.io migration and will apply the same ActiveCampaign API changes to this as well.  @NukeManDan I might ping you to test it to make sure the blockers are not causing any trouble. 
I'll sync with Marcomms over future of this list and get back to you.  

Will keep you guys posted.

**Comment by imadarai** [comment]
@NukeManDan @jimmychu0807  I looked into this today. 

The API implementation for ActiveCampaign requires (or nice to have) access to React lifecycle methods, which are stripped in Docusaurus versions under 2.0.  

Was it ever considered to migrate Docusaurus to V2?   Or is there a particular reason we haven't done that yet?

**Comment by jimmychu0807** [comment]
The devhub main site is using Docusaurus v1 now. We haven't migrated because it may not worth the migration when it is going to be revamped in 2-3 mo down the road.

**Comment by NukeManDan** [comment]
@sacha-l now maintaining the newsletter 🥳
