### ISSUE TITLE
Plan and execute substrate.dev domain migration

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-developer-hub.github.io#97]
We need to know who can admin the substrate.dev domain.

Kirill recommended we transfer it to the gandi.net registrar, but that could be done after the new devhub is live.

Felix and Gabriel were confident that directing it to github pages would not be a problem. It should be even easier now that we're hosting as an organization page (https://github.com/substrate-developer-hub/docs/issues/96)

**Comment by fevo1971** [comment]
* Me and David have access to the Namecheap account and can do the necessary changes to the DNS, no problem. 

* Moving the domains away to a different registrar is unrelated i think. It might or might not be done in the future.

* If i remember right the new site will be hosted as a (static) GitHub-Pages site with a custom domain (like docs.substrate.dev or the like), so what we need is:
    * Someone with (admin)access to the GitHub project (maybe Eric?)
    * The domain/hostnames that need to be changed/added in the DNS (the same that now point to the readme.io?)

**Comment by JoshOrndorff** [comment]
Thanks for that info @fevo1971 . Great to hear you have access to the namecheap account.

Let's forget about transferring the registrar. I'll leave it up to Kirill to push for that after the migration if he wants it.

I am an owner of this repo, so I should be able to do whatever you need in that regard.

When we make the transfer, we want to point just plain `substrate.dev` to `substrate-developer-hub.github.io`. I'm expecting to make this transfer early next week.

**Comment by shawntabrizi** [comment]
The domain `substrate.dev` has been attached to the repo, so all we need to do is update the A-NAME and C-NAME stuff once we are ready.

https://help.github.com/en/articles/setting-up-an-apex-domain-and-www-subdomain

We should do it for **both** the apex domain and www subdomain, thus `www.substrate.dev` will redirect to `substrate.dev`

**Comment by JoshOrndorff** [comment]
We attempted to change the DNS today, but ran into some unexpected issues. Here's as much as I know.

![image](https://user-images.githubusercontent.com/2915325/59360236-bd2d7c00-8cfd-11e9-8ee3-5475beb02f01.png)

**Comment by JoshOrndorff** [comment]
Excellent work @fevo1971 and @shawntabrizi on getting the domain changed and redirected!
