### ISSUE TITLE
Possibly incorrect link to proof of existence

### ISSUE THREAD

**Issue by MihirLuthra** [substrate-developer-hub/substrate-developer-hub.github.io#971]
In the tutorial ["Build a PoE Decentralized Application"](https://substrate.dev/docs/en/tutorials/build-a-dapp/), the link to Proof of existence seems to be incorrect. It redirects to [Constructive Proof](https://en.wikipedia.org/wiki/Constructive_proof).

I am not sure where was it intended to point to and I can't find any wikipedia articles for PoE chains.

**Comment by NukeManDan** [comment]
Constructive proof from the wiki:
> In mathematics, a constructive proof is a method of proof that demonstrates the existence of a mathematical object by creating or providing a method for creating the object.

This is what the PoE chain is all about: using a hash of data to (mathematically) prove the existence of that data. So the redirect makes sense to me 😁 

If you have further questions, be sure to join us in https://matrix.to/#/#substratetechnical:matrix.org about substrate development questions in general 😁
