### ISSUE TITLE
Connecting to FE and node template on different machines

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#976]
Those using VMs and containers locally to manage nodes will need to use the following:

## Node host machine
```shell
# find your local IP
ip a
# note the IP, as we need it for the FE next.
# start the node on any LAN connected machine 
./target/release/node-template --dev --tmp --unsafe-rpc-external --unsafe-ws-external
# take note of the "listening for connection on..." section, should be 0.0.0.0:<ws port, likely 9944>
```

## FE host machine

```shell
# edit the web socket the FE template wants to use:
nano  substrate-front-end-template/src/config/development.json
```
you will set this to:
```json
{
  "PROVIDER_SOCKET": "ws://<ip of your node>:<ws port, likely 9944>"
}
```
Then start the FE
```shell
# start the FE template on any LAN connected machine 
yarn start
# take note of the IP and port on your local network the interface is viewable at:
#   Local:            http://localhost:8000/substrate-front-end-template
#   On Your Network:  http://<ip of your FE template host>:8000/substrate-front-end-template
```

This should now work as expected for a LAN. for **testing only!** unsafe to use this in production. 
Next steps would be to try the private/multi-node network tutorial to connect multiple nodes on the LAN this way. Possibly with a demo using containers.

**Comment by kwikiel** [comment]
I volunteer for working on this. I've spent few unnecessary hours researching how to host chain/frontend on the server and connect via browser from the other machine. I will help others avoid it in the future

**Comment by NukeManDan** [comment]
@kwikiel awesome! Let me know how I can assist it at all 🙏🏼

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-docs/issues/173
