### ISSUE TITLE
How to introduce and demonstrate substrate playground?

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#977]
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/commits/df/tut/playground

@sacha-l / @jimmychu0807 / @jeluard  - this (now stale) tutorial was to replace (or be an alternative to) the "add a pallet" nicks tutorial using the playground. It would need a rework to get it ready to publish, but if we want to highlight playground in general, this could be the go-to referenced as an alternative to building on your local machine as an example of using the playground. 

What are your thoughts or getting this reworked and published? Or better alternatives to show off playground on the devhub?

**Comment by jeluard** [comment]
Playground can be better integrated using some kind of JS integration. Would it be doable with the current framework?

Also I understand there is some work being done on devhub as a whole.

**Comment by jimmychu0807** [comment]
@NukeManDan 
hmm... I have never tried this branch, and this branch seems really old. Did you run this branch. If that's handy, can you make a screenshot how playground is integrated in this branch?

**Comment by sacha-l** [comment]
@jimmychu0807 Its a tutorial that incorporates using Playground to complete it, using screenshots of Playground for relevant steps. I think it was a great initiative but we should leave it out for that sake of not risking wasted efforts once we get integrating Playground in all tutorials (one day!)

**Comment by jimmychu0807** [comment]
I am thinking to have a better integration between Substrate Node template and playground, adding a link on top of the node template readme. Once the integration is stabilised, we can do further integration from knowledge base to playground.

**Comment by NukeManDan** [comment]
Let''s open a new issue for the new docs if needed https://github.com/substrate-developer-hub/substrate-docs/
