### ISSUE TITLE
CI link checking broken, not reproducable locally. 

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-developer-hub.github.io#979]
@TriplEight in #978 I can verify that one of the two exact same links is not being rendered correctly. This is *NOT* reproducable locally, and strange that only one link get's malformed. (should be http://localhost:3000/docs/en/knowledgebase/getting-started/index#troubleshooting-substrate-builds and it doesn't get the propper `../` so what CI gets is http://localhost:3000/docs/en/tutorials/knowledgebase/getting-started/index#troubleshooting-substrate-builds )

What can be done to fix this?

**Comment by TriplEight** [comment]
sorry, I'm not that familiar with this repo, could you explain a bit, please?

**Comment by NukeManDan** [comment]
this is the https://substrate.dev source @TriplEight 

AFAIK the `source` branch here should be what is built and published on every merge to that branch.

**Comment by jimmychu0807** [comment]
The linkchecker ignore pattern [defined here](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/.circleci/config.yml#L101) is wrong:

```
linkchecker --ignore-url="^(?:(?!\/en\/).)*$" --check-extern http://localhost:3000/
```

But if I set it to a more appropriate `"^.*(?:zh-CN)+.*$"` there will be links tested that exceed the rate limit and return max connection error.

**Comment by TriplEight** [comment]
is this still relevant?

**Comment by NukeManDan** [comment]
We are migrating to a new docs repo, so maybe not super important @TriplEight 

Still the link checker fails often
